### ISSUE TITLE
Force close while creating freeze/unfreeze shortcut 

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1048]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App force stop while creating shortcut 

### Logs

java.lang.IllegalStateException: Immutable bitmap passed to Canvas constructor
    at android.graphics.Canvas.<init>(Canvas.java:114)
    at io.github.muntashirakon.AppManager.utils.UIUtils.setBrightness(UIUtils.java:363)
    at io.github.muntashirakon.AppManager.utils.UIUtils.dimBitmap(UIUtils.java:353)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$createFreezeShortcut$120$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:1648)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:4)
    at io.github.muntashirakon.dialog.SearchableMultiChoiceDialogBuilder.lambda$setPositiveButton$1$io-github-muntashirakon-dialog-SearchableMultiChoiceDialogBuilder(SearchableMultiChoiceDialogBuilder.java:188)
    at io.github.muntashirakon.dialog.SearchableMultiChoiceDialogBuilder$$ExternalSyntheticLambda4.onClick(Unknown Source:4)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8380)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Device Info:
App version: 3.1.0-2306-DEBUG
App version code: 423
Android build version: R.ea140a_881c7_5650b
Android release version: 13
Android SDK version: 33
Android build ID: RMX3461_11_F.04
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: root

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment]
Fixed in 09724d2a36839dc801a9f0f2aa5f371a10f81498
