### ISSUE TITLE
App Manager crashes after opening Trichrome Library in apps list [3.2.0-alpha01]

### ISSUE THREAD

**Issue by resiehnnes** [MuntashirAkon/AppManager#1054]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

As the title states. Providing crash report.

### Logs

java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown package: com.google.android.trichromelibrary
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfo$1(AppInfoViewModel.java:346)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
 Caused by: java.lang.IllegalArgumentException: Unknown package: com.google.android.trichromelibrary
   at android.os.Parcel.createException(Parcel.java:2095)
   at android.os.Parcel.readException(Parcel.java:2059)
   at android.os.Parcel.readException(Parcel.java:2007)
   at android.content.pm.IPackageManager$Stub$Proxy.getInstallerPackageName(IPackageManager.java:6671)
   at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstallSourceInfo(PackageManagerCompat.java:246)
   at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstallerPackageName(PackageManagerCompat.java:237)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadAppInfo(AppInfoViewModel.java:317)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1660)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.$r8$lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda79.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   at java.lang.Thread.run(Thread.java:929)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4848)
	at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:25094)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3049)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4926)
	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:472)
callee: null 1554/1570

### Device info

Device Info:
App version: 3.2.0-alpha01
App version code: 433
Android build version: 10.1.0.150C431
Android release version: 10
Android SDK version: 29
Android build ID: VOG-L29 10.1.0.150(C431E19R2P5)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWVOG
Device model: VOG-L29
Device product name: VOG-L29EEA
Device hardware name: kirin980
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-NO
In-App Language: auto
Mode: auto
Inferred Mode: ADB

**Comment by MuntashirAkon** [comment]
Fixed in 20f0fb4761f1ffa6b1cd6310f92471c1badf090e
