### ISSUE TITLE
Crash on ListOptionsActions

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1059]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashed when "Split screen" or "Freeform" mode while on Main Page with List options view.

### To Reproduce

1. Open AM. Click on "List options" (view bottom sheet)
2. Perform "Split screen" or "Freeform" mode
3. See error

### Logs

```
java.lang.NullPointerException: ListOptionsActions must be set before calling init.
    at io.github.muntashirakon.AppManager.misc.ListOptions.requireListOptionActions(ListOptions.java:122)
    at io.github.muntashirakon.AppManager.misc.ListOptions.init(ListOptions.java:140)
    at io.github.muntashirakon.AppManager.misc.ListOptions.onViewCreated(ListOptions.java:101)
    at io.github.muntashirakon.AppManager.main.MainListOptions.onViewCreated(MainListOptions.java:115)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
    at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
    at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
    at io.github.muntashirakon.AppManager.BaseActivity.onStart(BaseActivity.java:165)
    at io.github.muntashirakon.AppManager.main.MainActivity.onStart(MainActivity.java:542)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1457)
    at android.app.Activity.performStart(Activity.java:8259)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3776)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

Device Info:
App version: **3.2.0-alpha01-DEBUG**
App version code: 433
Android build version: 1ec84-76c7d7
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-5
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: no_root

### Additional context

Logs from Android: 8

<details>
  <summary>logs</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.MainActivity}: java.lang.NullPointerException: ListOptionsActions must be set before calling init.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
    at android.app.ActivityThread.-wrap18(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.NullPointerException: ListOptionsActions must be set before calling init.
   at io.github.muntashirakon.AppManager.misc.ListOptions.requireListOptionActions(ListOptions.java:122)
   at io.github.muntashirakon.AppManager.misc.ListOptions.init(ListOptions.java:140)
   at io.github.muntashirakon.AppManager.misc.ListOptions.onViewCreated(ListOptions.java:101)
   at io.github.muntashirakon.AppManager.main.MainListOptions.onViewCreated(MainListOptions.java:115)
   at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
   at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
   at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
   at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
   at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
   at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
   at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
   at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
   at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
   at io.github.muntashirakon.AppManager.BaseActivity.onStart(BaseActivity.java:165)
   at io.github.muntashirakon.AppManager.main.MainActivity.onStart(MainActivity.java:542)
   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
   at android.app.Activity.performStart(Activity.java:7043)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
   at android.app.ActivityThread.-wrap18(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Device Info:
App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: no_root
```

**Comment by MuntashirAkon** [comment]
Fixed in 5d1c196e99e2abf9ac5518144e2b9cbf5b7c9a97
