### ISSUE TITLE
Code Editor crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1062]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM, code editor crashed while I tried to reopen from device recent apps. Intermittent crash.

### To Reproduce

1. Open AM > Code Editor
2. Add some texts there
3. Open another app (in my case browser application)
4. Reopen Code Editor from device recent apps
5. See Error...

### Expected behavior

Reopen Code Editor from device recent & continue from where you left.

### Logs

```
java.lang.RuntimeException: Unable to resume activity {io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.editor.CodeEditorActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.NullPointerException
   at j$.util.Objects.requireNonNull(Objects.java:219)
   at io.github.muntashirakon.AppManager.editor.CodeEditorFragment.requireActionBar(CodeEditorFragment.java:615)
   at io.github.muntashirakon.AppManager.editor.CodeEditorFragment.onResume(CodeEditorFragment.java:537)
   at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
   at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
   at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
   at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
   at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
   at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
   at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
   at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
   at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
   at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:245)
   at android.app.Activity.performResume(Activity.java:7155)
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3559)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
   at android.app.ActivityThread.-wrap11(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Device info

App version: **3.2.0-alpha01-DEBUG**
App version code: 433
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: no_root

**Comment by MuntashirAkon** [comment]
Fixed in dadb35e47b7394b710f3638e6d0da8744e0fce8a
