### ISSUE TITLE
Crash on `intent://settings/rules_prefs/freeze_type`

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1079]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashed when clicked on `Settings > Rules > Default freezing method ` from docs.

### To Reproduce

1. Open AM > User Manual
2. Search "Default freezing method"
3. Click on `Settings > Rules > Default freezing method ` hyperlink

### Expected behavior

Should open "Default freezing method" option from AM settings.

### Logs

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=intent://settings/rules_prefs/freeze_type }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2181)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1812)
    at android.app.Activity.startActivityForResult(Activity.java:5506)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
    at android.app.Activity.startActivityForResult(Activity.java:5464)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
    at android.app.Activity.startActivity(Activity.java:5854)
    at android.app.Activity.startActivity(Activity.java:5807)
    at io.github.muntashirakon.AppManager.misc.HelpActivity$WebViewClientImpl.shouldOverrideUrlLoading(HelpActivity.java:157)
    at java.lang.reflect.Method.invoke(Native Method)
    at Xf.invoke(chromium-SystemWebViewGoogle.aab-stable-561513603:36)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy2.shouldOverrideUrlLoading(Unknown Source)
    at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-SystemWebViewGoogle.aab-stable-561513603:77)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:342)
    at android.os.Looper.loopOnce(Looper.java:182)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 1ec84-76c7d7
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-5
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: no_root

**Comment by MuntashirAkon** [comment]
Fixed in 66997942bc31d2a4afdd6e0cf560fc43f6466d30
