### ISSUE TITLE
Force stop while accessing root folder 

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1081]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Force stops fm root folder access

### Logs

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
    at io.github.muntashirakon.io.Path.needPrivilegedAccess(Path.java:131)
    at io.github.muntashirakon.io.Path.getRequiredRawDocument(Path.java:141)
    at io.github.muntashirakon.io.Path.<init>(Path.java:201)
    at io.github.muntashirakon.io.Paths.get(Paths.java:76)
    at io.github.muntashirakon.AppManager.fm.FmViewModel.loadFiles(FmViewModel.java:147)
    at io.github.muntashirakon.AppManager.fm.FmPathListAdapter.lambda$onBindViewHolder$0$io-github-muntashirakon-AppManager-fm-FmPathListAdapter(FmPathListAdapter.java:103)
    at io.github.muntashirakon.AppManager.fm.FmPathListAdapter$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7558)
    at android.view.View.performClickInternal(View.java:7534)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29661)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8381)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Device Info:
App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: R.105741b-5f5a-5f59
Android release version: 13
Android SDK version: 33
Android build ID: RMX3461_11_F.07
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: root

### Device info

Device Info:
App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: R.105741b-5f5a-5f59
Android release version: 13
Android SDK version: 33
Android build ID: RMX3461_11_F.07
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in 7af167857d6206702d7a4a5bce74d7e2d67db270
