### ISSUE TITLE
Crash  appmanager installer in work profile

### ISSUE THREAD

**Issue by userkilled** [MuntashirAkon/AppManager#1089]
Logs

java.lang.SecurityException: createSession: Neither user 1210145 nor current process has android.permission.INTERACT_ACROSS_USERS_FULL.
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:426)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:726)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:574)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:168)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:53)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.os.HandlerThread.run(HandlerThread.java:67)
 Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1897)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1925)
	at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(PermissionManagerService.java:3053)
	at com.android.server.pm.permission.PermissionManagerService.access$2100(PermissionManagerService.java:125)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.enforceCrossUserPermission(PermissionManagerService.java:3279)

Device Info:
App version: 3.1.1
App version code: 424
Android build version: 1596015452
Android release version: 10
Android SDK version: 29
Android build ID: BV6300Pro_S1_200729
Device brand: Blackview
Device manufacturer: wheatek
Device name: BV6300Pro
Device model: BV6300Pro
Device product name: BV6300Pro_RU
Device hardware name: mt6771
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ru-RU
In-App Language: auto
Mode: auto
Inferred Mode: no_root

**Comment by MuntashirAkon** [comment]
App Manager installed in the main profile or the work profile?

**Comment by userkilled** [comment]
App manager installed in work profile

**Comment by MuntashirAkon** [comment]
Fixed via 6f824eb83523b6931fa93afc5cf68c4b39d7cd4e. App Manager was wrongfully installing the app for main profile instead of current profile.
