### ISSUE TITLE
Bug in install apk,apks in work profile in version 3.1.0 /3.1.1

### ISSUE THREAD

**Issue by Stu75e** [MuntashirAkon/AppManager#1090]
java.lang.SecurityException: createSession: Requires android.permission.INTERACT_ACROSS_USERS_FULL.
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2386)
    at android.os.Parcel.createException(Parcel.java:2370)
    at android.os.Parcel.readException(Parcel.java:2353)
    at android.os.Parcel.readException(Parcel.java:2295)
    at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:474)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:726)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:574)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:168)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:53)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 3.1.1
App version code: 424
Android build version: 
Android release version: 11
Android SDK version: 30
Android build ID: 
Device brand: samsung
Device manufacturer: samsung
Device name: 
Device model:
Device product name:
Device hardware name:
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: auto
Inferred Mode: no_root

**Comment by MuntashirAkon** [comment]
Duplicate of #1089
