### ISSUE TITLE
Crash | `DeadSystemException`

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1095]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Simply updated to debug version: `AM Debug v3.2.0-alpha01 Run#2394` & opened it. App crashed for some unknown reason. 1time crash.

### Logs

```
java.lang.RuntimeException: android.os.DeadSystemException
    at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
 Caused by: android.os.DeadSystemException
   at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
   at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
   at android.os.Handler.handleCallback(Handler.java:978)
   at android.os.Handler.dispatchMessage(Handler.java:104)
   at android.os.Looper.loopOnce(Looper.java:238)
   at android.os.Looper.loop(Looper.java:357)
   at android.app.ActivityThread.main(ActivityThread.java:8090)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 1ec84-76c7d7
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-5
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: No root

**Comment by MuntashirAkon** [comment]
Backtrace says it's produced by the framework, not App Manager.

**Comment by MuntashirAkon** [comment]
Crashes emitted by the system cannot be fixed in App Manager.
