### ISSUE TITLE
Restore backup app (bug)

### ISSUE THREAD

**Issue by Stu75e** [MuntashirAkon/AppManager#1096]
====> op=BACKUP_RESTORE, mode=2 pkg=(com.google.android.apps.docs, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred
	at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:212)
	at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:176)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:337)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.SecurityException: Package com.android.vending does not belong to 10950
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2386)
	at android.os.Parcel.createException(Parcel.java:2370)
	at android.os.Parcel.readException(Parcel.java:2353)
	at android.os.Parcel.readException(Parcel.java:2295)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:474)
	at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:726)
	at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:616)
	at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:349)
	at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:197)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7783)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:713)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:623)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:202)
	at android.os.Binder.execTransactInternal(Binder.java:1195)

**Comment by MuntashirAkon** [comment]
Closed because the issue doesn't follow any template.
