### ISSUE TITLE
crashes when creating a backup

### ISSUE THREAD

**Issue by OmlineEditor** [MuntashirAkon/AppManager#1097]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm trying to make a backup of the whatsapp application data

### To Reproduce

1 find whatsapp 
2 click on it to open the menu where you select backup
3 I choose only data
I click create and the application crashes

### Expected behavior

a backup was created

### Logs

====> op=BACKUP_RESTORE, mode=1 pkg=(com.whatsapp, 0)
io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:163)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:98)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:331)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Device info

- Device: Redmi Note 7
- OS Version: Android 10
- App Manager Version:  3.1.1 F-droid
- Mode: Root

**Comment by MuntashirAkon** [comment]
You said App Manager crashed, but your included logs from failed backups which says _The app has keystore items and KeyStore backup isn't enabled._ meaning you haven't enabled restoring apps with keystore from settings.

**Comment by OmlineEditor** [comment]
after changing the settings, the application does not crash and makes backups. I ask you to make changes to the application and display an alert with a clear description so that people know that they need to use keys for archiving

**Comment by MuntashirAkon** [comment]
I'm still waiting for a crash log though. The logs you shared aren't crash logs. They indicated why a backup failed which is well documented in the docs.

**Comment by OmlineEditor** [comment]
the application has stopped crashing, although it has fallen every time before, perhaps this is spontaneous behavior. I'll wait some more and try later.
