### ISSUE TITLE
Activities, Services, Receivers crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1105]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Opening _Activities_, _Services_ or _Receivers_ crashes the app. Latest debug version : `AM Debug v3.2.0-alpha01 Run#2418`

### To Reproduce

1. Open activities/Services/Receivers of any app
2. See error

### Logs

```
java.lang.NullPointerException: permission must be non-null
    at androidx.core.util.ObjectsCompat.requireNonNull(ObjectsCompat.java:159)
    at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:600)
    at io.github.muntashirakon.AppManager.self.SelfPermissions.checkSelfPermission(SelfPermissions.java:170)
    at io.github.muntashirakon.AppManager.self.SelfPermissions.checkSelfOrRemotePermission(SelfPermissions.java:166)
    at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment.canLaunchService(AppDetailsComponentsFragment.java:785)
    at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.getServicesView(AppDetailsComponentsFragment.java:614)
    at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsComponentsFragment.java:386)
    at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsComponentsFragment.java:271)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:831)
    at android.view.View.layout(View.java:23265)
    at android.view.ViewGroup.layout(ViewGroup.java:6415)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3869)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3328)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2282)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8986)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: No root

**Comment by MuntashirAkon** [comment]
Fixed via e4e339ceece4725ca1e22a50b7a35d9bf5876772
