### ISSUE TITLE
FM | Open with crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1109]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM filemanager open with crashes ifvyou pick any option/app.

### To Reproduce

1. Open AM Labs > Files
2. Click on any file (open with) > pick any option
3. See error

### Logs

```
java.lang.NullPointerException: package name is null
    at android.content.ComponentName.<init>(ComponentName.java:103)
    at android.content.Intent.setClassName(Intent.java:10353)
    at io.github.muntashirakon.AppManager.fm.OpenWithDialogFragment$MatchingActivitiesRecyclerViewAdapter.lambda$onBindViewHolder$0$io-github-muntashirakon-AppManager-fm-OpenWithDialogFragment$MatchingActivitiesRecyclerViewAdapter(OpenWithDialogFragment.java:349)
    at io.github.muntashirakon.AppManager.fm.OpenWithDialogFragment$MatchingActivitiesRecyclerViewAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
    at android.view.View.performClick(View.java:7467)
    at android.view.View.performClickInternal(View.java:7444)
    at android.view.View.access$3700(View.java:840)
    at android.view.View$PerformClick.run(View.java:28831)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: ADB

**Comment by MuntashirAkon** [comment]
I guess I forgot to push the last commit: 4c0fdaf4af01c29048085766eb760b78e57a6f1e
