### ISSUE TITLE
Crash when freeze Trichrome Library

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1111]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App crashes when I try to Freeze Trichrome Library (`com.google.android.trichromelibrary`)
Latest` AM Debug v3.2.0-alpha01 Run#2445`

### To Reproduce

 - Open AM > Filter User apps
 - Search & open "Trichrome Library" App Info page
 - Click on Freeze (used freezing method : _Disable_)
 - See error

### Logs

```
java.lang.IllegalArgumentException: Unknown package: com.google.android.trichromelibrary
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
    at android.os.Parcel.createException(Parcel.java:2410)
    at android.os.Parcel.readException(Parcel.java:2393)
    at android.os.Parcel.readException(Parcel.java:2335)
    at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:7355)
    at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.setApplicationEnabledSetting(PackageManagerCompat.java:328)
    at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:71)
    at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:45)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.freeze(AppInfoFragment.java:1701)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$setHorizontalActions$75$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:1060)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda105.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7467)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
    at android.view.View.performClickInternal(View.java:7444)
    at android.view.View.access$3700(View.java:840)
    at android.view.View$PerformClick.run(View.java:28831)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:24572)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:24437)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3375)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9065)
	at android.os.Binder.execTransactInternal(Binder.java:1192)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: ADB

### Additional context

I can't find this "Trichrome Library" _user app_ on my system settings even after enabling system apps.

Results if I perform following operations for this app from AM main screen.

- Clear Data
```
====> op=CLEAR_DATA, pkg=(com.google.android.trichromelibrary, 0)
android.util.AndroidException: Could not clear data of package (com.google.android.trichromelibrary, 0)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.clearApplicationUserData(PackageManagerCompat.java:425)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opClearData(BatchOpsManager.java:547)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:250)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:160)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
====> op=CLEAR_DATA, pkg=(com.google.android.trichromelibrary, 10)
android.util.AndroidException: Could not clear data of package (com.google.android.trichromelibrary, 10)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.clearApplicationUserData(PackageManagerCompat.java:425)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opClearData(BatchOpsManager.java:547)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:250)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:160)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

- Freeze
```
====> op=APP_FREEZE, pkg=(com.google.android.trichromelibrary, 0), freeze = true
java.lang.IllegalArgumentException: Unknown package: com.google.android.trichromelibrary
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:7355)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.setApplicationEnabledSetting(PackageManagerCompat.java:328)
	at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:71)
	at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:45)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opFreeze(BatchOpsManager.java:565)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:254)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:160)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:24572)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:24437)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3375)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9065)
	at android.os.Binder.execTransactInternal(Binder.java:1192)

====> op=APP_FREEZE, pkg=(com.google.android.trichromelibrary, 10), freeze = true
java.lang.IllegalArgumentException: Unknown package: com.google.android.trichromelibrary
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:7355)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.setApplicationEnabledSetting(PackageManagerCompat.java:328)
	at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:71)
	at io.github.muntashirakon.AppManager.utils.FreezeUtils.freeze(FreezeUtils.java:45)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opFreeze(BatchOpsManager.java:565)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:254)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:160)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

- Uninstall
```
====> op=UNINSTALL, pkg=(com.google.android.trichromelibrary, 0)
====> op=UNINSTALL, pkg=(com.google.android.trichromelibrary, 10)
```

- Other operations like Force-stop, Prevent background operations, Save APK etcetera works.

**Comment by MuntashirAkon** [comment]
ddac2f5824920241b1899809e0b994d5fd08bf62

**Comment by MuntashirAkon** [comment]
You can't find this app because it's not an app, it's a library.

**Comment by shuvashish76** [comment]
Thanks. Why it is listed as 'user app' in AM?

**Comment by MuntashirAkon** [comment]
Because it wasn't in your system partition.
