### ISSUE TITLE
App Usage | Crash when click on apps quickly

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1113]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashes when open App Usage > & try to click on different apps multiple times very quickly.

### Logs

```
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
    at android.view.ViewGroup.addView(ViewGroup.java:5068)
    at android.view.ViewGroup.addView(ViewGroup.java:5048)
    at io.github.muntashirakon.dialog.CapsuleBottomSheetDialogFragment.finishLoading(CapsuleBottomSheetDialogFragment.java:127)
    at io.github.muntashirakon.AppManager.usage.AppUsageDetailsDialog$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 3.2.0-alpha01-DEBUG
App version code: 433
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: ADB

**Comment by MuntashirAkon** [comment]
Should be fixed now.
