### ISSUE TITLE
AM crashes without SAF

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1137]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

~Not sure what I changed, recently AM crashing everytime I export any profile.~
See my next comment.

### To Reproduce

1. Long click on any profile > Export
3. See error

### Logs

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=application/json (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2181)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1812)
    at android.app.Activity.startActivityForResult(Activity.java:5506)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
    at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:858)
    at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:247)
    at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:243)
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at io.github.muntashirakon.AppManager.profiles.ProfilesActivity$ProfilesAdapter.lambda$onBindViewHolder$5$io-github-muntashirakon-AppManager-profiles-ProfilesActivity$ProfilesAdapter(ProfilesActivity.java:290)
    at io.github.muntashirakon.AppManager.profiles.ProfilesActivity$ProfilesAdapter$$ExternalSyntheticLambda4.onMenuItemClick(Unknown Source:4)
    at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
    at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3216)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:4204)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3945)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:236)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:140)
    at android.view.View.dispatchTouchEvent(View.java:14601)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2572)
    at android.view.View.dispatchPointerEvent(View.java:14884)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6598)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6399)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5877)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5934)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5900)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6065)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5908)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6122)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5881)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5934)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5900)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5908)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5881)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8895)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8811)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8780)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9031)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:342)
    at android.os.Looper.loopOnce(Looper.java:182)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 4.0.0-alpha01
App version code: 434
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: Root

**Comment by shuvashish76** [comment]
Looks like I disabled `com.google.android.documentsui`. Enabled & now everything is fine.
Some features like Save APK, Backup/Restore works without SAF, but Export app list, Export blocking rules, Extract icons etc crashes.

**Expected behavior:** 
Instead show message like 👇
![SAF](https://github.com/MuntashirAkon/AppManager/assets/48226312/c597fee5-485d-4f8a-814c-ea2f7eef19a0)
screenshot source: Neo Backup

**Additional context:**
https://github.com/NeoApplications/Neo-Backup/blob/main/FAQ.md#what-should-i-do-when-i-get-the-no-saf-manager-message

**Comment by MuntashirAkon** [comment]
**Files** app is not just another file manager, this is a core package of Android that provides the UI to manage Android's own file system (marked as unsafe in Android Debloat List). Disabling a core package is both crazy and stupid thing to do. It's like deleting the system partition and then asking why the phone is not booting. This is why App Manager does not attempt to handle those situations.

**Comment by shuvashish76** [comment]
Thanks.

> marked as unsafe in Android Debloat List

`com.android.documentsui` : [unsafe](https://github.com/MuntashirAkon/android-debloat-list/blob/27b1fc028f7ceee4db48aca082aab6c55ca9d162/aosp.json#L217)
`com.google.android.documentsui` : [caution](https://github.com/MuntashirAkon/android-debloat-list/blob/27b1fc028f7ceee4db48aca082aab6c55ca9d162/google.json#L813) _(Another file browser can replace most of the functionality...Safe to disable.._)

**Comment by MuntashirAkon** [comment]
> `com.google.android.documentsui` : [caution](https://github.com/MuntashirAkon/android-debloat-list/blob/27b1fc028f7ceee4db48aca082aab6c55ca9d162/google.json#L813) _(Another file browser can replace most of the functionality...Safe to disable.._)

Updated.

**Comment by shuvashish76** [comment]
> Disabling a core package is both crazy and stupid thing to do...App Manager does not attempt to handle those situations.

Searched with keyword google > select all > freeze. This is the vendor ROM & there is no `com.android.documentsui` package. I'll be careful next time, thanks for the warning.
