### ISSUE TITLE
Can't Save APK for chrome

### ISSUE THREAD

**Issue by researchscum** [MuntashirAkon/AppManager#1162]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

when i tried to save apk for google chrome it failed.

### To Reproduce

- 1. Open AppManager
- 2. Search Chrome
- 3. Click google chrome icon
- 4. Click Save APK
- 5. There will be new floating notification "Couldn't backup 1 ... "

### Expected behavior

Succes in saving chrome apks

### Screenshots

![1693480076915](https://github.com/MuntashirAkon/AppManager/assets/97543175/b66f807b-f1e1-4de2-9d7b-456eff9566f8)

![1693480076912](https://github.com/MuntashirAkon/AppManager/assets/97543175/fcfe5db7-980c-49bf-94c9-a044dfe59956)

### Logs

====> op=BACKUP_APK, pkg=(com.android.chrome, 0)
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at io.github.muntashirakon.io.Path.needPrivilegedAccess(Path.java:136)
	at io.github.muntashirakon.io.Path.getRequiredRawDocument(Path.java:146)
	at io.github.muntashirakon.io.Path.<init>(Path.java:169)
	at io.github.muntashirakon.io.Paths.get(Paths.java:66)
	at io.github.muntashirakon.AppManager.apk.splitapk.SplitApkExporter.getAllApkFiles(SplitApkExporter.java:116)
	at io.github.muntashirakon.AppManager.apk.splitapk.SplitApkExporter.saveApkInternal(SplitApkExporter.java:55)
	at io.github.muntashirakon.AppManager.apk.splitapk.SplitApkExporter.saveApks(SplitApkExporter.java:49)
	at io.github.muntashirakon.AppManager.apk.splitapk.ApksMetadata.writeMetadata(ApksMetadata.java:177)
	at io.github.muntashirakon.AppManager.apk.splitapk.SplitApkExporter.saveApkInternal(SplitApkExporter.java:60)
	at io.github.muntashirakon.AppManager.apk.splitapk.SplitApkExporter.saveApks(SplitApkExporter.java:49)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:104)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:157)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

### Device info

- Device: POCO F3
- OS Version: MIUI 14 / Android 13
- App Manager Version: 4.0.0-alpha01 (434)
- Mode: Wireless debugging (Inferred mode: No root)

### Additional context

i tried android system webview but failed.
i tried other system app that have an update and split apk it succeed in saving apk.

in the case of chrome and android system webview when i click Back Up it succeed.

**Comment by MuntashirAkon** [comment]
When you export Chrome and WebView (if it's also by Google), App Manager attempts to backup the Trichrome APK as well (since it's a required dependency). Probably it's failing for some reason here. I'll look into this.

**Comment by MuntashirAkon** [comment]
May be fixed by 874d159c1a25cd6fa8d7392b2db403b55de7c4a6. If you're able to test debug builds via GitHub actions or Telegram channel, please let me know if it works. Otherwise, you'll have to wait for the next alpha release.

**Comment by MuntashirAkon** [comment]
@researchscum: Can you confirm that the fix above works since you're trying debug builds?
