### ISSUE TITLE
Enabling battery optimization for Galaxy store crashes the app

### ISSUE THREAD

**Issue by vordx** [MuntashirAkon/AppManager#1165]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Title, app manager crash when trying to enable the battery optimization for Galaxy store for example. 

### To Reproduce

Pick Galaxy store
3 dots menu
Battery optimization
Enable
Crash

### Expected behavior

Not sure 

### Screenshots

![Screenshot_20230903_173318_Settings](https://github.com/MuntashirAkon/AppManager/assets/39927714/062ed28f-852e-4d0c-98a5-4a746f86353e)

### Logs

java.lang.UnsupportedOperationException: Cannot remove system whitelisted app
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3035)
    at android.os.Parcel.createException(Parcel.java:3007)
    at android.os.Parcel.readException(Parcel.java:2990)
    at android.os.Parcel.readException(Parcel.java:2932)
    at android.os.IDeviceIdleController$Stub$Proxy.removePowerSaveWhitelistApp(IDeviceIdleController.java:553)
    at io.github.muntashirakon.AppManager.compat.DeviceIdleManagerCompat.enableBatteryOptimization(DeviceIdleManagerCompat.java:26)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$onOptionsItemSelected$16$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:440)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda41.onClick(Unknown Source:2)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.DeviceIdleController$BinderService.removePowerSaveWhitelistApp(DeviceIdleController.java:1847)
	at android.os.IDeviceIdleController$Stub.onTransact(IDeviceIdleController.java:288)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)

Device Info:
App version: 4.0.0-alpha01
App version code: 434
Android build version: S908EXXU6CWH3
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.S908EXXU6CWH3
Device brand: samsung
Device manufacturer: samsung
Device name: b0q
Device model: SM-S908E
Device product name: b0qxxx
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: adb_wifi
Inferred Mode: ADB

### Device info

- Device: Galaxy s22U. Snapdragon, SM-S908E
- OS Version: Android 13, oneui 5.1
- App Manager Version:4.0.0-alpha01 (434)
- Mode: ADB

**Comment by hirenshah** [comment]
I have the same issue if I try doing this for any system app which Samsung doesn't usually allow me to change via the usual Settings.

**Comment by MuntashirAkon** [comment]
This is because system whitelisted apps can't be optimised. I've already made a fix for it and will be available in the next release.
