### ISSUE TITLE
Backup Fail

### ISSUE THREAD

**Issue by Ahplla** [MuntashirAkon/AppManager#1175]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Trying backup a Bank App , get error

```
====> op=BACKUP_RESTORE, mode=BACKUP pkg=(com.itau.iti, 0)
io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:165)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:106)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$backup$1$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:356)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda2.run(Unknown Source:18)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

### Screenshots

![Screenshot_20230911-152713_App_Manager](https://github.com/MuntashirAkon/AppManager/assets/16189267/40956193-0286-4ef7-bdfa-1b3e708d44a8)

### Device info

- Device: Pixel 5
- OS Version: 11
- App Manager Version: 4 Alpha 1
- Mode: Root

**Comment by MuntashirAkon** [comment]
> `io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.`

As you can see, you haven't enabled backup for apps with KeyStore. See [relevant docs here](https://muntashirakon.github.io/AppManager/en/#backup-apps-with-android-keystore).

**Comment by Ahplla** [comment]
I noticed that, thank you. What do you think about adding a friendly message like "This app only allows backup with Keystore, would you like to enable this option?" and an action button that takes you to the backup options?

Greetings.

**Comment by MuntashirAkon** [comment]
> I noticed that, thank you. What do you think about adding a friendly message like "This app only allows backup with Keystore, would you like to enable this option?" and an action button that takes you to the backup options?

No. Because later, some users will complain that they cannot restore those backups. Apps with Android KeyStore aren't guaranteed to work after restoring which is why it's disabled, and it's necessary that they gain a certain understanding of the feature before enabling it. Enabling it with a message does not work as most users will just click “enable” without reading anything only to find that their backups cannot be restored as expected.
