### ISSUE TITLE
WakeLock under-locked

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1176]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager crashed while performing 1-click ops immediately after restarting the device. (1 time crash)

### To Reproduce

1. Restart the device
2. Immediately open AM > 1-Click Ops > Clear data from uninstall apps & Trim caches in all apps
3. See error

### Logs

```
java.lang.RuntimeException: WakeLock under-locked AppManager::1-click_ops
    at android.os.PowerManager$WakeLock.release(PowerManager.java:2899)
    at android.os.PowerManager$WakeLock.release(PowerManager.java:2861)
    at io.github.muntashirakon.AppManager.oneclickops.OneClickOpsActivity.clearData(OneClickOpsActivity.java:404)
    at io.github.muntashirakon.AppManager.oneclickops.OneClickOpsActivity.$r8$lambda$PAAA15TnXXKPI_Vc49jE5M68oeE(Unknown Source:0)
    at io.github.muntashirakon.AppManager.oneclickops.OneClickOpsActivity$$ExternalSyntheticLambda15.onChanged(Unknown Source:4)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

Device Info:
App version: 4.0.0-alpha01-DEBUG
App version code: 434
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed via 0bb56c3189798a48d67fa5e4d515dcf64050eddd
