### ISSUE TITLE
Backup/Restore can't restore apk

### ISSUE THREAD

**Issue by researchscum** [MuntashirAkon/AppManager#1182]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

tried to restore apk from a recently backed-up app after uninstalling the app without keep data and signature but fail with log error even if skip signature check ticked.

### To Reproduce

1. make an apk backup from backup/restore feature
2. uninstall the app without keep data and signature ticked
3. do a restore of that apk
4. fail

### Expected behavior

app installed from the backedup apk.

### Logs

====> op=BACKUP_RESTORE, mode=RESTORE pkg=(com.rise.automatic.autoclicker.clicker, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Failed to extract the apk file(s).
	at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:341)
	at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:201)
	at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:189)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$restoreBackups$3$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:394)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda0.run(Unknown Source:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: android.system.ErrnoException: chown failed: EPERM (Operation not permitted)
	at io.github.muntashirakon.AppManager.utils.TarUtils.extract(TarUtils.java:241)
	at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:339)
	... 9 more
Caused by: android.system.ErrnoException: chown failed: EPERM (Operation not permitted)
	at libcore.io.Linux.chown(Native Method)
	at libcore.io.ForwardingOs.chown(ForwardingOs.java:171)
	at libcore.io.BlockGuardOs.chown(BlockGuardOs.java:90)
	at android.system.Os.chown(Os.java:124)
	at io.github.muntashirakon.io.FileSystemService.setUidGid(FileSystemService.java:230)
	at io.github.muntashirakon.io.IFileSystemService$Stub.onTransact(IFileSystemService.java:524)
	at android.os.Binder.execTransactInternal(Binder.java:1290)
	at android.os.Binder.execTransact(Binder.java:1249)

### Device info

- Device: POCO F3
- OS Version: MIUI 14 Android 13
- App Manager Version: AppManager_v4.0.0-alpha01-DEBUG#2574 (never tried in version before this)
- Mode: ADB

### Additional context

if the app installed and i do restore data and the other option except apk it succeed

**Comment by MuntashirAkon** [comment]
Should be fixed by b5eb868e77f7bbd7a614c3aa93b98ea6229b50d1
