### ISSUE TITLE
save apk error x-invalid-mime-type

### ISSUE THREAD

**Issue by researchscum** [MuntashirAkon/AppManager#1197]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

tried to save apk mobile legengs bang bang it give error.

### To Reproduce

1. opem am debug 2589
2. search for mobile legend, if not found you need to install it.
3. click the icon
4. click more in the option that poped
5. click save apk
6. it will show couldn't backup in notification which can be clicked and to view logs.

### Expected behavior

apk saved

### Screenshots

![1695346510184](https://github.com/MuntashirAkon/AppManager/assets/97543175/cdc7fe44-5247-444e-b7bf-b0154bc23549)

### Logs

====> op=BACKUP_APK, pkg=(com.mobile.legends, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Mobile Legends: Bang Bang_1.8.20.8941.apks with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:103)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

### Device info

- Device: POCO F3
- OS Version: MIUI 14 Android 13
- App Manager Version: am_debug_4.0.0-alpha02-debug#2588
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Only this particular app?

**Comment by researchscum** [comment]
not sure but tachiyomi extension also fail it use the same "﹕" for the two dot thing
![Screenshot_2023-09-22-19-32-31-626_io github muntashirakon AppManager debug](https://github.com/MuntashirAkon/AppManager/assets/97543175/5cdfc82b-40aa-4361-9d9f-4625cc5b84ed)

<details> 
  <summary>the View Logs after clicking that floating notification </summary>
   ====> op=BACKUP_APK, pkg=(eu.kanade.tachiyomi.extension.en.truemanga, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Tachiyomi: TrueManga_1.4.13.apk with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:107)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
====> op=BACKUP_APK, pkg=(eu.kanade.tachiyomi.extension.en.toonitube, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Tachiyomi: TooniTube_1.4.13.apk with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:107)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
====> op=BACKUP_APK, pkg=(eu.kanade.tachiyomi.extension.en.suryascans, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Tachiyomi: Surya Scans_1.4.26.apk with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:107)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
====> op=BACKUP_APK, pkg=(eu.kanade.tachiyomi.extension.en.summanga, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Tachiyomi: Summanga_1.4.31.apk with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:107)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
====> op=BACKUP_APK, pkg=(eu.kanade.tachiyomi.extension.id.sektedoujin, 0)
java.io.IOException: Could not create file:///storage/emulated/0/AppManager/apks/Tachiyomi: Sekte Doujin_1.4.30.apk with type application/x-invalid-mime-type
	at io.github.muntashirakon.io.Path.createFileAsDirectChild(Path.java:1727)
	at io.github.muntashirakon.io.Path.createNewFile(Path.java:437)
	at io.github.muntashirakon.AppManager.apk.ApkUtils.backupApk(ApkUtils.java:107)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opBackupApk(BatchOpsManager.java:314)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:244)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:227)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:167)
	at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

</details>

**Comment by MuntashirAkon** [comment]
FAT* partition? I'll add necessary sanitisation for FAT/NTFS partitions.

**Comment by MuntashirAkon** [comment]
Fixed via a94eed6cdc0077604537adca90effcd653951818
