### ISSUE TITLE
Code editor crashed and failed to open the file

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1202]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1st my system crashed due to some other reason then followed by AM code editor crash when opened from device recents. I was editing a file using AM code editor.

### Logs

```
java.lang.IllegalStateException: Fragment CodeEditorFragment{f9a1853} (4b0e8958-7353-420f-b5ff-5d6f555ae17b) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
    at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
    at io.github.muntashirakon.AppManager.editor.CodeEditorFragment.updateSearchResult(CodeEditorFragment.java:675)
    at io.github.muntashirakon.AppManager.editor.CodeEditorFragment.lambda$onViewCreated$4$io-github-muntashirakon-AppManager-editor-CodeEditorFragment(CodeEditorFragment.java:305)
    at io.github.muntashirakon.AppManager.editor.CodeEditorFragment$$ExternalSyntheticLambda10.onReceive(Unknown Source:4)
    at io.github.rosemoe.sora.event.EventManager.dispatchEvent(EventManager.java:226)
    at io.github.rosemoe.sora.widget.CodeEditor.dispatchEvent(CodeEditor.java:3725)
    at io.github.rosemoe.sora.widget.EditorSearcher$SearchRunnable.lambda$run$0$io-github-rosemoe-sora-widget-EditorSearcher$SearchRunnable(EditorSearcher.java:466)
    at io.github.rosemoe.sora.widget.EditorSearcher$SearchRunnable$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at io.github.rosemoe.sora.widget.CodeEditor.lambda$postInLifecycle$0$io-github-rosemoe-sora-widget-CodeEditor(CodeEditor.java:4505)
    at io.github.rosemoe.sora.widget.CodeEditor$$ExternalSyntheticLambda6.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 4.0.0-alpha02
App version code: 435
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 409818f0dd98317ff25d08a066c5b242c4452628
