### ISSUE TITLE
Click on any app , make appmanager crash

### ISSUE THREAD

**Issue by islam2hamy** [MuntashirAkon/AppManager#1203]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Just click on any app in the list

### To Reproduce

Just click on any app in the list

### Logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8395)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8538)
   at android.app.Activity.performCreate(Activity.java:8502)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:211)
   at android.os.Looper.loop(Looper.java:300)
   at android.app.ActivityThread.main(ActivityThread.java:8395)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8538)
   at android.app.Activity.performCreate(Activity.java:8502)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:211)
   at android.os.Looper.loop(Looper.java:300)
   at android.app.ActivityThread.main(ActivityThread.java:8395)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
 Caused by: java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
   at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
   at android.os.Parcel.createException(Parcel.java:2995)
   at android.os.Parcel.readException(Parcel.java:2978)
   at android.os.Parcel.readException(Parcel.java:2920)
   at android.permission.IPermissionManager$Stub$Proxy.grantRuntimePermission(IPermissionManager.java:931)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:333)
   at io.github.muntashirakon.AppManager.compat.AppOpsManagerCompat.<init>(AppOpsManagerCompat.java:629)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:668)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8538)
   at android.app.Activity.performCreate(Activity.java:8502)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:211)
   at android.os.Looper.loop(Looper.java:300)
   at android.app.ActivityThread.main(ActivityThread.java:8395)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

Device Info:
App version: 3.1.2
App version code: 425
Android build version: V14.0.12.0.TMTMIXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.221114.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: tapas
Device model: 23021RAAEG
Device product name: tapas_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ar-EG
In-App Language: auto
Mode: auto
Inferred Mode: ADB

### Device info

Device Info:
App version: 3.1.2
App version code: 425
Android build version: V14.0.12.0.TMTMIXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.221114.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: tapas
Device model: 23021RAAEG
Device product name: tapas_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ar-EG
In-App Language: auto
Mode: auto
Inferred Mode: ADB

**Comment by MuntashirAkon** [comment]
It appears you have an incomplete ADB setup. Follow the official guide: https://muntashirakon.github.io/AppManager/en/#xiaomi-miui
