### ISSUE TITLE
Component block crash

### ISSUE THREAD

**Issue by HarriBuh** [MuntashirAkon/AppManager#1204]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App crashes sometimes while blocking random components of an app

### To Reproduce

1. Open AppManager
2. Choose an app to edit
3. Enter one of the tabs to block specific components (e.g. undetected trackers)
4. Try to block one or more components
5. Recognise the app crashing

### Expected behavior

No crash

### Logs
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object io.github.muntashirakon.AppManager.details.struct.AppDetailsItem.vanillaItem' on a null object reference in method 'void io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.getServicesView(android.content.Context, io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter$ViewHolder, int)'
	at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.getServicesView(AppDetailsComponentsFragment.java:551)
	at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsComponentsFragment.java:374)
	at io.github.muntashirakon.AppManager.details.AppDetailsComponentsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsComponentsFragment.java:269)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4118)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3459)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Device info

[Device Brand]: google
[Device Model]: Pixel 7
[Android Version]: 13
[Android API Level]: 33
[Process ID]: 11567
[CPU ABI]: arm64-v8a
[Package Name]: io.github.muntashirakon.AppManager
[Version Name]: 3.1.2
[Version Code]: 425
[Error Type]: JVM

### Additional context

_No response_

**Comment by MuntashirAkon** [comment]
I wasn't active on FOSS development since October. Consider switching to the unstable branch if you need this fix ASAP.

**Comment by MuntashirAkon** [comment]
Fixed?

**Comment by MuntashirAkon** [comment]
I see. Thanks. The fix will be released very soon, probably, in the next week.
