### ISSUE TITLE
Log Viewer crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1208]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Log viewer crashed while long click an item > select it from context menu.
1time crash.

### Logs

```
java.lang.IndexOutOfBoundsException: Index: 10151, Size: 10019
    at java.util.ArrayList.get(ArrayList.java:437)
    at io.github.muntashirakon.AppManager.logcat.LogViewerRecyclerAdapter.getItem(LogViewerRecyclerAdapter.java:251)
    at io.github.muntashirakon.AppManager.logcat.LogViewerRecyclerAdapter.isSelected(LogViewerRecyclerAdapter.java:298)
    at io.github.muntashirakon.widget.MultiSelectionView$Adapter.toggleSelection(MultiSelectionView.java:509)
    at io.github.muntashirakon.AppManager.logcat.LogViewerRecyclerAdapter.lambda$onBindViewHolder$3$io-github-muntashirakon-AppManager-logcat-LogViewerRecyclerAdapter(LogViewerRecyclerAdapter.java:416)
    at io.github.muntashirakon.AppManager.logcat.LogViewerRecyclerAdapter$$ExternalSyntheticLambda4.onMenuItemClick(Unknown Source:4)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3216)
    at android.widget.AbsListView$3.run(AbsListView.java:4192)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 4.0.0-alpha02-DEBUG
App version code: 435
Android build version: 56720d-f37a9
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-10
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 7ada8a7f6ea98d8b268cb665864d8c8f74a57d43
