### ISSUE TITLE
App manager crashing when tapping on some apps that might not be installed.

### ISSUE THREAD

**Issue by cozykitten** [MuntashirAkon/AppManager#1215]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I lost some apps through the error of another app that somewhat uninstalled them but not really?
The apps were gone, but when I reinstalled one of them through the apk file that I still had it said "Do you want to install an update for an existing app" indicating that it was still somewhat there.

Long story short, I went to AppManager to restore the backups I had made and after clicking some of the apps to see if they were there or not it crashed and gave me log below.

### Logs

java.lang.RuntimeException: java.lang.IllegalArgumentException: ApkFile not found for key 281954527
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfo$1(AppInfoViewModel.java:330)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8177)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 Caused by: java.lang.IllegalArgumentException: ApkFile not found for key 281954527
   at io.github.muntashirakon.AppManager.apk.ApkFile.getInstance(ApkFile.java:105)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadAppInfo(AppInfoViewModel.java:261)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1617)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.$r8$lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda63.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
   at java.lang.Thread.run(Thread.java:1012)

Device Info:
App version: 3.1.3
App version code: 426
Android build version: 10754064
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231005.007
Device brand: google
Device manufacturer: Google
Device name: bluejay
Device model: Pixel 6a
Device product name: bluejay
Device hardware name: bluejay
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: Pixel 6a
- OS Version: 14 (October)
- App Manager Version: 3.1.3
- Mode: Root

**Comment by MuntashirAkon** [comment]
This was one of the major issues in v3.x.x that couldn't be fixed without some major overhauls. v4.x.x lineups will fix the issues.
