### ISSUE TITLE
No backups for Work profile apps

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1220]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

As mentioned in the title backups not working as expected
It creates empty folder e.g. - `/storage/emulated/0/AppManager/com.dede.android_eggs/0`

### To Reproduce

1. Enable "Show users in installer
2. Install an app for **Work profile only**
3. Backup the app

### Expected behavior

[Currently you've to enable "Custom users" checkbox from "Settings > Backup/Restore > Backup options" or directly from Backup/Restore bottom sheet and select correct user to make it work.]
By default it should backup the app without any additional configuration.

### Logs

- Default mode i.e. Custom user disabled
  Simply backup an work profile app from "App info", AM already show `Island (12)` so the assumption is it should backup for the same profile. (❌)

```
====> op=BACKUP_RESTORE, mode=1 pkg=(com.dede.android_eggs, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Failed to setup metadata.
	at io.github.muntashirakon.AppManager.backup.BackupOp.<init>(BackupOp.java:126)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:97)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:331)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.content.pm.PackageManager$NameNotFoundException: Could not retrieve info for package com.dede.android_eggs with flags 0x8000080 for user 0
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:171)
	at io.github.muntashirakon.AppManager.backup.BackupOp.<init>(BackupOp.java:118)
	... 8 more

```
---
- Enable Custom user from settings
 App installed on `Owner (0)` but I backup for `Island (12)`. I know it's my fault but it shouldn't show me other user option either. (❓)

<details><summary>Logs</summary>
<p>

```
====> op=BACKUP_RESTORE, mode=1 pkg=(io.github.muntashirakon.captiveportalcontroller, 12)
io.github.muntashirakon.AppManager.backup.BackupException: Failed to setup metadata.
	at io.github.muntashirakon.AppManager.backup.BackupOp.<init>(BackupOp.java:126)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:97)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:331)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.content.pm.PackageManager$NameNotFoundException: Could not retrieve info for package io.github.muntashirakon.captiveportalcontroller with flags 0x8000080 for user 12
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:171)
	at io.github.muntashirakon.AppManager.backup.BackupOp.<init>(BackupOp.java:118)
	... 8 more

```

</p>
</details> 

### Device info

- Device: moto g71 5G
- OS Version: 12
- App Manager Version: 3.1.2
- Mode: Root

### Additional context

Suggestion
1. Backup using "Batch operations" from main page:
 a) If "Custom user" checkbox disabled (default): Backup `Owner (0)` apps ignoring work profile apps if selected in that batch. Ignore backup, if you pick work profile apps _only_ because `Owner (0)` is the default behavior. (❓). Make other user backups possible **iff** [1.(b)]
 b) If "Custom user" checkbox enabled: Suppose you picked multiple apps from both main+work profile but from "select user" window you picked only `Owner (0)` then it should backup apps installed on that specific profile only ignoring apps installed on work profile. (❓)
 
2. Backup from "App info" page: We already show "Select user" option before you enter to App info page, so
 a) "Custom user" checkbox option should be removed if app installed on _one profile only_ show **iff** installed on both profile [2.(b)] (❌)
 b) If installed on both profile: Backup for the correct profile instead of `Owner (0)` as always. (❌)

Note : Ignoring means no backups, no empty directories creation. Backup option (_Custom user_) preset from AM settings applicable to [1.(b) & 2.(b)] only.

**Comment by MuntashirAkon** [comment]
I think your suggestions can be modified a little bit:

Instead of only “App Info” tab, the options can be applied for any single selection. For example, if the user selects one work profile app from the main page and want to take backups, the custom backup options should be disabled since it's only installed for the work profile. If the app is installed in both profiles, however, the “batch ops” options will be applied like the usual.

This also makes the implementation a bit easier since it's no longer bound to batch ops or app info tab, it becomes global.

**Comment by MuntashirAkon** [comment]
I've tried to implement this here: c3968ac600a7f9bc818ac22080a195eef5320a1b

Not sure if I've got everything correctly. As I have implemented all the logic, it's difficult for me to find fault with it!
