### ISSUE TITLE
App manager not showing running apps nor showing logs. 

### ISSUE THREAD

**Issue by vordx** [MuntashirAkon/AppManager#1221]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App manager not loading logs nor showing running apps after force closing any app. 

### To Reproduce

-APP manager, labs, logs, nothing shows up (infinite loading)

-App manager, running apps, force close any app or change anything, the list disappears.

https://github.com/MuntashirAkon/AppManager/assets/39927714/a4b6e082-4417-43cc-942e-f738d083abe1

### Expected behavior

Logs loading and running apps showing the full list. 

### Screenshots

![Screenshot_20231013_191824_App Manager](https://github.com/MuntashirAkon/AppManager/assets/39927714/f1439a66-622d-4768-9b83-8e287c6d14bf)
![Screenshot_20231013_192313_App Manager](https://github.com/MuntashirAkon/AppManager/assets/39927714/a0e5dfeb-4be0-44db-a721-a01b5e9c3f5e)

### Logs

[app manager.zip](https://github.com/MuntashirAkon/AppManager/files/12895558/app.manager.zip)

### Device info

- Device: Galaxy s22U S908E
- OS Version: Android 14, oneui 6.
- App Manager Version: 4.0.0 Alpha 02 (435)
- Mode: ADB

### Additional context

How to get the debuggable apk?

**Comment by vordx** [comment]
https://github.com/MuntashirAkon/AppManager/assets/39927714/a4b6e082-4417-43cc-942e-f738d083abe1

**Comment by MuntashirAkon** [comment]
> How to get the debuggable apk?

https://muntashirakon.github.io/AppManager/en/#subsec:binary-distribution-sources

**Comment by MuntashirAkon** [comment]
I've found the following from your logs:

**For log viewer**
```
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: IOException when writing to out
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: java.io.InterruptedIOException: read interrupted
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at libcore.io.Linux.readBytes(Native Method)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at libcore.io.Linux.read(Linux.java:190)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at libcore.io.IoBridge.read(IoBridge.java:604)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at java.io.FileInputStream.read(FileInputStream.java:328)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:277)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:338)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
13.10 19:19:18.792 shell 2356 5436 com.android.shell E/FD: 	at io.github.muntashirakon.AppManager.ipc.RemoteProcessImpl$InputTransferThread.run(RemoteProcessImpl.java:219)
```

**For running apps**
```
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: FATAL EXCEPTION: binder:2356_9
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: PID: 2356
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: java.lang.ExceptionInInitializerError
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.utils.ExUtils.exceptionAsNull(ExUtils.java:79)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.io.Path.getContentAsString(Path.java:1640)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.proc.ProcFs.getStringOrNull(ProcFs.java:324)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.proc.ProcFs.getStat(ProcFs.java:219)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.ipc.ps.Ps.loadProcesses(Ps.java:70)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.getRunningProcesses(AMService.java:51)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.IAMService$Stub.onTransact(IAMService.java:102)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:76)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1380)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1311)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: Caused by: java.lang.SecurityException: callingPackage does not match UID
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3053)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3036)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.storage.IStorageManager$Stub$Proxy.getVolumeList(IStorageManager.java:2180)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:1490)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:184)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Environment$UserEnvironment.buildExternalStorageAppCacheDirs(Environment.java:232)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Environment.buildExternalStorageAppCacheDirs(Environment.java:1167)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:959)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:146)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.utils.FileUtils.getCachePath(FileUtils.java:137)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.logs.Logger.getLoggingDirectory(Logger.java:22)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at io.github.muntashirakon.AppManager.logs.Log.<clinit>(Log.java:40)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	... 10 more
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at com.android.server.StorageManagerService.getVolumeList(StorageManagerService.java:4271)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.storage.IStorageManager$Stub.onTransact(IStorageManager.java:1076)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1375)
13.10 19:19:29.690 shell 2356 2389 com.android.shell E/AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1311)
```

**Comment by MuntashirAkon** [comment]
> -App manager, running apps, force close any app or change anything, the list disappears.

Should be fixed by 544d92746f5166e822e3564b0115f467126417b7

**Comment by MuntashirAkon** [comment]
You still need to send me some logs regarding log viewer. The exception above was thrown because you exited the log viewer page.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.
