### ISSUE TITLE
Crash report on some random interaction around AppManager and with landscape/portrait switch

### ISSUE THREAD

**Issue by Porkepix** [MuntashirAkon/AppManager#1265]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Can't tell the exact circumstances but I was interacting around log viewer, saving them and so on in AppManager, while there was some landscape/portrait switching while plugging the phone, and some crash happened with the system offering to send a crash report you'll see below.

### Expected behavior

No crash.

### Logs

```
java.lang.RuntimeException: Unable to destroy activity {io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.logcat.LogViewerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.removeOnScrollListener(androidx.recyclerview.widget.RecyclerView$OnScrollListener)' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4453)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4471)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4745)
    at android.app.ActivityThread.-wrap18(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1604)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:251)
    at android.app.ActivityThread.main(ActivityThread.java:6572)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.removeOnScrollListener(androidx.recyclerview.widget.RecyclerView$OnScrollListener)' on a null object reference
   at io.github.muntashirakon.AppManager.logcat.AbsLogViewerFragment.onDestroy(AbsLogViewerFragment.java:146)
   at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3219)
   at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
   at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:120)
   at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
   at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
   at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
   at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
   at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
   at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
   at io.github.muntashirakon.AppManager.logcat.LogViewerActivity.onDestroy(LogViewerActivity.java:323)
   at android.app.Activity.performDestroy(Activity.java:7177)
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4440)
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4471)
   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4745)
   at android.app.ActivityThread.-wrap18(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1604)
   at android.os.Handler.dispatchMessage(Handler.java:105)
   at android.os.Looper.loop(Looper.java:251)
   at android.app.ActivityThread.main(ActivityThread.java:6572)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Device Info:
App version: 3.1.4
App version code: 427
Android build version: 1629831864
Android release version: 8.0.0
Android SDK version: 26
Android build ID: 41.3.A.2.192
Device brand: Sony
Device manufacturer: Sony
Device name: F8331
Device model: F8331
Device product name: F8331
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: no_root
```

### Device info

- Device: Xperia XZ
- OS Version: Android Oreo (8.0)
- App Manager Version: 3.1.4
- Mode: NonRoot

**Comment by MuntashirAkon** [comment]
Fixed in ea065d5b31ae01012f6d7246c90b014d54e911f3
