### ISSUE TITLE
Mode of operation being.... difficult

### ISSUE THREAD

**Issue by CamsShaft** [MuntashirAkon/AppManager#1285]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Installed this great piece of work on my S10 and S22 (both snapdragon) and it works excellent on the S10, no issues at all. The S22 on the otherhand is having some extreme issues with ADB and therefore is not functioning at all. I can't even take a look at the logs to see what's up. I have it in split screen and connected to wireless debugging with it saying "inferred mode: ADB." When I go out of that screen to check out my apps, none of them will open saying "not installed" or "could not fetch package information" and then when I go back to settings, inferred mode is now back to no root. If I go to auto in mode of operation it still defaults to no root, which I suppose is to be expected?

### To Reproduce

1. Set up App Manager.
2. Try wireless ADB mode.
3. Connects to ADB.
4. None of the usual ADB features are functioning.

### Expected behavior

I would ecpect it to be working as it is on my other samsung phone: all app-ops, permissions and other features responding normally.

### Screenshots

| | |
| --- | --- |
| ![Screenshot_20240129_135006_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/1205429c-14a1-4936-95c6-a7a902872f5a) | ![Screenshot_20240129_135023_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/60c1f76d-db7c-4b60-ab98-eaa798512e90) |
| ![Screenshot_20240129_135051_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/4a2a2a79-990d-4afe-ad0f-31ee0a24a01c) | ![Screenshot_20240129_135140_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/6a35fa70-e71e-47db-8d94-e4b79b11917d)|
| ![Screenshot_20240129_134954_Settings](https://github.com/MuntashirAkon/AppManager/assets/141678661/48e514b7-25b2-433b-b46d-e221023261f6) | |

### Device info

- Device: Samsung Galaxy S22 SM-S901W
- OS Version: Android 14
- App Manager Version: 3.1.4 
- Mode: ADB

### Additional context

My S10 is running Android 12 and is pretty close to the same phone as my S22, just two updates behind. I'm at a bit of a loss on how to fix this on my own so I've come here, hopefully it's something really dumb and simple. Also shizuku is on both of my phones and wasn't running, but I did have it running on my S10 and still had no issues so that shouldn't be the problem. I'm having an issues with my logs too so hopefully can get some info later too.

**Comment by MuntashirAkon** [comment]
Install a debug build and try again. Logs should be available at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/caches/am.log`

**Comment by CamsShaft** [comment]
Waited for the newest update and something new happened now. It's still pretty much the same as before and takes forever to even open too. My log is at the bottom. The whole thing just repeated itself.

![Screenshot_20240330_100525_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/bedb25c7-8888-492a-9709-89819ff8f44f)
![Screenshot_20240330_100012_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/28a7664f-6b34-4b26-87d7-7f615685dbc6)
![Screenshot_20240330_095944_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/8b277cce-241c-4f59-bcdf-5d509bf1dee3)
![Screenshot_20240330_095917_App Manager](https://github.com/MuntashirAkon/AppManager/assets/141678661/2aa7ad28-9231-45d2-8029-8b4cb89d13a4)

2024-03-30 09:49:53.198 W/ExUtils: (Suppressed error)
java.lang.SecurityException: getPermissionFlags requires android.permission.GRANT_RUNTIME_PERMISSIONS or android.permission.REVOKE_RUNTIME_PERMISSIONS or android.permission.GET_RUNTIME_PERMISSIONS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.permission.IPermissionManager$Stub$Proxy.getPermissionFlags(IPermissionManager.java:790)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:280)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$getPermissionItem$30$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:1499)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda31.run(Unknown Source:6)
	at io.github.muntashirakon.AppManager.utils.ExUtils.exceptionAsNull(ExUtils.java:44)
	at io.github.muntashirakon.AppManager.utils.ExUtils.requireNonNullElse(ExUtils.java:53)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPermissionItem(AppDetailsViewModel.java:1499)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1460)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$24$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:911)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda40.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-03-30 09:49:53.204 W/ExUtils: (Suppressed error)
java.lang.SecurityException: getPermissionFlags requires android.permission.GRANT_RUNTIME_PERMISSIONS or android.permission.REVOKE_RUNTIME_PERMISSIONS or android.permission.GET_RUNTIME_PERMISSIONS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.permission.IPermissionManager$Stub$Proxy.getPermissionFlags(IPermissionManager.java:790)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:280)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$getPermissionItem$30$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:1499)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda31.run(Unknown Source:6)
	at io.github.muntashirakon.AppManager.utils.ExUtils.exceptionAsNull(ExUtils.java:44)
	at io.github.muntashirakon.AppManager.utils.ExUtils.requireNonNullElse(ExUtils.java:53)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPermissionItem(AppDetailsViewModel.java:1499)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1460)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$24$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:911)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda40.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by MuntashirAkon** [comment]
Your reports and logs are useless since you haven't followed the instructions I posted in my last comment.

**Comment by MuntashirAkon** [comment]
Closed due to https://github.com/MuntashirAkon/AppManager/issues/1337#issuecomment-2042874494
