### ISSUE TITLE
null error on interceptor 

### ISSUE THREAD

**Issue by fcaronte** [MuntashirAkon/AppManager#1292]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

i'm try to install apk using interceptor and adding extra intent, app seem to be installed but always get a "null" popup and with logcat i see this error but i can't understand if is okay or something go wrong:

```
2024-02-13 00:11:49.050 27396-20804 JavaBinder      io....shirakon.AppManager  W  ibinderForJavaObject: 0x77ae126f20 is not a Binder object
2024-02-13 00:11:49.050 27396-20804 Parcel          io....shirakon.AppManager  E  Native binder in markForBinder is null for non-null jobject
2024-02-13 00:11:49.052 27396-20804 JavaBinder      io....shirakon.AppManager  W  ibinderForJavaObject: 0x77ae126f20 is not a Binder object
2024-02-13 00:11:49.052 27396-20804 Parcel          io....shirakon.AppManager  E  Native binder in markForBinder is null for non-null jobject
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  java.io.FileNotFoundException: Cannot find file:///data/system/users/0/settings_ssaid.xml
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at io.github.muntashirakon.io.Path.findFile(Path.java:605)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at io.github.muntashirakon.AppManager.ssaid.SsaidSettings.<init>(SsaidSettings.java:50)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at io.github.muntashirakon.AppManager.db.utils.AppDb.updateVariableData(AppDb.java:367)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at io.github.muntashirakon.AppManager.db.utils.AppDb.updateApplications(AppDb.java:159)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at
                                                                                  io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForPackages(MainViewModel.java:562)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at
                                                                                  io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForUid(MainViewModel.java:534)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at io.github.muntashirakon.AppManager.main.MainViewModel.access$000(MainViewModel.java:66)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at
                                                                                  io.github.muntashirakon.AppManager.main.MainViewModel$PackageIntentReceiver.onPackageChanged(MainViewModel.java:731)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at
                                                                                  io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:126)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at android.os.Looper.loopOnce(Looper.java:230)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at android.os.Looper.loop(Looper.java:319)
2024-02-13 00:11:49.058 27396-20804 System.err      io....shirakon.AppManager  W  	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-13 00:11:49.058 27396-20804 JavaBinder      io....shirakon.AppManager  W  ibinderForJavaObject: 0x77ae127170 is not a Binder object
2024-02-13 00:11:49.058 27396-20804 Parcel          io....shirakon.AppManager  E  Native binder in markForBinder is null for non-null jobject
2024-02-13 00:11:49.087 27396-27407 System          io....shirakon.AppManager  W  A resource failed to call close. 
```

![Screenshot_20240213_001248_Package installer](https://github.com/MuntashirAkon/AppManager/assets/26366403/4e7aaa88-8bcb-42ad-85f8-8e755031900b)

### Device info

- Device: S24Ultra
- OS Version: A14
- App Manager Version: 3.1.4
- Mode: Root/ADB/NonRoot Wireless Debug ADB

**Comment by fcaronte** [comment]
Pratically i'm try to fix kinginstaller problem on android 14 where stop to do his job

` Intent intent = new Intent(Intent.ACTION_INSTALL_PACKAGE);
            Uri fileUri;
            fileUri = FileProvider.getUriForFile(getApplicationContext(), getPackageName() + ".provider", myFile);
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK + Intent.FLAG_GRANT_READ_URI_PERMISSION);
            intent.setData(fileUri);
            intent.putExtra(Intent.EXTRA_NOT_UNKNOWN_SOURCE, true);
            intent.putExtra(Intent.EXTRA_INSTALLER_PACKAGE_NAME, "com.android.vending");
            et.setText("");
            TextView tv = findViewById(R.id.textViewError);
            tv.setText("");
            startActivity(intent);`
[https://github.com/fcaronte/KingInstaller/blob/master/app/src/main/java/com/example/kinginstaller/MainActivity.java]

**Comment by MuntashirAkon** [comment]
When you open an activity from the interceptor, it also watches out for a result to be returned by the activity. If it does not return any result, `null` is returned. It's not a bug or anything. See official guide for more info: https://developer.android.com/training/basics/intents/result
