### ISSUE TITLE
BootLoop when I block a thirdparty app to startup 

### ISSUE THREAD

**Issue by weisuofayubb** [MuntashirAkon/AppManager#1304]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

```
03-06 22:21:51.722  9431  9431 E Zygote  : System zygote died with fatal exception
03-06 22:21:51.722  9431  9431 E Zygote  : java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_UNLOCKED flg=0x50000010 (has extras) } in com.android.server.content.SyncManager$5@110da10
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.os.Handler.handleCallback(Handler.java:958)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.os.Handler.dispatchMessage(Handler.java:99)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.os.Looper.loopOnce(Looper.java:205)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.os.Looper.loop(Looper.java:294)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:995)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:681)
03-06 22:21:51.722  9431  9431 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)
03-06 22:21:51.722  9431  9431 E Zygote  : Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=android.content.SyncAdapter cmp=com.snda.wifilocating/com.lantern.daemon.farmore.syncnew.AccountSyncService (has extras) }
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2133)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:2041)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager.sendOnUnsyncableAccount(SyncManager.java:2907)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager.scheduleSync(SyncManager.java:1190)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager.scheduleSync(SyncManager.java:1008)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager.onUserUnlocked(SyncManager.java:1941)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager.-$$Nest$monUserUnlocked(SyncManager.java:0)
03-06 22:21:51.722  9431  9431 E Zygote  :      at com.android.server.content.SyncManager$5.onReceive(SyncManager.java:433)
03-06 22:21:51.722  9431  9431 E Zygote  :      at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
03-06 22:21:51.722  9431  9431 E Zygote  :      ... 11 more
03-06 22:21:51.722  9431  9431 D AndroidRuntime: Shutting down VM
03-06 22:21:51.722  9431  9431 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-06 22:21:51.722  9431  9431 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_UNLOCKED flg=0x50000010 (has extras) } in com.android.server.content.SyncManager$5@110da10
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:995)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:681)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)
03-06 22:21:51.722  9431  9431 E AndroidRuntime: Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=android.content.SyncAdapter cmp=com.snda.wifilocating/com.lantern.daemon.farmore.syncnew.AccountSyncService (has extras) }
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2133)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:2041)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager.sendOnUnsyncableAccount(SyncManager.java:2907)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager.scheduleSync(SyncManager.java:1190)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager.scheduleSync(SyncManager.java:1008)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager.onUserUnlocked(SyncManager.java:1941)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager.-$$Nest$monUserUnlocked(SyncManager.java:0)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at com.android.server.content.SyncManager$5.onReceive(SyncManager.java:433)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
03-06 22:21:51.722  9431  9431 E AndroidRuntime:        ... 11 more
03-06 22:21:51.725  9431  9431 I DropBoxManagerService: add tag=system_server_crash isTagEnabled=true flags=0x2
03-06 22:21:51.725  9431  9684 I Process : Sending signal. PID: 9431 SIG: 9
```

### Device info

- Device:
- OS Version: crdroid 10
- App Manager Version: 4.0
- Mode: Root/ADB/NonRoot Root

### Additional context

Any idea?

**Comment by weisuofayubb** [comment]
Delete /data/system/ifw/com.snda.wifilocating.xml can restore to normal

**Comment by MuntashirAkon** [comment]
I don't think anything more could be done in App Manager's end. If it is reproducible in a more recent version of Android (Android 12 onwards), I suggest reporting this issue to [Google Issue Tracker](https://issuetracker.google.com/). The bootloop was caused by the framework's inability to deliver a broadcast intent to a certain component of the third-party app which should never happen. A component blocked via Intent Firewall should be ignored by the system.
