### ISSUE TITLE
AppManager crashes when importing from OAndBackup

### ISSUE THREAD

**Issue by xxxxme** [MuntashirAkon/AppManager#1307]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When attempting to import a backup created by oandbackup, App Manager crashes.

### To Reproduce

- Go to Settings > Backup/Restore > Import Backups
- Choose Import from OAndBackup
- Choose "no" and allow access to the directory the backup is in (I had copied it to a subdirectory of Downloads)
- AppManager restarts without importing and produces a crash notification.

### Expected behavior

Backup(s) are imported

### Logs

java.lang.UnsupportedOperationException
    at androidx.documentfile.provider.SingleDocumentFile.listFiles(SingleDocumentFile.java:115)
    at androidx.documentfile.provider.MediaDocumentFile.listFiles(MediaDocumentFile.java:21)
    at io.github.muntashirakon.io.Path.listFiles(Path.java:1343)
    at io.github.muntashirakon.io.Path.listFiles(Path.java:1361)
    at io.github.muntashirakon.AppManager.backup.convert.ConvertUtils.getRelevantImportFiles(ConvertUtils.java:62)
    at io.github.muntashirakon.AppManager.backup.convert.ConvertUtils.getRelevantImportFiles(ConvertUtils.java:40)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opImportBackups(BatchOpsManager.java:367)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:266)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:213)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:205)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:53)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 3.1.4
App version code: 427
Android build version: 29da1fa03e
Android release version: 13
Android SDK version: 33
Android build ID: lineage_barbet-userdebug 13 TQ3A.230901.001 29da1fa03e
Device brand: google
Device manufacturer: Google
Device name: barbet
Device model: Pixel 5a
Device product name: barbet
Device hardware name: barbet
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: Pixel 5a
- OS Version: LineageOS 20 (A13)
- App Manager Version: 3.1.4
- Mode: Root
- OAndBackup Version: 0.3.5

**Comment by MuntashirAkon** [comment]
c55862f1812cab467cd3fcce09b1498101e11c36
