### ISSUE TITLE
App won't open in One UI even after getting root permission. 

### ISSUE THREAD

**Issue by anurag565** [MuntashirAkon/AppManager#1312]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I dont know if its on my device or all, but it happens every time even if i flash new stock ROM from beginning. App just wont open even if i gave it magisk permission. Stuck on front page.

### Screenshots

![Screenshot_20240320_235108_App Manager](https://github.com/MuntashirAkon/AppManager/assets/143786347/b0122c6c-228b-40a1-9576-0ddebba8e0de)

### Device info

- Device: M13 5G
- OS Version:14
- App Manager Version:3.1.5
- Mode: Root

**Comment by yukkerike** [comment]
+1

**Comment by anurag565** [comment]
> You need to provide some logs from the debug releases which you can find in the Actions page. Be sure to use AppManager-v3.1.x branch.

How to? Please tell the steps. I really want the app to get fixed asap.

**Comment by HanabishiRecca** [comment]
Are you sure this is not #1311?

**Comment by anurag565** [comment]
> Are you sure this is not #1311?

Yes its different issue. I will provide log soon.... my exams are going on right now.

**Comment by Kovinda** [comment]
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager, PID: 16019
java.lang.IllegalStateException: External directory unavailable.
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161)
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
	at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
	at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
	at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.io.FileNotFoundException: No available shared storage found.
	at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210)
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159)
	... 14 more

**Comment by anurag565** [comment]
> FATAL EXCEPTION: main Process: io.github.muntashirakon.AppManager, PID: 16019 java.lang.IllegalStateException: External directory unavailable. at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285) at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8246) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) Caused by: java.io.FileNotFoundException: No available shared storage found. at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159) ... 14 more

Did u found the log?

**Comment by Kovinda** [comment]
> > FATAL EXCEPTION: main Process: io.github.muntashirakon.AppManager, PID: 16019 java.lang.IllegalStateException: External directory unavailable. at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285) at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8246) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) Caused by: java.io.FileNotFoundException: No available shared storage found. at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159) ... 14 more
> 
> Did u found the log?

Yes, The same bug.

Device info
Device: A52s 5G
OS Version:14
App Manager Version:3.1.5
Mode: Root

**Comment by Kovinda** [comment]
time: 1712259669910
msg: java.io.FileNotFoundException: No available shared storage found.
stacktrace: java.lang.IllegalStateException: External directory unavailable.
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161)
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
	at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
	at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
	at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.io.FileNotFoundException: No available shared storage found.
	at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210)
	at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159)
	... 14 more
	
This is the log from the debug version 3.1.5-2656-DEBUG (428)

**Comment by anurag565** [comment]
> > > FATAL EXCEPTION: main Process: io.github.muntashirakon.AppManager, PID: 16019 java.lang.IllegalStateException: External directory unavailable. at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285) at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110) at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117) at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8246) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) Caused by: java.io.FileNotFoundException: No available shared storage found. at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210) at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159) ... 14 more
> > 
> > 
> > Did u found the log?
> 
> Yes, The same bug. But it is not from the debug version of the app
> 
> Device info Device: A52s 5G OS Version:14 App Manager Version:3.1.5 Mode: Root

Thanks...hope devs solve this

**Comment by MuntashirAkon** [comment]
> java.lang.IllegalStateException: External directory unavailable.

This issue is a duplicate of #948, unlikely the once that @anurag565 is facing.

**Comment by Kovinda** [comment]
> > java.lang.IllegalStateException: External directory unavailable.
> 
> This issue is a duplicate of #948, unlikely the one that @anurag565 is facing.

Creating the folder and giving permissions fixed everything

**Comment by MuntashirAkon** [comment]
@anurag565: Any updates?

**Comment by anurag565** [comment]
> @anurag565: Any updates?

Even in latest updates, it still persists same issue.
