### ISSUE TITLE
 Crash on WebView reinstall

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1326]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashes when reinstalling System WebView

### To Reproduce

1. Uninstall Android System WebView (com.android.webview)
2. Reinstall it > AM crashes
3. Open AM again > check if WebView installed > yes it's installed

### Logs

```
java.lang.NullPointerException
    at j$.util.Objects.requireNonNull(Objects.java:219)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getInstance(ComponentsBlocker.java:131)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getMutableInstance(ComponentsBlocker.java:110)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentUtils.blockTrackingComponents(ComponentUtils.java:78)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService$1.onFinishedInstall(PackageInstallerService.java:144)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.installCompleted(PackageInstallerCompat.java:1021)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.installExisting(PackageInstallerCompat.java:925)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:169)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:73)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Device info

App version: **4.0.0-alpha02-DEBUG** (RUN#2644)
App version code: 435
Android build version: eng.chef.20200713.073313
Android release version: 9
Android SDK version: 28
Android build ID: lineage_TB8704-userdebug 9 PQ3A.190801.002 eng.chef.20200713.073313 test-keys
Device brand: Lenovo
Device manufacturer: Lenovo
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: lineage_TB8704
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 7e63188bc6477c21bebfa5a0251d8a0305f49964
