### ISSUE TITLE
java.lang.IllegalStateException: External directory unavailable.

### ISSUE THREAD

**Issue by brian6932** [MuntashirAkon/AppManager#1333]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I updated my phone from Android 13 to 14, and now opening App Manager instantly crashes with the following stack.
Seems like the latest actions build doesn't exhibit this the same way, instead after a few launches, it freezes on initialization, and then eventually says that it can't establish root method.

### To Reproduce

1. Grant the app root in KSU
1. Open app
1. Crashes

### Expected behavior

Should open

### Logs

```
java.lang.IllegalStateException: External directory unavailable.
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161)
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
    at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 Caused by: java.io.FileNotFoundException: No available shared storage found.
   at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
   at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
   at android.os.Handler.handleCallback(Handler.java:958)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loopOnce(Looper.java:205)
   at android.os.Looper.loop(Looper.java:294)
   at android.app.ActivityThread.main(ActivityThread.java:8248)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Device Info:
App version: 3.1.5
App version code: 428
Android build version: 278
Android release version: 14
Android SDK version: 34
Android build ID: UQ1A.240205.004.B1 release-keys
Device brand: asus
Device manufacturer: asus
Device name: AI2202
Device model: ASUS_AI2202
Device product name: WW_AI2202
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: root
```

### Device info

- Device: Zenfone 9
- OS Version: omni-14-202403121645-zenfone9-GAPPS
- App Manager Version: 3.1.5
- Mode: Root (KSU)

### Additional context

Only happens with Root enabled, likely the same cause as #948, although I didn't have such an issue on Android 13.

**Comment by brian6932** [comment]
Fixed by a reinstall

**Comment by brian6932** [comment]
This was actually due to a Kernel incompatibility with my ROM 😅

**Comment by MuntashirAkon** [comment]
Hi, can you explain exactly where it went wrong? Please explain it here: #948. Thanks.

**Comment by brian6932** [comment]
It shouldn't actually be related to that.

**Comment by MuntashirAkon** [comment]
> It shouldn't actually be related to that.

The issue tracker tracks every issue that produces the crash. So, it should very much be identical to the issue even though it may be reproduced differently in your case.

**Comment by MuntashirAkon** [comment]
Duplicate of #948
