### ISSUE TITLE
No response in my old post

### ISSUE THREAD

**Issue by CamsShaft** [MuntashirAkon/AppManager#1337]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

It's telling me it's not even installed now so I really don't know what to say. Even with shizuku and any other services I figured would interfere, it still does this. If I fresh install or reboot my phone it runs perfectly until it's closed and then upon reopening nothing happens. Truly baffling.

### To Reproduce

1. Install App Manager.

### Expected behavior

Expect it to run normally and not be confused as to why it questions its own existence.

### Logs

TAKEN DIRECTLY FROM "AM.LOG" TODAY....

2024-04-07 17:47:39.284 E/ComponentBlocker: Root/ADB enabled but privileged service isn't alive.
2024-04-07 17:47:39.285 E/AppDetailsViewModel
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:58)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4970)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfoInternal(PackageManagerCompat.java:512)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:159)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:1032)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:211)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:47:39.287 E/AppDetailsViewModel
android.content.pm.PackageManager$NameNotFoundException: Package not installed
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:1065)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:211)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:47:39.288 E/AppDetailsViewModel: Could not fetch package info.
io.github.muntashirakon.AppManager.apk.ApkFile$ApkFileException: Package not installed.
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:213)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:47:41.895 W/LocalServerManager: closeBgServer: null  Read timed out
2024-04-07 17:48:05.235 E/ComponentBlocker: Root/ADB enabled but privileged service isn't alive.
2024-04-07 17:48:05.236 E/AppDetailsViewModel
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:58)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4970)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfoInternal(PackageManagerCompat.java:512)
	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:159)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:1032)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:211)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:48:05.238 E/AppDetailsViewModel
android.content.pm.PackageManager$NameNotFoundException: Package not installed
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:1065)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:211)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:48:05.239 E/AppDetailsViewModel: Could not fetch package info.
io.github.muntashirakon.AppManager.apk.ApkFile$ApkFileException: Package not installed.
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:213)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda27.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-04-07 17:48:09.256 W/PackageUtils: Could not retrieve package info list for user 0
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.

### Device info

- Device: Samsung S22 SM-S901W
- OS Version:Android 14
- App Manager Version: 3.1.5
- Mode: ADB

### Additional context

I had the same issue with the previous version and it has not gone away. I updated my earlier post but have not heard anything so I'm making a new report. I also cleared my cache and it's still persistent, I really dont want to have to factory reset if I don't have to. Love this app so much and it really sucks not being able to use it fully. Thanks for everything and hope we can get to the bottom of it!

**Comment by MuntashirAkon** [comment]
Duplicate of #1285

**Comment by MuntashirAkon** [comment]
I understand that you like the app very much. But patience is a virtue that you should exercise more often, at least, if you do not want your favourite app to go away because of the maintenance burden that, perhaps, you unknowingly create. I maintain this app as one of my hobbies. I've got a life and other hobbies, too. If you look at other issues, there's hardly any issues where I didn't make a reply. But exactly when I'm going to reply depends on my work schedules, priorities, etc. While it might be difficult for you to accept that your issue has a lower priority than most others, you should know that it's impossible anybody to make everyone happy.

Regarding the issue, although your ROM is based on Android, every device and every OS works differently due to customisations done on the top of Android. Your issue, in particular, seem to be quite specific to you as I did not find any issues that is similar to yours. So, naturally, it has a lower priority than those which are being faced by hundred others. By creating another issue, you've also increased the administrative burden which prompted me to write this statement. Just imagine, if you hadn't create this duplicate issue, I could've utilised that time to do something more productive which, in turns, would've created a space when I could've actually looked into your issue.

**Comment by CamsShaft** [comment]
What the?? Where in any of this warranted a response like that? I took my time and was careful in writing it to avoid getting bitched at and was nothing but respectful in how I brought up this issue. Perhaps instead of being condescending right off the bat you should take some of your own advice. Way to turn everything around and ensure that I know everything is my fault. It's probably my fault the family pet died when you were a kid too right?? Don't worry, you'll never fuckin hear from me again. Good luck if that's how you treat people with nothing but the best intentions. ✌️🖕

**Comment by CamsShaft** [comment]
K
