### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity 

### ISSUE THREAD

**Issue by chaoscalm** [MuntashirAkon/AppManager#1397]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3993)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8960)
   at android.app.Activity.performCreate(Activity.java:8938)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8592)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8960)
   at android.app.Activity.performCreate(Activity.java:8938)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8592)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;II)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:354)
   at io.github.muntashirakon.AppManager.compat.AppOpsManagerCompat.<init>(AppOpsManagerCompat.java:629)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:668)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8960)
   at android.app.Activity.performCreate(Activity.java:8938)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8592)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

### Device info

Device Info:
App version: 3.1.6
App version code: 429
Android build version: eng.tim.20240626.192903
Android release version: 14
Android SDK version: 34
Android build ID: lineage_beyond1lte-userdebug 14 AP2A.240605.024 eng.tim.20240626.192903 dev-keys
Device brand: samsung
Device manufacturer: samsung
Device name: beyond1lte
Device model: SM-G973F
Device product name: lineage_beyond1lte
Device hardware name: exynos9820
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: it-IT
In-App Language: auto
Mode: auto
Inferred Mode: root

**Comment by MuntashirAkon** [comment]
It appears AOSP 14.0 r50 has altered the `IPermissionManager` API once again. The changes will be included in the next release.

**Comment by MuntashirAkon** [comment]
Added in 86210def66efd8d3eaf93edb46c62186901d31ab
