### ISSUE TITLE
Crash on install from notification

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1398]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashed when trying to install from device notification.
1 tine crash...can't reproduce it.

### To Reproduce

1. Download some app on Droidify
2. When it's downloading remove Droidify from device regents which downloads in background
3. After the download, it shows the "Tap to install" option on notification, click on it
4. AppManager crashed. (I'm using Legacy installer for Droid-ify)

### Logs

```
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager.debug, PID: 13993
java.lang.IllegalArgumentException
	at android.os.Parcel.createException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.view.IWindowSession$Stub$Proxy.remove(IWindowSession.java:928)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3848)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6760)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:6737)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at android.app.Dialog.dismissDialog(Dialog.java:375)
	at android.app.Dialog.dismiss(Dialog.java:358)
	at androidx.appcompat.app.AppCompatDialog.dismiss(AppCompatDialog.java:140)
	at io.github.muntashirakon.AppManager.BaseActivity.lambda$onCreate$3$io-github-muntashirakon-AppManager-BaseActivity(BaseActivity.java:136)
	at io.github.muntashirakon.AppManager.BaseActivity$$ExternalSyntheticLambda3.onChanged(D8$$SyntheticClass:0)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:630)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:60)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:386)
	at com.android.server.wm.SurfaceAnimator.createAnimationLeash(SurfaceAnimator.java:307)
```

### Device info

- Device: Lenovo Tab4 8 plus
- OS Version: Android 9
- App Manager Version: 4.0.0-beta01-DEBUG (436)
- Mode: Root

### Additional context

Just after AM crash my System crashed so not sure if it's bug in my ROM instead.

**Comment by MuntashirAkon** [comment]
This is likely a system error, something to do with animation.
