### ISSUE TITLE
AppInfo `ConcurrentModificationException` crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1411]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AM crashed while opening AppInfo of an app.
1 time crash, can't reproduce it.

### Logs

```
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager.debug, PID: 32274
java.lang.RuntimeException: java.util.ConcurrentModificationException
	at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadTagCloudInternal$3(AppInfoViewModel.java:314)
	at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.util.ConcurrentModificationException
	at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:482)
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.getService(ProxyBinder.java:42)
	at io.github.muntashirakon.AppManager.compat.SensorServiceCompat.getSensorService(SensorServiceCompat.java:62)
	at io.github.muntashirakon.AppManager.compat.SensorServiceCompat.isSensorEnabled(SensorServiceCompat.java:27)
	at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadTagCloudInternal(AppInfoViewModel.java:233)
	at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadTagCloud$1$io-github-muntashirakon-AppManager-details-info-AppInfoViewModel(AppInfoViewModel.java:141)
	at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

### Device info

App version: **AM Debug v4.0.0-beta01 Run#2746**
App version code: 436
Android build version: eng.chef.20200713.073313
Android release version: 9
Android SDK version: 28
Android build ID: lineage_TB8704-userdebug 9 PQ3A.190801.002 eng.chef.20200713.073313 test-keys
Device brand: Lenovo
Device manufacturer: Lenovo
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: lineage_TB8704
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed via 906c4981ca8de26808f371b24c80e308e05ecd9c
