### ISSUE TITLE
File Manager crashed while browsing directories

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1429]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Self explanatory from the title.
1 time crash, not sure how to reproduce this.

### Logs

```
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager.debug, PID: 20159
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at java.util.Collections$SynchronizedList.get(Collections.java:2461)
	at io.github.muntashirakon.AppManager.fm.FmUtils.uriFromPathParts(FmUtils.java:197)
	at io.github.muntashirakon.AppManager.fm.FmPathListAdapter.calculateUri(FmPathListAdapter.java:81)
	at io.github.muntashirakon.AppManager.fm.FmFragment$1.handleOnBackPressed(FmFragment.java:146)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:279)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.kt:612)
	at android.app.Activity.onKeyUp(Activity.java:3083)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2721)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3366)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5044)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4912)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4625)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4786)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Device info

- Device: Lenovo Tab4 8 plus
- OS Version: Android 9
- App Manager Version: 4.0.0-beta01-DEBUG (436)
- Mode: Root

**Comment by MuntashirAkon** [comment]
Handled by cf64b0c9be6c7b845030cb6370201540eacf45ef
