### ISSUE TITLE
Unfreezing apps causes crash

### ISSUE THREAD

**Issue by FurhadTheNerd** [MuntashirAkon/AppManager#1446]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have frozen an app a couple of days ago called "element" so i wouldn't get notifications or try to open it again for the peace of my mind, today i went to unfreeze it and it unfreezing causes "app manager" to crash right away

### To Reproduce

1- select app you want to unfreeze
2- select unfreeze
3- *crashes*

### Logs

java.lang.NoSuchMethodError: No interface method setPackagesSuspendedAsUser([Ljava/lang/String;ZLandroid/os/PersistableBundle;Landroid/os/PersistableBundle;Landroid/content/pm/SuspendDialogInfo;Ljava/lang/String;I)[Ljava/lang/String; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.suspendPackages(PackageManagerCompat.java:328)
    at io.github.muntashirakon.AppManager.utils.FreezeUtils.unfreeze(FreezeUtils.java:63)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.freeze(AppInfoFragment.java:1631)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$setHorizontalActions$78$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:1039)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda86.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7931)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
    at android.view.View.performClickInternal(View.java:7908)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30990)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Device Info:
App version: 3.1.7
App version code: 430
Android build version: 12235381
Android release version: 14
Android SDK version: 34
Android build ID: AP2A.240905.003.F1
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
Device hardware name: oriole
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US-u-fw-sun-mu-celsius
In-App Language: auto
Mode: root
Inferred Mode: root

### Device info

- Device: pixel 6
- OS Version: android 14 (AP2A.240905.003.F1)
- App Manager Version: 3.1.7
- Mode: rooted via MAGISK 27.0 stable

### Additional context

logcat via foxlog: [15_09-11-38-01_336.zip](https://github.com/user-attachments/files/17005097/15_09-11-38-01_336.zip)

**Comment by FurhadTheNerd** [comment]
UPDATE: i have managed to find a fix by using android's package manager and a terminal like termux, you can use these two commands

su
pm enable package.name.here

I'm going to keep this bug report open in case its actually a wide spread issue

**Comment by binarynoise** [comment]
Same for freezing with suspend.

Workaround would be to set freezing method to disable in Settings - Rules

**Comment by MuntashirAkon** [comment]
Fixed in b2e4ed4792d7436951a0eec68677125788a2181a
