### ISSUE TITLE
AM crashed while installing an app

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1448]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Just downloaded an app from Droid-ify (Legacy installer), AM crashed.
1 time crash can't reproduce it.

### Logs

```
java.lang.IllegalArgumentException
    at android.os.Parcel.createException(Parcel.java:1954)
    at android.os.Parcel.readException(Parcel.java:1918)
    at android.os.Parcel.readException(Parcel.java:1868)
    at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:826)
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:758)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
    at android.app.Dialog.show(Dialog.java:329)
    at io.github.muntashirakon.AppManager.BaseActivity.onStart(BaseActivity.java:183)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
    at android.app.Activity.performStart(Activity.java:7165)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 Caused by: android.os.RemoteException: Remote stack trace:
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:630)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:60)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:386)
	at com.android.server.wm.WindowContainer.onParentSet(WindowContainer.java:184)
```

### Device info

Device Info:
App version: **4.0.0-beta01-DEBUG**
App version code: 436
Android build version: eng.chef.20200713.073313
Android release version: 9
Android SDK version: 28
Android build ID: lineage_TB8704-userdebug 9 PQ3A.190801.002 eng.chef.20200713.073313 test-keys
Device brand: Lenovo
Device manufacturer: Lenovo
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: lineage_TB8704
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: No root

**Comment by MuntashirAkon** [comment]
This crash was due to a UI state error in the system, and cannot be fixed by App Manager.
