### ISSUE TITLE
Remote server is active, but cannot connect it

### ISSUE THREAD

**Issue by EatHatsuneShallots** [MuntashirAkon/AppManager#1451]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Sometimes (usually happens after the app is killed), when I open AM Debug, the page stays in "Initializating...", until execute `adb shell killall am_local_server`, or timeout

### To Reproduce

1. Use the network debugging (wireless) to activate AM Debug
2. Wait a while (I'm not clear on what to do) and then make sure the app isn't running (maybe killed by system)
3. Open AM Debug

### Expected behavior

Immediate connection succeeds or fails, or able to restart local server

### Logs

```
2024-09-30 23:18:00.156 W/TypefaceUtil: Could not override fonts
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.putAll(Collections.java:1512)
	at io.github.muntashirakon.AppManager.utils.appearance.TypefaceUtil.overrideFonts(TypefaceUtil.java:129)
	at io.github.muntashirakon.AppManager.utils.appearance.TypefaceUtil.replaceFontsWithSystem(TypefaceUtil.java:36)
	at io.github.muntashirakon.AppManager.AppManager.onCreate(AppManager.java:42)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588)
	at android.app.ActivityThread.access$2600(ActivityThread.java:260)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
2024-09-30 23:18:00.237 D/SplashActivity: Waiting to be authenticated.
2024-09-30 23:18:00.239 W/KSManager: Using keystore BKS
2024-09-30 23:18:00.242 I/CompatUtil: Loading local protection key
2024-09-30 23:18:00.245 I/CompatUtil: AES local protection key found in keystore
2024-09-30 23:18:00.275 D/SplashActivity: Authenticated
2024-09-30 23:18:00.277 D/SecurityAndOpsViewModel: Before Ops::init
2024-09-30 23:18:00.349 D/Runner: RootShell
2024-09-30 23:18:00.350 D/RunnerUtils: PATH=/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
2024-09-30 23:18:00.351 D/RunnerUtils: SU(file=/sbin/su, exists=false, executable=false)
2024-09-30 23:18:00.351 D/RunnerUtils: SU(file=/system/sbin/su, exists=false, executable=false)
2024-09-30 23:18:00.352 D/RunnerUtils: SU(file=/product/bin/su, exists=false, executable=false)
2024-09-30 23:18:00.352 D/RunnerUtils: SU(file=/apex/com.android.runtime/bin/su, exists=false, executable=false)
2024-09-30 23:18:00.353 D/RunnerUtils: SU(file=/system/bin/su, exists=false, executable=false)
2024-09-30 23:18:00.354 D/RunnerUtils: SU(file=/system/xbin/su, exists=false, executable=false)
2024-09-30 23:18:00.356 D/RunnerUtils: SU(file=/odm/bin/su, exists=false, executable=false)
2024-09-30 23:18:00.357 D/RunnerUtils: SU(file=/vendor/bin/su, exists=false, executable=false)
2024-09-30 23:18:00.358 D/RunnerUtils: SU(file=/vendor/xbin/su, exists=false, executable=false)
2024-09-30 23:18:00.363 D/IPC: Init: Local server
2024-09-30 23:18:00.392 D/ServiceConnectionWrapper: Launching service...
2024-09-30 23:18:45.393 E/Ops
android.os.RemoteException: Binder not running.
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.getService(ServiceConnectionWrapper.java:86)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.bindService(ServiceConnectionWrapper.java:98)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindAmService(LocalServices.java:89)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindServices(LocalServices.java:38)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindServicesIfNotAlready(LocalServices.java:31)
	at io.github.muntashirakon.AppManager.settings.Ops.isAMServiceUpAndRunning(Ops.java:635)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:243)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:72)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
2024-09-30 23:19:01.951 W/LocalServerManager: closeBgServer: Error
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at java.io.DataInputStream.readFully(DataInputStream.java:198)
	at java.io.DataInputStream.readInt(DataInputStream.java:389)
	at io.github.muntashirakon.AppManager.server.common.DataTransmission.readMessage(DataTransmission.java:131)
	at io.github.muntashirakon.AppManager.server.common.DataTransmission.sendAndReceiveMessage(DataTransmission.java:149)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.closeBgServer(LocalServerManager.java:168)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.closeBgServer(LocalServer.java:164)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.exec(LocalServer.java:140)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.runCommand(LocalServer.java:125)
	at io.github.muntashirakon.AppManager.ipc.RootService.lambda$asRunnable$0(RootService.java:202)
	at io.github.muntashirakon.AppManager.ipc.RootService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
2024-09-30 23:19:01.955 W/LocalServerManager: closeBgServer: Error
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at java.io.DataInputStream.readFully(DataInputStream.java:198)
	at java.io.DataInputStream.readInt(DataInputStream.java:389)
	at io.github.muntashirakon.AppManager.server.common.DataTransmission.readMessage(DataTransmission.java:131)
	at io.github.muntashirakon.AppManager.server.common.DataTransmission.sendAndReceiveMessage(DataTransmission.java:149)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.closeBgServer(LocalServerManager.java:168)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.restart(LocalServer.java:173)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:292)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:72)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
2024-09-30 23:19:01.963 D/ServiceConnectionWrapper: Launching service...
2024-09-30 23:19:46.965 E/Ops
android.os.RemoteException: Binder not running.
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.getService(ServiceConnectionWrapper.java:86)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.bindService(ServiceConnectionWrapper.java:98)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindAmService(LocalServices.java:89)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindServices(LocalServices.java:38)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindServicesIfNotAlready(LocalServices.java:31)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:293)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:72)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
2024-09-30 23:19:46.968 D/SecurityAndOpsViewModel: After Ops::init
2024-09-30 23:19:46.977 D/SplashActivity: Authentication completed.
2024-09-30 23:19:47.095 D/BaseActivity: Already authenticated.
2024-09-30 23:19:47.257 D/MVM: New instance created
2024-09-30 23:19:47.667 D/Users: Missing required permission: MANAGE_USERS or CREATE_USERS (7+). Falling back to unprivileged mode.
2024-09-30 23:19:48.967 W/AppUsageStatsManager: Missing required permission: android.permission.READ_PRIVILEGED_PHONE_STATE
2024-09-30 23:19:49.449 W/AppDb: Error: Cannot find file:///data/system/users/0/settings_ssaid.xml
```

### Device info

- Device: HUAWEI P30 Pro
- OS Version: 10
- App Manager Version: v4.0.0-beta1 (436)
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Should be fixed by 51f107fa2632e42eea030e0f91e48fe39d8f5836
