### ISSUE TITLE
Cannot make backups, unknown error ocurred

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#1461]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I always get this error when trying to make backups of my apps anywhere.

```
====> op=BACKUP_RESTORE, mode=1 pkg=(app.eduroam.geteduroam, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:216)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:91)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No interface method getPermissionFlags(Ljava/lang/String;Ljava/lang/String;I)I in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:273)
	at io.github.muntashirakon.AppManager.backup.BackupOp.backupExtras(BackupOp.java:384)
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:176)
	... 8 more
====> op=BACKUP_RESTORE, mode=1 pkg=(de.nulide.findmydevice, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:216)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:91)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No interface method getPermissionFlags(Ljava/lang/String;Ljava/lang/String;I)I in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:273)
	at io.github.muntashirakon.AppManager.backup.BackupOp.backupExtras(BackupOp.java:384)
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:176)
	... 8 more
====> op=BACKUP_RESTORE, mode=1 pkg=(com.aurora.store, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:216)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:91)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No interface method getPermissionFlags(Ljava/lang/String;Ljava/lang/String;I)I in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:273)
	at io.github.muntashirakon.AppManager.backup.BackupOp.backupExtras(BackupOp.java:384)
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:176)
	... 8 more
====> op=BACKUP_RESTORE, mode=1 pkg=(com.aurora.store, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:216)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:91)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No interface method getPermissionFlags(Ljava/lang/String;Ljava/lang/String;I)I in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:273)
	at io.github.muntashirakon.AppManager.backup.BackupOp.backupExtras(BackupOp.java:384)
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:176)
	... 8 more
====> op=BACKUP_RESTORE, mode=1 pkg=(app.eduroam.geteduroam, 0)
io.github.muntashirakon.AppManager.backup.BackupException: Unknown error occurred.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:216)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:91)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodError: No interface method getPermissionFlags(Ljava/lang/String;Ljava/lang/String;I)I in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at io.github.muntashirakon.AppManager.compat.PermissionCompat.getPermissionFlags(PermissionCompat.java:273)
	at io.github.muntashirakon.AppManager.backup.BackupOp.backupExtras(BackupOp.java:384)
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:176)
	... 8 more
```

### To Reproduce

Make a backup of anything, to any location

### Device info

- Device: Razer Phone
- OS Version: Android 14, LineageOS
- App Manager Version: 3.0.0-rc03
- Mode: Root

Edit: Not just limited to my SDCard as I thought, I'm getting that everywhere

**Comment by UltraBlackLinux** [comment]
should've updated, just noticed that I was behind some versions, oops
