### ISSUE TITLE
QuickPic Gallery Mod 8.5 fails to restore on Pixel 8

### ISSUE THREAD

**Issue by genpfault** [MuntashirAkon/AppManager#1479]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Attempting to restore a backup of [QuickPic Gallery Mod 8.5](https://github.com/WSTxda/QP-Gallery-Releases/releases/download/8.5/QP.Gallery.8.5.apk) taken on a OnePlus Nord N100 (Android 11, LineageOS GSI) onto a Pixel 8 (Android 14, MicroG's LineageOS 21 build) fails with this exception:

```none
====> op=BACKUP_RESTORE, mode=RESTORE pkg=(com.alensw.PicFolder, 0)
io.github.muntashirakon.AppManager.backup.BackupException: A (re)install was necessary but couldn't perform it.
	at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:370)
	at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:202)
	at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:189)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$restoreBackups$3$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:391)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

Manually extracting the `base.apk` from the backup's `source.tar.gz.0` and attempting to install it via the file manager fails with:

> App not installed as app isn't compatible with your phone.

Popping the APK open reveals a `lib` directory with only `armeabi` and `x86` native libraries.

### Expected behavior

Some indication as to why the restore failed would be nice, even if it would just be returning the OS's "App not installed as app isn't compatible with your phone." message.

### Device info

- Device: Pixel 8
- OS Version: [MicroG's LineageOS 21 build](https://download.lineage.microg.org/shiba/), `20241126`
- App Manager Version: 4.0.0-beta02 (437)
- Mode: Root

**Comment by MuntashirAkon** [comment]
Added in 4a7d3f9e1c0dce81235e33ca267b4f21bdad7499
