### ISSUE TITLE
Disabled Tag-manager service leads to crashes

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#157]
**Describe the bug**
Disabling the Tag-manager service makes some apps crash - any replacement?

**Crash logs**

```
FATAL EXCEPTION: google-tag-manager-background-thread
Process: de.eplus.mappecc.client.android.alditalk, PID: 26103
java.lang.SecurityException: Not allowed to bind to service Intent { cmp=de.eplus.mappecc.client.android.alditalk/com.google.android.gms.tagmanager.TagManagerService }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:20)
	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:13)
	at com.google.android.gms.internal.gtm.zzgt.zzkz(Unknown Source:44)
	at com.google.android.gms.internal.gtm.zzgt.zzb(Unknown Source:0)
	at com.google.android.gms.internal.gtm.zzge.run(Unknown Source:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Consider opening a thread on XDA or other forums for helps regarding this issue.
