### ISSUE TITLE
Can't open sharedpref of Miui screenshot app

### ISSUE THREAD

**Issue by AadilGillani** [MuntashirAkon/AppManager#169]
java.lang.ClassCastException: androidx.appcompat.widget.LinearLayoutCompat cannot be cast to android.widget.LinearLayout
    at io.github.muntashirakon.AppManager.sharedpref.EditPrefItemFragment.onCreateDialog(EditPrefItemFragment.java:145)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:641)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:555)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1639)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:276)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:455)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2389)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2145)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2083)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1985)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
    at android.os.Handler.handleCallback(Unknown Source:2)
    at android.os.Handler.dispatchMessage(Unknown Source:4)
    at android.os.Looper.loop(Unknown Source:242)
    at android.app.ActivityThread.main(Unknown Source:101)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

Device Info:
App version: 2.5.19-DEBUG
App version code: 372
Android build version: 20.11.25
Android release version: 10
Android SDK version: 29
Android build ID: QKQ1.190910.002 20.11.25
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: lavender
Device model: Redmi Note 7
Device product name: lavender
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto

**Comment by MuntashirAkon** [comment]
Fixed via 781b181
