### ISSUE TITLE
Crash if you try to install an app with the "sign apk" option enabled

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#175]
**Describe the bug**
AM crash if you try to install an app with the "sign apk" option is enabled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any apk in file manager'
2. Click on 'open with Install (App Manager app installer) when sign apk is enabled'
3. See error

**Expected behavior**
I don't know.

**Crash logs**
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
    at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateManifestFile(V1SchemeSigner.java:372)
    at com.android.apksig.internal.apk.v1.V1SchemeSigner.sign(V1SchemeSigner.java:247)
    at com.android.apksig.DefaultApkSignerEngine.outputJarEntries(DefaultApkSignerEngine.java:740)
    at com.android.apksig.ApkSigner.sign(ApkSigner.java:509)
    at com.android.apksig.ApkSigner.sign(ApkSigner.java:211)
    at io.github.muntashirakon.AppManager.apk.SignUtils.sign(SignUtils.java:219)
    at io.github.muntashirakon.AppManager.apk.ApkFile$Entry.getSignedFile(ApkFile.java:714)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity.getPackageInfo(PackageInstallerActivity.java:229)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity.lambda$onCreate$11$PackageInstallerActivity(PackageInstallerActivity.java:141)
    at io.github.muntashirakon.AppManager.apk.installer.-$$Lambda$PackageInstallerActivity$MZBi-8orBmxfnMQGj0iha35aLOs.run(lambda)
    at java.lang.Thread.run(Thread.java:760)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/io.github.muntashirakon.AppManager.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/io.github.muntashirakon.AppManager.debug-1/lib/arm64, /data/app/io.github.muntashirakon.AppManager.debug-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateManifestFile(V1SchemeSigner.java:372)
   at com.android.apksig.internal.apk.v1.V1SchemeSigner.sign(V1SchemeSigner.java:247)
   at com.android.apksig.DefaultApkSignerEngine.outputJarEntries(DefaultApkSignerEngine.java:740)
   at com.android.apksig.ApkSigner.sign(ApkSigner.java:509)
   at com.android.apksig.ApkSigner.sign(ApkSigner.java:211)
   at io.github.muntashirakon.AppManager.apk.SignUtils.sign(SignUtils.java:219)
   at io.github.muntashirakon.AppManager.apk.ApkFile$Entry.getSignedFile(ApkFile.java:714)
   at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity.getPackageInfo(PackageInstallerActivity.java:229)
   at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity.lambda$onCreate$11$PackageInstallerActivity(PackageInstallerActivity.java:141)
   at io.github.muntashirakon.AppManager.apk.installer.-$$Lambda$PackageInstallerActivity$MZBi-8orBmxfnMQGj0iha35aLOs.run(lambda)
   at java.lang.Thread.run(Thread.java:760)

Device Info:
App version: 2.5.20-DEBUG
App version code: 374
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: Miui 11 - Android 7.0
 - App Manager Version: v2.5.20-DEBUG
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
This is a Java 1.7 issue, I believe. I'll try a fix.

**Comment by MuntashirAkon** [comment]
Fixed via caa35f45
