### ISSUE TITLE
Crash when trying to open the App Details of any app

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#185]
**Describe the bug**
AM crashes when I try to open the App Details of any app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'any app within the AM'
2. See error

**Crash logs**
java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
    at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:256)
    at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:225)
    at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:208)
    at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:169)
    at io.github.muntashirakon.AppManager.apk.ApkUtils.getManifestFromApk(ApkUtils.java:124)
    at io.github.muntashirakon.AppManager.apk.ApkFile.<init>(ApkFile.java:349)
    at io.github.muntashirakon.AppManager.apk.ApkFile.createInstance(ApkFile.java:116)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackage(AppDetailsViewModel.java:154)
    at io.github.muntashirakon.AppManager.details.AppDetailsActivity.lambda$onCreate$5$AppDetailsActivity(AppDetailsActivity.java:117)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsActivity$AFaz09Og1VPxdJ3mjVrPnDz4lJU.run(lambda)
    at java.lang.Thread.run(Thread.java:760)

Device Info:
App version: 2.5.20-DEBUG
App version code: 374
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: Miui 11 - Android 7.0
 - App Manager Version: v2.5.20-DEBUG#557
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Fixed via b55b578b
