### ISSUE TITLE
Crash while trying to open "About Device" & Apps don't load

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#198]
**Describe the bug**
The app crashes when I try toopen About Device and the apps list dont't load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to open 'About Device'
2. See error

**Crash logs**
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
    at android.os.Parcel.readException(Parcel.java:1715)
    at android.os.Parcel.readException(Parcel.java:1668)
    at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:857)
    at io.github.muntashirakon.AppManager.misc.Users.getUsers(Users.java:73)
    at io.github.muntashirakon.AppManager.misc.Users.getUsersHandles(Users.java:89)
    at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$1$MainViewModel(MainViewModel.java:217)
    at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$qLo3jFzmIzSIPMR_AVjx0qF7k6w.run(lambda)
    at java.lang.Thread.run(Thread.java:760)

Device Info:
App version: 2.5.21-DEBUG
App version code: 376
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.21-DEBUG#620
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Should be fixed in 9cde63a0

**Comment by RickyM7** [comment]
@MuntashirAkon I tested and remains the same, however I realized that the crash only occurs if I try to open the "About Device" option, but the list of apps really doesn't load.

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon I tested and remains the same, however I realized that the crash only occurs if I try to open the "About Device" option, but the list of apps really doesn't load.

Make sure you have reinstalled the app. Debug builds have to be reinstalled otherwise the app may misbehave.

**Comment by RickyM7** [comment]
> Make sure you have reinstalled the app. Debug builds have to be reinstalled otherwise the app may misbehave.

I always reinstall the debug versions. I will test the latest version debug now.

**Comment by RickyM7** [comment]
java.lang.RuntimeException: Unable to pause activity {io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.settings.SettingsActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@21b2e67 is not valid; is your activity running?
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3843)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3809)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3783)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3754)
    at android.app.ActivityThread.-wrap16(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
 Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@21b2e67 is not valid; is your activity running?
   at android.view.ViewRootImpl.setView(ViewRootImpl.java:701)
   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:344)
   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
   at android.app.Dialog.show(Dialog.java:316)
   at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:684)
   at io.github.muntashirakon.AppManager.types.FullscreenDialog.onStart(FullscreenDialog.java:180)
   at androidx.fragment.app.Fragment.performStart(Fragment.java:2993)
   at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:606)
   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:308)
   at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
   at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
   at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:455)
   at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2389)
   at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2145)
   at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2083)
   at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1985)
   at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3119)
   at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3071)
   at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:284)
   at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:374)
   at android.app.Activity.performPause(Activity.java:6994)
   at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)
   at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3832)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3809)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3783)
   at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3754)
   at android.app.ActivityThread.-wrap16(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:165)
   at android.app.ActivityThread.main(ActivityThread.java:6375)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Device Info:
App version: 2.5.21-DEBUG
App version code: 376
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

This is another crash log of Version 2.5.21-DEBUG#621. Btw, everything has been fixed in Version 2.5.21-DEBUG#622.
I'll close the issue now.
