### ISSUE TITLE
Crash when trying to edit and create shortcuts from uninstalled apps

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#203]
**Describe the bug**
The app crashes when trying to create a shortcut from some app you used "Open with App Manager". This occurs in both the latest stable version and the debug version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any uninstalled app'
2. Click on 'Open with App Manager'
3. Go to 'Activities' tab
4. Click on 'any clickable activity'
5. Click on 'Edit Shortcut'
6. Click on 'Create Shortcut'
7. See error

Note: The crash does not occur with all activities.

**Crash logs**
java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
    at java.lang.String.substring(String.java:1931)
    at io.github.muntashirakon.AppManager.details.LauncherIconCreator.createLauncherIcon(LauncherIconCreator.java:71)
    at io.github.muntashirakon.AppManager.details.EditShortcutDialogFragment.lambda$onCreateDialog$2$EditShortcutDialogFragment(EditShortcutDialogFragment.java:141)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$EditShortcutDialogFragment$lzUAlfvRU-O9vW9vBXxAeWDuXZk.onClick(lambda)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Device Info:
App version: 2.5.21-DEBUG
App version code: 376
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.21-DEBUG#646 (v2.5.20 too)
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Ah, shortcuts shouldn't be allowed in first place.

**Comment by MuntashirAkon** [comment]
Fixed via a07d0265
