### ISSUE TITLE
Crash on opening profile page

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#210]
AM crashes on opening the profiles page after creating a profile.

Steps to reproduce:
- Create a profile in AM
- Open the profiles page later
- Crash

Stack trace:
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.github.muntashirakon.AppManager.profiles.ProfileMetaManager$Profile.comment' on a null object reference
    at io.github.muntashirakon.AppManager.profiles.ProfileMetaManager.getLocalisedSummaryOrComment(ProfileMetaManager.java:273)
    at io.github.muntashirakon.AppManager.profiles.ProfileManager.getProfiles(ProfileManager.java:53)
    at io.github.muntashirakon.AppManager.profiles.ProfilesViewModel.loadProfiles(ProfilesViewModel.java:49)
    at io.github.muntashirakon.AppManager.profiles.-$$Lambda$o3tAF0V35Ip0P7A365H_Un-pThc.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:919)

Device Info:
App version: 2.5.21-PRE
App version code: 377
Android release version: 10
Android SDK version: 29
Device brand: lge
Device manufacturer: LGE
Device name: lucye
Device model: LG-H870
Device product name: lucye_global_com
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
```

Possibly a null pointer when the profile description is empty?

**Comment by MuntashirAkon** [comment]
Should be fixed in 9da92c78.
