### ISSUE TITLE
Crash on start - Android-x86 (VirtualBox)

### ISSUE THREAD

**Issue by DonQuixoteI** [MuntashirAkon/AppManager#214]
AM crashes when trying to start app after installation.

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.main.MainViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.main.MainViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
   at io.github.muntashirakon.AppManager.main.MainActivity.onCreate(MainActivity.java:209)
   at android.app.Activity.performCreate(Activity.java:7146)
   at android.app.Activity.performCreate(Activity.java:7137)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:193)
   at android.app.ActivityThread.main(ActivityThread.java:6669)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Device Info:
App version: 2.5.21-PRE
App version code: 377
Android build version: eng.lh.20200325.112926
Android release version: 9
Android SDK version: 28
Android build ID: android_x86_64-userdebug 9 PI eng.lh.20200325.112926 test-keys
Device brand: Android-x86
Device manufacturer: innotek GmbH
Device name: x86_64
Device model: VirtualBox
Device product name: android_x86_64
Device hardware name: android_x86_64
ABIs: [x86_64, x86, armeabi-v7a, armeabi]
ABIs (32bit): [x86, armeabi-v7a, armeabi]
ABIs (64bit): [x86_64]
System language: en-US
In-App Language: auto

**Comment by MuntashirAkon** [comment]
Should be fixed in 36b03c23. Can you check? You can find latest debug builds in https://github.com/MuntashirAkon/AppManager/actions.

**Comment by DonQuixoteI** [comment]
Crash log of debug build #702:

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.main.MainViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.main.MainViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
   at io.github.muntashirakon.AppManager.main.MainActivity.onCreate(MainActivity.java:209)
   at android.app.Activity.performCreate(Activity.java:7146)
   at android.app.Activity.performCreate(Activity.java:7137)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:193)
   at android.app.ActivityThread.main(ActivityThread.java:6669)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Device Info:
App version: 2.5.22-DEBUG
App version code: 378

**Comment by MuntashirAkon** [comment]
Can you provide me the link to the VBox image file? I've to check it myself.

**Comment by DonQuixoteI** [comment]
android-x86.org/download.html suggests OSDN and FOSSHUB. The 64-bit ISO file for Android-9.0-r2 : [OSDN](https://osdn.net/projects/android-x86/downloads/71931/android-x86_64-9.0-r2.iso/), [FOSSHUB](https://www.fosshub.com/Android-x86.html?dwl=android-x86_64-9.0-r2.iso)

**Comment by MuntashirAkon** [comment]
There could be some issues on your side.

v2.5.21 x86_64 version is running fine on Android 9.0 r2 (64 bit).

![Screenshot 2021-04-27 at 06 38 34](https://user-images.githubusercontent.com/8176128/116168520-67f98880-a724-11eb-8cff-dd2fe63c8792.png)

**Comment by MuntashirAkon** [comment]
Hmmm, odd. It crashes after I've installed the OS. It worked fine on live CD.

**Comment by MuntashirAkon** [comment]
Fixed in 08579ca5.
