### ISSUE TITLE
Crash by clicking save in 'Net policy' option

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#247]
**To Reproduce**
Steps to reproduce the behaviour:
1. Enter any app in AM
2. Go to the 'Net policy' option and click 'save'
3. See error

**Crash logs**
java.lang.SecurityException: NetworkPolicy: Neither user 12076 nor current process has android.permission.MANAGE_NETWORK_POLICY.
    at android.os.Parcel.readException(Parcel.java:1715)
    at android.os.Parcel.readException(Parcel.java:1668)
    at android.net.INetworkPolicyManager$Stub$Proxy.setUidPolicy(INetworkPolicyManager.java:317)
    at io.github.muntashirakon.AppManager.servermanager.NetworkPolicyManagerCompat.setUidPolicy(NetworkPolicyManagerCompat.java:36)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$onOptionsItemSelected$15$AppInfoFragment(AppInfoFragment.java:352)
    at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$IWiL3tob-mV6vQ6zHwztJGuoL6I.onClick(lambda)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Device Info:
App version: 2.5.23-DEBUG
App version code: 380
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: pt-BR
Mode: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.23-DEBUG#796
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Fixed in 57df6e0d
