### ISSUE TITLE
Crash when uninstalling app

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#259]
Hey, there,
I have noticed some crashes, when uninstalling apps.
```
java.lang.IllegalArgumentException: Unknown component: ComponentInfo{<app>/com.adcolony.sdk.AdColonyAdViewActivity}
    at android.os.Parcel.createException(Parcel.java:2075)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:7381)
    at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2563)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.isComponentDisabled(AppDetailsFragment.java:563)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getActivityView(AppDetailsFragment.java:845)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:825)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:584)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1655)
    at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1509)
    at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1417)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
    at android.view.View.layout(View.java:22466)
    at android.view.ViewGroup.layout(ViewGroup.java:6304)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:726)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.Settings.getComponentEnabledSettingLPr(Settings.java:4263)
	at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:21720)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3497)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4109)
	at android.os.Binder.execTransactInternal(Binder.java:1021)


Device Info:
App version: 2.5.22-PRE
App version code: 379
Android build version: a912fb9321
Android release version: 10
Android SDK version: 29
Android build ID: lineage_cheryl-userdebug 10 QQ3A.200805.001 a912fb9321
Device brand: razer
Device manufacturer: Razer
Device name: cheryl
Device model: Phone
Device product name: lineage_cheryl
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: auto
```

Thanks!

_Sent from my Phone using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MuntashirAkon** [comment]
Already fixed in 7f3eeee2.
