### ISSUE TITLE
App crashing at specific Tabs

### ISSUE THREAD

**Issue by alex26052005** [MuntashirAkon/AppManager#299]
**Describe the bug**
The App is crashing, when going to Providers, App OPS, User Permissions and Permissions.

**Crash logs**
java.lang.ExceptionInInitializerError
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:917)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1410)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:917)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
   at java.lang.Thread.run(Thread.java:923)

**Device info**
App version: 2.5.20
App version code: 375
Android build version: G973FXXU9ETLJ
Android release version: 11
Android SDK version: 30
Android build ID: beyond1ltexx-user 11 RP1A.200720.012 G973FXXU9ETLJ release-keys
Device brand: samsung
Device manufacturer: Samsung
Device name: beyond1
Device model: SM-G973F
Device product name: beyond1ltexx
Device hardware name: exynos9820
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: de-DE
In-App Language: auto, but doesn't matter
Mode: root, gut doesn't matter

**Comment by alex26052005** [comment]
Nevermind, with the newest debug Version it's working

**Comment by MuntashirAkon** [comment]
Duplicate of #194
