### ISSUE TITLE
java.lang.NullPointerException: intent's action must be set

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#315]
Latest debug build \#988 crashes when I try creating shortcut.
```
<<< log_count = 33 >>>
[03-09 22:22:56.664 2110:2250 D/ArtManagerInternalImpl]
/data/misc/iorapd/io.github.muntashirakon.AppManager.debug/382/io.github.muntashirakon.AppManager.main.MainActivity/compiled_traces/compiled_trace.pb doesn't exist

[03-09 22:22:57.330 24924:24947 I/chatty]
uid=10141(io.github.muntashirakon.AppManager.debug) FinalizerDaemon identical 7 lines

[03-09 22:22:58.563 2110:3313 I/ActivityTaskManager]
START u0 {cmp=io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity (has extras)} from uid 10141

[03-09 22:22:58.721 2110:2250 I/ActivityTaskManager]
Displayed io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity: +156ms

[03-09 22:23:04.972 2110:2250 D/ArtManagerInternalImpl]
/data/misc/iorapd/io.github.muntashirakon.AppManager.debug/382/io.github.muntashirakon.AppManager.details.AppDetailsActivity/compiled_traces/compiled_trace.pb doesn't exist

[03-09 22:23:05.091 24924:25615 W/ppManager.debu]
Long monitor contention with owner pool-4-thread-3 (25612) at io.github.muntashirakon.AppManager.runner.Runner$Result io.github.muntashirakon.AppManager.runner.Runner.runCommand(io.github.muntashirakon.AppManager.runner.Runner, java.lang.String, java.io.InputStream)(Runner.java:174) waiters=0 in io.github.muntashirakon.AppManager.runner.Runner$Result io.github.muntashirakon.AppManager.runner.Runner.runCommand(java.lang.String[]) for 193ms

[03-09 22:23:05.617 24924:24924 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager.debug, PID: 24924
java.lang.NullPointerException: intent's action must be set
	at java.util.Objects.requireNonNull(Objects.java:245)
	at android.content.pm.ShortcutInfo$Builder.setIntents(ShortcutInfo.java:1268)
	at androidx.core.content.pm.ShortcutInfoCompat.toShortcutInfo(ShortcutInfoCompat.java:103)
	at androidx.core.content.pm.ShortcutManagerCompat.requestPinShortcut(ShortcutManagerCompat.java:175)
	at io.github.muntashirakon.AppManager.details.LauncherIconCreator.doCreateShortcut(LauncherIconCreator.java:120)
	at io.github.muntashirakon.AppManager.details.LauncherIconCreator.createLauncherIcon(LauncherIconCreator.java:71)
	at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.lambda$getActivityView$4$AppDetailsFragment$AppDetailsRecyclerAdapter(AppDetailsFragment.java:930)
	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsFragment$AppDetailsRecyclerAdapter$jSa_6cUbX7LFJP6qqdngzF3zjQo.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7448)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

[03-09 22:23:05.659 2110:25388 W/ActivityTaskManager]
  Force finishing activity io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity

[03-09 22:23:05.741 2110:10360 E/ActivityManager]
Sending non-protected broadcast io.github.muntashirakon.AppManager.action.SERVER_DISCONNECTED from system uid 0 pkg null
java.lang.Throwable
	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:15900)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16571)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15913)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16727)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2283)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

[03-09 22:23:05.748 14538:26414 D/IPC]
ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService} unbind

[03-09 22:23:05.749 2110:2734 I/WindowManager]
WIN DEATH: Window{9fdcfc u0 io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.MainActivity}

[03-09 22:23:05.750 2110:2734 W/InputDispatcher]
Attempted to unregister already unregistered input channel '9fdcfc io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.MainActivity (server)'

[03-09 22:23:05.750 2110:25388 I/ActivityManager]
Process io.github.muntashirakon.AppManager.debug (pid 24924) has died: fg  TOP 

[03-09 22:23:05.756 2110:12247 I/WindowManager]
WIN DEATH: Window{343ca48 u0 io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity}

[03-09 22:23:05.756 2110:12247 W/InputDispatcher]
Attempted to unregister already unregistered input channel '343ca48 io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity (server)'

[03-09 22:23:05.773 2110:2188 W/ActivityManager]
ProcessRecord{262ed2e 0:io.github.muntashirakon.AppManager.debug/u0a141}: ART verification disabled

[03-09 22:23:05.788 2110:2252 I/ActivityManager]
Start proc 25644:io.github.muntashirakon.AppManager.debug/u0a141 for top-activity {io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.MainActivity}

[03-09 22:23:05.842 2507:2507 D/InterruptionStateProvider]
No bubble up: not allowed to bubble: 0|io.github.muntashirakon.AppManager.debug|2|null|10141

[03-09 22:23:05.845 2110:2110 E/NotificationService]
Muting recently noisy 0|io.github.muntashirakon.AppManager.debug|2|null|10141

[03-09 22:23:05.883 2507:2507 D/InterruptionStateProvider]
No bubble up: not allowed to bubble: 0|io.github.muntashirakon.AppManager.debug|2|null|10141

[03-09 22:23:05.894 2507:2507 D/InterruptionStateProvider]
No bubble up: not allowed to bubble: 0|io.github.muntashirakon.AppManager.debug|2|null|10141

[03-09 22:23:05.973 25644:25644 I/EdXposed]
Loading modules for io.github.muntashirakon.AppManager.debug

[03-09 22:23:05.855 2110:2110 E/NotificationService]
Muting recently noisy 0|io.github.muntashirakon.AppManager.debug|2|null|10141

[03-09 22:23:06.175 2110:2188 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{5761971 u0 io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity t-1 f}}

[03-09 22:23:06.264 25644:25644 I/XLua.Xposed]
Loaded io.github.muntashirakon.AppManager.debug:10141

[03-09 22:23:06.305 25644:25644 I/LoadedApk]
No resource references to update in package io.github.muntashirakon.AppManager.debug.feat_docs

[03-09 22:23:06.444 2110:8160 I/ActivityTaskManager]
START u0 {cmp=io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.crypto.AuthenticationActivity} from uid 10141

[03-09 22:23:06.652 2110:12247 E/ActivityManager]
Sending non-protected broadcast io.github.muntashirakon.AppManager.action.SERVER_CONNECTED from system uid 0 pkg null
java.lang.Throwable
	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:15900)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16571)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15913)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16727)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2283)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

[03-09 22:23:06.704 2110:2250 I/ActivityTaskManager]
Displayed io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.crypto.AuthenticationActivity: +259ms

[03-09 22:23:06.729 25644:25707 D/SHELL_IN]
cp /data/user_de/0/io.github.muntashirakon.AppManager.debug/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process  /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer)&

[03-09 22:23:06.932 25726:25726 D/AndroidRuntime]
Calling main entry io.github.muntashirakon.AppManager.server.IPCMain

[03-09 22:23:07.128 14538:14538 D/IPC]
ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService} rebind

[03-09 22:23:07.925 25644:25667 I/chatty]
uid=10141(io.github.muntashirakon.AppManager.debug) FinalizerDaemon identical 1 line

`

**Comment by MuntashirAkon** [comment]
Fixed in 51526328
