### ISSUE TITLE
Crashes on enabling global component blocking in preferences always .

### ISSUE THREAD

**Issue by Genxster1998** [MuntashirAkon/AppManager#322]
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo[] android.content.pm.PackageInfo.activities' on a null object reference
    at io.github.muntashirakon.AppManager.utils.PackageUtils.collectComponentClassNames(PackageUtils.java:210)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.<init>(ComponentsBlocker.java:187)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getInstance(ComponentsBlocker.java:150)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getMutableInstance(ComponentsBlocker.java:117)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.applyAllRules(ComponentsBlocker.java:203)
    at io.github.muntashirakon.AppManager.settings.MainPreferences.lambda$onCreatePreferences$11$MainPreferences(MainPreferences.java:203)
    at io.github.muntashirakon.AppManager.settings.-$$Lambda$MainPreferences$atbWM-M6qSDF3jsMYyfTgU1D2ss.onPreferenceChange(Unknown Source:2)
    at androidx.preference.Preference.callChangeListener(Preference.java:1118)
    at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
    at androidx.preference.Preference.performClick(Preference.java:1182)
    at androidx.preference.Preference.performClick(Preference.java:1166)
    at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
    at androidx.preference.Preference$1.onClick(Preference.java:181)
    at android.view.View.performClick(View.java:7259)
    at android.view.View.performClickInternal(View.java:7236)
    at android.view.View.access$3600(View.java:801)
    at android.view.View$PerformClick.run(View.java:27897)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7398)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
 Caused by: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo[] android.content.pm.PackageInfo.activities' on a null object reference
   at io.github.muntashirakon.AppManager.utils.PackageUtils.collectComponentClassNames(PackageUtils.java:220)
   at io.github.muntashirakon.AppManager.utils.PackageUtils.collectComponentClassNames(PackageUtils.java:207)
   at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.<init>(ComponentsBlocker.java:187)
   at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getInstance(ComponentsBlocker.java:150)
   at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getMutableInstance(ComponentsBlocker.java:117)
   at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.applyAllRules(ComponentsBlocker.java:203)
   at io.github.muntashirakon.AppManager.settings.MainPreferences.lambda$onCreatePreferences$11$MainPreferences(MainPreferences.java:203)
   at io.github.muntashirakon.AppManager.settings.-$$Lambda$MainPreferences$atbWM-M6qSDF3jsMYyfTgU1D2ss.onPreferenceChange(Unknown Source:2)
   at androidx.preference.Preference.callChangeListener(Preference.java:1118)
   at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
   at androidx.preference.Preference.performClick(Preference.java:1182)
   at androidx.preference.Preference.performClick(Preference.java:1166)
   at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
   at androidx.preference.Preference$1.onClick(Preference.java:181)
   at android.view.View.performClick(View.java:7259)
   at android.view.View.performClickInternal(View.java:7236)
   at android.view.View.access$3600(View.java:801)
   at android.view.View$PerformClick.run(View.java:27897)
   at android.os.Handler.handleCallback(Handler.java:883)
   at android.os.Handler.dispatchMessage(Handler.java:100)
   at android.os.Looper.loop(Looper.java:214)
   at android.app.ActivityThread.main(ActivityThread.java:7398)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

Device Info:
App version: 2.5.22-PRE
App version code: 379
Android build version: eng.vishwa.20210122.113105
Android release version: 10
Android SDK version: 29
Android build ID: rr_lavender-userdebug 10 QQ3A.200905.001 eng.vishwa.20210122.113105 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: lavender
Device model: Redmi Note 7s
Device product name: lavender
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto 

- [x] ## Further , it is too unstable to use , I can't use all  app manager intents like installer , scanner ,app info.Always Ends like **failed to get app info**

**Comment by MuntashirAkon** [comment]
Already fixed in v2.5.23-PRE

**Comment by Genxster1998** [comment]
It's not usable still ,best one is v2.5.21 crashes always even on V2.5.24Pre

**Comment by MuntashirAkon** [comment]
> It's not usable still ,best one is v2.5.21 crashes always even on V2.5.24Pre

Which crash? Could you provide any crash logs? Open another issue if it's unrelated to this one.
