### ISSUE TITLE
Endless loading loop in "uses permissions" tab

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#391]
When swiping to the "uses permissions" tab, it fails to load.

Log:

```
2021-04-21 20:32:19.175 E/IPC: Init: Local server
2021-04-21 20:32:19.220 D/IPCUtils: Launching service...
2021-04-21 20:32:19.222 D/IPC: Total bound services: 0
2021-04-21 20:32:19.223 D/IPC: Need to start a new connection.
2021-04-21 20:32:19.231 E/IPC: Running service starter script...
2021-04-21 20:32:19.268 D/AdbShell - Command: cp /data/user_de/0/io.github.muntashirakon.AppManager.debug/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process  /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer)&
2021-04-21 20:32:19.272 D/AdbShell - Stdout: 
2021-04-21 20:32:19.274 D/AdbShell - Return Code: 0
2021-04-21 20:32:20.393 D/IPCUtils: service onServiceConnected
2021-04-21 20:32:20.395 D/IPCUtils: service onResponseReceived
2021-04-21 20:32:20.946 D/MVM: New instance created
2021-04-21 20:32:25.209 D/ADVM: New constructor called.
2021-04-21 20:32:25.340 D/ADVM: Package name is being set
2021-04-21 20:32:25.342 D/ADVM: Package name is being set for io.github.muntashirakon.AppManager.debug
2021-04-21 20:32:26.095 E/ADA - App Info: isPackageChanged called
2021-04-21 20:32:26.367 D/Runner: AdbShellRunner
2021-04-21 20:32:31.018 E/AppOpsService: Could not get app ops for UID 10693
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1973)
	at android.os.Parcel.readException(Parcel.java:1913)
	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579)
	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:78)
	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:30)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1034)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
2021-04-21 20:32:51.476 D/ADVM: Package availability changed.
```

Galaxy S7 edge
8.0.0
Debug version 1147
TCP over adb mode

**Comment by MuntashirAkon** [comment]
Fixed in 68a9f233 (by reverting the commit for now).
