### ISSUE TITLE
Unable to block trackers - App manager crash

### ISSUE THREAD

**Issue by Mtkmanjaro** [MuntashirAkon/AppManager#412]
After trying to block trackers app manager crash,  after chrash the page app info keeps loading forever, this is the output log, 

```
java.lang.SecurityException: Attempt to change component state; pid=23875, uid=10242, component=lyr.search.net/com.google.android.gms.measurement.AppMeasurementReceiver
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:7352)
    at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.setComponentEnabledSetting(PackageManagerCompat.java:100)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.applyRules(ComponentsBlocker.java:369)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.updateRulesForComponent(AppDetailsViewModel.java:291)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.lambda$applyRules$21$AppDetailsFragment(AppDetailsFragment.java:536)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsFragment$2C3qSdlz9HxGg5kXQssh3mJPsMY.run(Unknown Source:6)
    at java.lang.Thread.run(Thread.java:919)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21582)
	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:21516)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3481)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4144)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
```

Device Info:
App version: 2.6.0
App version code: 385
Android build version: eng.kenhv.20200915.184314
Android release version: 10
Android SDK version: 29
Android build ID: QQ3A.200805.001
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: vince
Device model: Redmi 5 Plus
Device product name: havoc_vince
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: es-HN
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment]
What's the UID of App Manager? `10242`?

**Comment by Mtkmanjaro** [comment]
10243

**Comment by MuntashirAkon** [comment]
So, what's in UID `10242`?

**Comment by Mtkmanjaro** [comment]
My bad i uninstalled app Manager after crash due to heavy lag on my device, so when you asked for uid i installed again and the system give 10243 Uid so 10242 is the previous installation of app Manager

**Comment by MuntashirAkon** [comment]
> My bad i uninstalled app Manager after crash due to heavy lag on my device, so when you asked for uid i installed again and the system give 10243 Uid so 10242 is the previous installation of app Manager

Thought so. The crash happens because AM was trying to block component using its own context rather than magisk/root context.

**Comment by Mtkmanjaro** [comment]
But why? Well thanks for the fast reply, i will waiting for the fix love your app, there's the weird thing after crash the app info tab is broken keep loading indefinitely, also the device become lagui i think is because some selinux police relate maybe due the app manager using its own context maybe

**Comment by MuntashirAkon** [comment]
> But why?

No idea. It's specific to some devices only, it seems. I get a lot of crash reports with similar issues but nobody came forward to actually help me resolve the issue.

I'll inform you when I need some testing.

**Comment by Mtkmanjaro** [comment]
Ok

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon 
After the app crash when trying to block trackers, all the main features become unusable for example backup and restore is broken can't do practically nothing, well at least logcat works and is a nice feature, so for me app manager 2.6 is literally broken meanwhile you find a fix the only solution is to do a downgrade, I'm ready to test if you need, thanks for the hard work mate.

**Comment by MuntashirAkon** [comment]
1. Install a debug build (you may need to restart if you've already installed a debug build)
2. Start logging using logcat (no filters)
3. Try to block trackers (it should fail)
4. Stop logging
5. Send me the logcat output

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
