### ISSUE TITLE
Crash upon tapping on uninstalled system app

### ISSUE THREAD

**Issue by skrimix** [MuntashirAkon/AppManager#440]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
AM crashes with ActivityNotFoundException after tapping on uninstalled system app while Package Installer feature is disabled.

**To Reproduce**
1. Go to Settings -> Enable/disable features
2. Disable Package Installer
3. Return to app list and uninstall a system app (I tested with Android System WebView and Android R Easter Egg)
4. Refresh list several times until AM recognizes uninstalled app
5. Click on uninstalled app
6. AM crashes

**Expected behavior**
AM shows message about disabled Package Installer or temporarily enables it automatically to reinstall app

**Screenshots**

**Crash logs**
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2065)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
    at android.app.Activity.startActivityForResult(Activity.java:5320)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
    at android.app.Activity.startActivityForResult(Activity.java:5278)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
    at android.app.Activity.startActivity(Activity.java:5664)
    at android.app.Activity.startActivity(Activity.java:5617)
    at io.github.muntashirakon.AppManager.main.MainRecyclerAdapter.lambda$onBindViewHolder$3$MainRecyclerAdapter(MainRecyclerAdapter.java:174)
    at io.github.muntashirakon.AppManager.main.-$$Lambda$MainRecyclerAdapter$f43eDB15RGNVX5IkeYSv5oDtco8.onClick(Unknown Source:6)
    at android.view.View.performClick(View.java:7448)
    at android.view.View.performClickInternal(View.java:7425)
    at android.view.View.access$3600(View.java:810)
    at android.view.View$PerformClick.run(View.java:28305)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7660)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 2.6.0
App version code: 385
Android build version: d759aec521
Android release version: 11
Android SDK version: 30
Android build ID: potato_begonia-userdebug 11 RQ2A.210505.003 d759aec521
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia
Device model: Redmi Note 8 Pro
Device product name: begonia
Device hardware name: mt6785
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
```

**Device info**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS Version: Android 11
 - App Manager Version: v2.6.0 (also present in debug v2.7.0 (1242))
 - Mode: root

**Additional context**

**Comment by MuntashirAkon** [comment]
Fixed in be3d0dff
