### ISSUE TITLE
Both App Manager and latest AM Debug crash on searching for an app

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#441]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Both App Manager and latest AM Debug crash. After the scan of the installed apps, I searched for an app (Netflix), which crashes. Typing "net" gives me a crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the app
2. And wait
3. Click search button
4. Type "net"
5. Getting crash everytime

**Expected behavior**
I cannot complete the task.

**Screenshots**

**Crash logs**
https://del.dog/cocinoonge

**Device info**
 - Device: Samsung Galaxy Tab S7+
 - OS Version: Android 11
 - App Manager Version: v2.6
 - Mode: root

**Additional context**
Could Netflix or Google Play Services installs possible culprits here?

**Comment by kgursu** [comment]
Crash report:

java.lang.IndexOutOfBoundsException: setSpan (14 ... 17) ends beyond length 16
    at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:491)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:197)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:184)
    at android.text.SpannableString.setSpan(SpannableString.java:60)
    at io.github.muntashirakon.AppManager.utils.UIUtils.getHighlightedText(UIUtils.java:64)
    at io.github.muntashirakon.AppManager.main.MainRecyclerAdapter.onBindViewHolder(MainRecyclerAdapter.java:285)
    at io.github.muntashirakon.AppManager.main.MainRecyclerAdapter.onBindViewHolder(MainRecyclerAdapter.java:63)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1655)
    at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1509)
    at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1417)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:1224)
    at android.view.View.layout(View.java:24475)
    at android.view.ViewGroup.layout(ViewGroup.java:7383)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4212)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3647)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2575)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9910)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
    at android.view.Choreographer.doCallbacks(Choreographer.java:809)
    at android.view.Choreographer.doFrame(Choreographer.java:744)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8506)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Device Info:
App version: 2.6.0
App version code: 385
Android build version: T970XXU1BUAA
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.012.T970XXU1BUAA
Device brand: samsung
Device manufacturer: samsung
Device name: gts7xlwifi
Device model: SM-T970
Device product name: gts7xlwifitur
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: tr-TR
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Should be fixed in 4e9cb6fe. Can you confirm?

**Comment by kgursu** [comment]
Yup, thank you so much... 🙂
