### ISSUE TITLE
Infinite "initializing" screen before eventually crashsing.

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#442]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

When first opening the app, it gets stuck at the "initializing" screen and crashes after a long time.

1. Open app
2. Nothing happens but infinitely "initializing" with a blank app list.
3. wait a while
4. App crashes

The app should initialize after seconds as it usually does with a full app list.

![Screenshot_20210516-060606_AM Debug.jpg](https://user-images.githubusercontent.com/43686736/118398423-66c5c800-b60d-11eb-90e2-aef80fc01e3d.jpg)

![Screenshot_20210516-060236_Niagara Launcher.jpg](https://user-images.githubusercontent.com/43686736/118398466-aab8cd00-b60d-11eb-8afb-711a3ce4a1dc.jpg)

2021-05-16 05:40:19.693 D/MVM: New instance created
2021-05-16 05:40:19.957 E/Users: Could not get list of users
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:63)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1055)
	at io.github.muntashirakon.AppManager.users.Users.getUsers(Users.java:80)
	at io.github.muntashirakon.AppManager.users.Users.getUsersHandles(Users.java:97)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:254)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:170)
	at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$FDXMpcfHZMTjLENDE7nHv1buIR0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
2021-05-16 05:40:19.962 E/PackageUtils: Could not retrieve package info list for user 0
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:63)
	at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:4831)
	at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:101)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:170)
	at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$FDXMpcfHZMTjLENDE7nHv1buIR0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
2021-05-16 05:40:20.144 D/updateInfoForPackages: packages: [com.silentlexx.ffmpeggui]
2021-05-16 05:40:33.406 D/PackageUtils: Loading apps for the first time.
2021-05-16 05:40:33.408 E/Users: Could not get list of users
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:63)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1055)
	at io.github.muntashirakon.AppManager.users.Users.getUsers(Users.java:80)
	at io.github.muntashirakon.AppManager.users.Users.getUsersHandles(Users.java:97)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:254)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
	at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
	at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
2021-05-16 05:40:33.413 E/PackageUtils: Could not retrieve package info list for user 0
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
	at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:63)
	at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:4831)
	at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:101)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
	at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
	at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
2021-05-16 05:40:33.482 D/updateInfoForPackages: packages: [com.silentlexx.ffmpeggui]

Galaxy S7 Edge
Oreo
Debug 2.7.0 #1249
Adb over TCP

**Comment by MuntashirAkon** [comment]
Logs suggest that ADB over TCP is activated but it couldn't use it (not reproducible on my Android 11). Anyway, where's the crashlog?

**Comment by BloodReleasesPain** [comment]
> Logs suggest that ADB over TCP is activated but it couldn't use it (not reproducible on my Android 11). Anyway, where's the crashlog?

How do I get one? I thought the one I gave from the app had what caused the crash as well. One thing I should point out is that this is after a reboot and was supaposed to give me the windows asking me to trust the adb from my computer but I don't even get that. I went to a previous build from I think around a week ago and I got the windows I needed to complete "initializing", upgraded back to latest debug build, and everything is fine until you reboot and it gets stuck again when the phone needs permission from the computer. I guess I could do trial and error to see exactly which build started the problem.

**Comment by MuntashirAkon** [comment]
> everything is fine until you reboot and it gets stuck again when the phone needs permission from the computer.

If you restart your device, you have to run `adb tcpip 555` again.

**Comment by BloodReleasesPain** [comment]
> > everything is fine until you reboot and it gets stuck again when the phone needs permission from the computer.
> 
> If you restart your device, you have to run `adb tcpip 555` again.

Yes I'm aware. I always do that. All other apps work fine when it asks to trust the computer as well as previous versions of this app. These current builds won't give me the prompts I need in order to give adb permissions. I don't know if the app still thinks the credentials from the previous boot are valid (which they aren't, I have to reconnect through adb every reboot) or what.

**Comment by MuntashirAkon** [comment]
Fixed in 0bde5606

**Comment by BloodReleasesPain** [comment]
> Fixed in 0bde5606

I don't know if I should create a new issue because this one is now closed but I will if this gets no response. The app no longer crashes and will now run in rootless/adbless mode but the app still refuses to even check or attempt to complete the adb connection. 

Here's a log.

2021-05-17 10:35:30.389 W/KSManager: Using keystore BKS
2021-05-17 10:35:30.401 I/CompatUtil: Loading local protection key
2021-05-17 10:35:30.410 I/CompatUtil: AES local protection key found in keystore
2021-05-17 10:35:30.912 D/IPC: Init: Local server
2021-05-17 10:35:30.936 E/ADB
android.os.RemoteException: AMService not running.
	at io.github.muntashirakon.AppManager.ipc.IPCUtils$AMServiceConnectionWrapper.getServiceSafe(IPCUtils.java:185)
	at io.github.muntashirakon.AppManager.ipc.IPCUtils$AMServiceConnectionWrapper.getAmService(IPCUtils.java:171)
	at io.github.muntashirakon.AppManager.ipc.IPCUtils.getAmService(IPCUtils.java:44)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.launchAmService(LocalServer.java:56)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.getInstance(LocalServer.java:46)
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.autoDetectRootOrAdb(RunnerUtils.java:152)
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.setModeOfOps(RunnerUtils.java:186)
	at io.github.muntashirakon.AppManager.crypto.AuthenticationActivity.lambda$handleModeOfOps$1$AuthenticationActivity(AuthenticationActivity.java:63)
	at io.github.muntashirakon.AppManager.crypto.-$$Lambda$AuthenticationActivity$93HUeU6yW43f6Muu5s9-PlJQrSc.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
2021-05-17 10:35:31.734 D/MVM: New instance created
2021-05-17 10:35:32.179 E/Users: Could not get list of users
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1056)
	at io.github.muntashirakon.AppManager.users.Users.getUsers(Users.java:65)
	at io.github.muntashirakon.AppManager.users.Users.getUsersHandles(Users.java:82)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:239)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:155)
	at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$FDXMpcfHZMTjLENDE7nHv1buIR0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

**Comment by MuntashirAkon** [comment]
> I don't know if I should create a new issue because this one is now closed but I will if this gets no response. The app no longer crashes and will now run in rootless/adbless mode but the app still refuses to even check or attempt to complete the adb connection.

Try 09d55d86. It seems that older phones have tight restrictions on how ADB can be used.

**Comment by BloodReleasesPain** [comment]
> > I don't know if I should create a new issue because this one is now closed but I will if this gets no response. The app no longer crashes and will now run in rootless/adbless mode but the app still refuses to even check or attempt to complete the adb connection.
> 
> Try 09d55d86. It seems that older phones have tight restrictions on how ADB can be used.

Can you put this Verizon on the debug channel in telegram?

**Comment by MuntashirAkon** [comment]
> Can you put this Verizon on the debug channel in telegram?

Try downloading it from GitHub actions.
