### ISSUE TITLE
Unable to select applications ("App not installed")

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#476]
First of all, thank you for fixing bug 140/167/298. I now see all of the apps. :)

**Device info**
- Device: Samsung Galaxy Tab 2
- OS Version: LineageOS 13.0-20180211-NIGHTLY-espressowifi
- App Manager Version: 2.6.1 (387)
- Mode: root

- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Unfortunately, this happens only intermittently (most of the time, but not always). I believe I have a log capture of when it happened. When I select an app in app manager, I see either "Could not fetch package infor" or "App not installed." App Manager then returns to the list of apps. No other application that interacts with packages has this problem.

**Crash logs**

App Manager did crash once due to this (but I managed to mishit a button, and lost those logs :( ). I have a log of the usual behavior (when I see the message, and App Manager returns to the llist of apps.

```
[06-12 09:52:58.039 137:171 E/BufferQueueProducer]
[io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity] allocateBuffers: slot 2 without buffer is not FREE

[06-12 09:53:05.819 12343:15549 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=14

[06-12 09:53:05.903 12343:12379 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=14

[06-12 09:53:06.028 12343:12363 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=14

[06-12 09:53:06.080 12343:12365 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=14

[06-12 09:53:06.170 12343:8506 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=14

[06-12 09:53:07.754 471:6166 I/ActivityManager]
START u0 {cmp=io.github.muntashirakon.AppManager/.details.AppDetailsActivity (has extras)} from uid 10171 on display 0

[06-12 09:53:07.970 12343:12379 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.089 12343:12379 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)

[06-12 09:53:08.091 12343:12379 E/JavaBinder]
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:132)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:106)
        at android.os.Binder.execTransact(Binder.java:453)

[06-12 09:53:08.092 12343:12363 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.279 12343:12365 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.304 12343:1628 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.314 12343:12367 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.340 12343:8899 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.348 15554:15811 W/art]
Long monitor contention event with owner method=void io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackageName$3$AppDetailsViewModel(java.lang.String) from AppDetailsViewModel.java:198 waiters=1 for 279ms

[06-12 09:53:08.349 15554:15812 W/art]
Long monitor contention event with owner method=void io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackageName$3$AppDetailsViewModel(java.lang.String) from AppDetailsViewModel.java:198 waiters=2 for 258ms

[06-12 09:53:08.350 12343:15549 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.356 471:490 I/ActivityManager]
Displayed io.github.muntashirakon.AppManager/.details.AppDetailsActivity: +585ms

[06-12 09:53:08.357 12343:12365 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.361 12343:8506 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.622 12343:8506 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)

[06-12 09:53:08.623 12343:8506 E/JavaBinder]
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:132)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:106)
        at android.os.Binder.execTransact(Binder.java:453)

[06-12 09:53:08.626 12343:8899 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.626 137:137 W/SurfaceFlinger]
couldn't log to binary event log: overflow.

[06-12 09:53:08.642 12343:15549 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)

[06-12 09:53:08.644 12343:15549 E/JavaBinder]
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:132)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:106)
        at android.os.Binder.execTransact(Binder.java:453)

[06-12 09:53:08.645 12343:8506 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.656 12343:12365 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)

[06-12 09:53:08.657 12343:12365 E/JavaBinder]
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:132)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:106)
        at android.os.Binder.execTransact(Binder.java:453)

[06-12 09:53:08.658 12343:15549 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.908 15554:15808 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 288)

[06-12 09:53:08.908 15554:15808 W/System.err]
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

[06-12 09:53:08.909 15554:15808 W/System.err]
        at android.os.BinderProxy.transactNative(Native Method)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at android.os.BinderProxy.transact(Binder.java:503)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:57)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2247)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:107)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:786)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPackageInfo(AppDetailsViewModel.java:839)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$setPackage$2$AppDetailsViewModel(AppDetailsViewModel.java:167)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$UfhyR2xVfIa2-hnR4epy60V5Q_I.run(lambda)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

[06-12 09:53:08.909 15554:15808 W/System.err]
        at java.lang.Thread.run(Thread.java:818)

[06-12 09:53:08.931 471:482 W/ActivityManager]
Duplicate finish request for ActivityRecord{9d8c14 u0 io.github.muntashirakon.AppManager/.details.AppDetailsActivity t583 f}

[06-12 09:53:08.949 15554:15812 E/JavaBinder]
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 288)

[06-12 09:53:08.949 15554:15812 W/System.err]
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

[06-12 09:53:08.951 15554:15812 W/System.err]
        at android.os.BinderProxy.transactNative(Native Method)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at android.os.BinderProxy.transact(Binder.java:503)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:57)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2247)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:107)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:786)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPackageInfo(AppDetailsViewModel.java:839)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadActivities(AppDetailsViewModel.java:914)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$nptXYDsatLObZChw-_K7I1obpcY(AppDetailsViewModel.java)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$nptXYDsatLObZChw-_K7I1obpcY.run(lambda)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

[06-12 09:53:08.951 15554:15812 W/System.err]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

[06-12 09:53:08.952 15554:15812 W/System.err]
        at java.lang.Thread.run(Thread.java:818)

[06-12 09:53:08.956 12343:12365 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:08.997 12343:8899 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:09.005 12343:1628 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:09.027 12343:12367 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:09.035 12343:8506 D/IPC]
transact: uid=10171, descriptor=android.content.pm.IPackageManager, code=3

[06-12 09:53:09.115 12343:12379 D/IPC]
transact: uid=10171, descriptor=com.android.internal.app.IAppOpsService, code=12

[06-12 09:53:09.295 15554:15564 I/art]
Background partial concurrent mark sweep GC freed 172256(10MB) AllocSpace objects, 6(3MB) LOS objects, 22% free, 13MB/17MB, paused 1.647ms total 297.912ms

[06-12 09:53:10.057 15554:15554 I/Choreographer]
Skipped 48 frames!  The application may be doing too much work on its main thread.

java.io.InterruptedIOException
        at com.topjohnwu.superuser.internal.TaskImpl.run(TaskImpl.java:74)
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:229)
        at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:62)
        at com.topjohnwu.superuser.internal.JobImpl.exec(JobImpl.java:81)
        at com.topjohnwu.superuser.internal.PendingJob.exec(PendingJob.java:54)
        at io.github.muntashirakon.AppManager.runner.RootShellRunner.runCommand(RootShellRunner.java:21)
        at io.github.muntashirakon.AppManager.runner.Runner.run(Runner.java:205)
        at io.github.muntashirakon.AppManager.runner.Runner.runCommand(Runner.java:163)
        at io.github.muntashirakon.AppManager.runner.Runner.runCommand(Runner.java:129)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.getHiddenCodePathOrDefault(PackageUtils.java:676)
        at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadTagCloud(AppInfoViewModel.java:112)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1398)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(AppInfoFragment.java)
        at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$oxlKbqiAsxIkEG69gntC-jrgnXk.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:391)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.topjohnwu.superuser.internal.TaskImpl.run(TaskImpl.java:71)
        ... 18 more
```

**Comment by MuntashirAkon** [comment]
The following seems to be the real culprit. I don't know what is causing it though. The parcel size isn't very large either.

```
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 288)
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:57)
        at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2247)
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:107)
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackageInfo(AppDetailsViewModel.java:786)
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPackageInfo(AppDetailsViewModel.java:839)
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadActivities(AppDetailsViewModel.java:914)
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$nptXYDsatLObZChw-_K7I1obpcY(AppDetailsViewModel.java)
        at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$nptXYDsatLObZChw-_K7I1obpcY.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

The following is not important. It's part of the interruption of the background processes due to app info page being exiting.

```
java.io.InterruptedIOException
        at com.topjohnwu.superuser.internal.TaskImpl.run(TaskImpl.java:74)
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:229)
        at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:62)
        at com.topjohnwu.superuser.internal.JobImpl.exec(JobImpl.java:81)
        at com.topjohnwu.superuser.internal.PendingJob.exec(PendingJob.java:54)
        at io.github.muntashirakon.AppManager.runner.RootShellRunner.runCommand(RootShellRunner.java:21)
        at io.github.muntashirakon.AppManager.runner.Runner.run(Runner.java:205)
        at io.github.muntashirakon.AppManager.runner.Runner.runCommand(Runner.java:163)
        at io.github.muntashirakon.AppManager.runner.Runner.runCommand(Runner.java:129)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.getHiddenCodePathOrDefault(PackageUtils.java:676)
        at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadTagCloud(AppInfoViewModel.java:112)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1398)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(AppInfoFragment.java)
        at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$oxlKbqiAsxIkEG69gntC-jrgnXk.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:391)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.topjohnwu.superuser.internal.TaskImpl.run(TaskImpl.java:71)
        ... 18 more
```

**Comment by MuntashirAkon** [comment]
Could you do that same but with the debug builds?

**Comment by 2011** [comment]
I have the latest debug build downloaded. Will install and report back in a day or two.

**Comment by 2011** [comment]
Let's see if I can sort this out. :) First of all, I think I have the logs from the time that it crashed a couple of weeks ago (I didn't know that I could still access those).

```
[06-12 11:03:57.386 15554:19303 E/AndroidRuntime]
FATAL EXCEPTION: PackageChangeReceiver
Process: io.github.muntashirakon.AppManager, PID: 15554
Theme: themes:{}
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@e4fd336 rejected from java.util.concurrent.ThreadPoolExecutor@c1b9237[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 18]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setIsPackageChanged(AppDetailsViewModel.java:727)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$PackageIntentReceiver.onPackageChanged(AppDetailsViewModel.java:1465)
    at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:103)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

On to today, I did not see any special log files created (let me know if I need to change a setting for that). I hope I captured what you need. Thank you again.

[io.github.muntashirakon.AppManager.debug_1344.log.zip](https://github.com/MuntashirAkon/AppManager/files/6699013/io.github.muntashirakon.AppManager.debug_1344.log.zip)

**Comment by MuntashirAkon** [comment]
> [io.github.muntashirakon.AppManager.debug_1344.log.zip](https://github.com/MuntashirAkon/AppManager/files/6699013/io.github.muntashirakon.AppManager.debug_1344.log.zip)

I don't understand. Binder communication seems to be too unreliable in your Android version. The failures seem to be very random.

**Comment by lshilshi** [comment]
@MuntashirAkon When I open the App Details page for HMS(com.huawei.hwid) , not most of the time, but none of them can be opened.
Below is the corresponding log file, but no useful information can be seen.
[2021-08-05-11-30-44.log](https://github.com/MuntashirAkon/AppManager/files/6935763/2021-08-05-11-30-44.log)
[device_info.txt](https://github.com/MuntashirAkon/AppManager/files/6935764/device_info.txt)
[dmesg.txt](https://github.com/MuntashirAkon/AppManager/files/6935765/dmesg.txt)

**Comment by lshilshi** [comment]
When I open the App Details page for HMS(com.huawei.hwid) , toast as "app not installed", and jump back to the main page.

**Comment by MuntashirAkon** [comment]
A possible duplicate of #526. Please try out the latest debug build to see if you can still reproduce the issue.

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
