### ISSUE TITLE
remove rules - crash

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#482]
Got this error when trying to remove rules on an app

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3e2691f rejected from java.util.concurrent.ThreadPoolExecutor@68646c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 139]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setIsPackageChanged(AppDetailsViewModel.java:689)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$PackageIntentReceiver.onPackageChanged(AppDetailsViewModel.java:1374)
    at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:108)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:233)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.5.24-PRE
App version code: 383
Android build version: 2105071656
Android release version: 11
Android SDK version: 30
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by fusionneur** [comment]
what is unsupported?

**Comment by MuntashirAkon** [comment]
> what is unsupported?

2.5.24 is no longer supported. Use 2.6.0 or later.
