### ISSUE TITLE
Net Policy Crashed

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#483]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
change net policy of wireless setting app will auto crash 

**To Reproduce**
Steps to reproduce the behaviour:
1. open AM and find wireless setting apps
2. Click that app and try change the net policy
3. AM will crash but instantly take me back to main menu

**Expected behavior**
it should work

**Screenshots**

**Crash logs**
```
java.lang.IllegalArgumentException: cannot apply policy to UID 1000
    at android.os.Parcel.createException(Parcel.java:2091)
    at android.os.Parcel.readException(Parcel.java:2055)
    at android.os.Parcel.readException(Parcel.java:2003)
    at android.net.INetworkPolicyManager$Stub$Proxy.setUidPolicy(INetworkPolicyManager.java:578)
    at io.github.muntashirakon.AppManager.servermanager.NetworkPolicyManagerCompat.setUidPolicy(NetworkPolicyManagerCompat.java:36)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$onOptionsItemSelected$20$AppInfoFragment(AppInfoFragment.java:456)
    at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$GhDZFUXxSUY94wl46ox41RfCDLI.onClick(Unknown Source:4)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:238)
    at android.app.ActivityThread.main(ActivityThread.java:7853)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.net.NetworkPolicyManagerService.setUidPolicy(NetworkPolicyManagerService.java:2697)
	at android.net.INetworkPolicyManager$Stub.onTransact(INetworkPolicyManager.java:279)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Device Info**
App version: 2.6.0
App version code: 385
Android build version: 1608537052
Android release version: 10
Android SDK version: 29
Android build ID: RMX2030EX_11_C.67
Device brand: realme
Device manufacturer: realme
Device name: RMX2030
Device model: RMX2030
Device product name: RMX2030
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: id-ID
In-App Language: auto
Mode: adb

**Device info**
 - Device: Realme 5i
 - OS Version: Android 10 Realme UI 1.0 
 - App Manager Version: 2.6.0
 - Mode: adb

**Additional context**
disclaimer idk this AM bug or caused by android system restriction and based on my test this bug happend only on this app.

**Comment by MuntashirAkon** [comment]
> disclaimer idk this AM bug or caused by android system restriction and based on my test this bug happened only on this app.

UID < 10000 are system/vendor reserved and cannot be changed.

**Comment by NSTAdventure** [comment]
> > disclaimer idk this AM bug or caused by android system restriction and based on my test this bug happened only on this app.
> 
> UID < 10000 are system/vendor reserved and cannot be changed.

🤦🤦🤦🤦🤦

then can you disable net policy option for that UID?
