### ISSUE TITLE
Permission changes won't apply

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#498]
- [ X] I know what my device, OS and App Manager versions are
- [ X] I know how to take logs
- [ X] I know how to reproduce the issue which may not be specific to my device

When changing permissions, they won't apply and reset back to where they were after a refresh despite working ADB permissions.

Logs:

2021-07-01 09:03:33.729 W/KSManager: Using keystore BKS 2021-07-01 09:03:33.736 I/CompatUtil: Loading local protection key 2021-07-01 09:03:33.741 I/CompatUtil: AES local protection key found in keystore 2021-07-01 09:03:34.078 E/ADB: ADB available 2021-07-01 09:03:34.097 D/IPC: Init: Local server 2021-07-01 09:03:34.118 D/LocalServerManager: useAdbStartServer: opening shell... 2021-07-01 09:03:34.349 E/LocalServerManager: classpath --> /data/user_de/0/io.github.muntashirakon.AppManager.debug/am.jar 2021-07-01 09:03:34.351 E/LocalServerManager: exec path --> /data/user_de/0/io.github.muntashirakon.AppManager.debug/run_server.sh 2021-07-01 09:03:34.354 D/LocalServerManager: useAdbStartServer: sh /data/user_de/0/io.github.muntashirakon.AppManager.debug/run_server.sh 60001 abb77c78356598757b6a97d4ac291918 2021-07-01 09:03:37.356 D/LocalServerManager: useAdbStartServer: Server has started. 2021-07-01 09:03:37.385 D/IPCUtils: Launching service... 2021-07-01 09:03:37.390 D/IPC: Total bound services: 0 2021-07-01 09:03:37.392 D/IPC: Need to start a new connection. 2021-07-01 09:03:37.406 E/IPC: Running service starter script... 2021-07-01 09:03:37.449 D/AdbShell - Command: cp /data/user_de/0/io.github.muntashirakon.AppManager.debug/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer)& 2021-07-01 09:03:37.451 D/AdbShell - Stdout: 2021-07-01 09:03:37.452 D/AdbShell - Return Code: 0 2021-07-01 09:03:38.402 D/IPCUtils: service onServiceConnected 2021-07-01 09:03:38.403 D/IPCUtils: service onResponseReceived 2021-07-01 09:03:39.074 D/MVM: New instance created 2021-07-01 09:03:54.464 D/Cache: Deleted 0 images. 2021-07-01 09:03:56.570 D/ADVM: New constructor called. 2021-07-01 09:03:56.719 D/ADVM: Package name is being set 2021-07-01 09:03:56.720 D/ADVM: Package name is being set for io.github.muntashirakon.AppManager.debug 2021-07-01 09:03:57.045 E/ADA - App Info: isPackageChanged called 2021-07-01 09:03:57.100 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764) 2021-07-01 09:03:57.202 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764) 2021-07-01 09:03:57.332 D/Runner: AdbShellRunner 2021-07-01 09:04:01.859 D/ADVM: Package availability changed. 2021-07-01 09:04:01.862 D/updateInfoForPackages: packages: [com.android.printspooler, com.termux.window, com.samsung.android.app.aodservice, com.draco.ssh, org.codeaurora.btmultisim, com.samsung.android.mobileservice, com.dsi.ant.service.socket, com.samsung.android.app.mirrorlink, com.samsung.android.bbc.fileprovider, com.samsung.sec.android.application.csc, com.draco.anyhome, games.paveldogreat.fluidsim, es.smvarela.nukeblast, com.android.wallpaper.livepicker, com.sec.bcservice, com.sec.android.app.launcher, com.android.providers.telephony, com.google.android.partnersetup, com.google.android.talk, com.google.android.tts, com.sec.android.provider.emergencymode, com.google.android.ext.shared, com.android.cts.ctsshim, com.samsung.android.dlp.service, com.samsung.android.coreapps, com.android.mtp, com.samsung.clipboardsaveservice, com.aurora.store.nightly, com.samsung.android.soundassistant, com.samsung.android.app.memo, com.gmail.heagoo.apkeditor.pro, com.samsung.android.asksmanager, com.knox.vpn.proxyhandler, com.ironzog.rvtournament, com.tmobile.pr.adapt, com.android.carrierdefaultapp, com.samsung.android.sm, partl.atomicclock, com.wsomacp, dk.appdictive.blurwallpaper, com.sec.android.app.camera.shootingmode.beauty, com.samsung.android.email.provider, com.samsung.android.svcagent, com.samsung.android.app.taskedge, com.dsi.ant.server, com.samsung.enhanceservice, com.lookout, com.android.companiondevicemanager, com.samsung.android.MtpApplication, com.sec.enterprise.mdm.vpn, com.samsung.android.incallui, com.jundroo.SimplePlanes, com.one.ui.dark.s10.iconpack, com.aurora.store, org.torproject.torservices, com.samsung.android.intelligenceservice2, com.wssyncmldm, com.wssnps, com.samsung.android.calendar, com.samsung.android.app.withtv, com.schindlerdavid.statify, com.sec.android.widgetapp.easymodecontactswidget, com.samsung.android.contacts, com.android.shell, dentex.youtube.downloader, com.termux.api, com.abstractart.music_racer, com.sec.ims, com.samsung.ucs.agent.ese, com.vkontakte.android, com.android.providers.userdictionary, com.google.android.feedback, com.samsung.android.app.accesscontrol, com.trustonic.tuiservice, com.sec.android.app.hwmoduletest, com.qualcomm.wfd.service, com.google.android.webview, com.samsung.dcmservice, com.google.android.printservice.recommendation, com.samsung.tmowfc.wfcpref, com.samsung.android.app.appsedge, com.samsung.android.lool, com.android.externalstorage, com.samsung.android.app.color, com.qualcomm.qti.services.secureui, com.samsung.svoice.sync, com.sec.epdgtestapp, com.hiya.star, com.draco.buoy, com.samsung.android.networkdiagnostic, com.android.keychain, com.android.managedprovisioning, com.samsung.app.highlightplayer, com.sec.android.app.personalization, com.sec.imsservice, com.samsung.aasaservice, com.samsung.oh, com.samsung.android.fmm, com.samsung.android.knox.containercore, com.google.android.apps.docs, joshuatee.wx, com.samsung.android.tvplus, com.samsung.android.sdk.professionalaudio.utility.jammonitor, com.termux.styling, org.torproject.android, org.billthefarmer.currency, com.sec.android.RilServiceModeApp, com.draco.anyassistant, com.spotify.music, com.google.android.videos, com.sec.android.soagent, com.samsung.android.gametuner.thin, com.samsung.android.sdk.professionalaudio.app.audioconnectionservice, com.sec.vsim.ericssonnsds.webapp, com.sec.enterprise.knox.cloudmdm.smdms, com.sec.phone, com.android.proxyhandler, com.sec.android.app.sbrowser, com.sec.automation, com.mobeam.barcodeService, com.qualcomm.atfwd, com.sec.mldapchecker, com.sec.android.app.samsungapps, com.ultrak.heagoo.apkbuilder.pro, com.samsung.android.svoice, com.sec.android.diagmonagent, com.samsung.android.location, com.sec.android.app.bluetoothtest, com.samsung.klmsagent, ru.cjwqbpwq.nhycdlmir, com.silentlexx.sohowrapper, com.draco.cachie, com.android.htmlviewer, com.google.android.configupdater, flipboard.boxer.app, com.samsung.android.app.talkback, com.samsung.android.themestore, vn.remove.photo.content, com.jndapp.square.nexa.iconpack, com.qualcomm.svi, com.rootify.emptyfoldercleaner, com.sec.android.AutoPreconfig, com.samsung.android.spay, com.sec.android.app.vepreload, com.draco.comatose, com.qualcomm.cabl, com.xda.labs.play, com.elitecyberdevs.webcode, com.mixplorer.beta, com.mirfatif.permissionmanagerx, com.jundroo.simplerockets, com.htetznaing.fonttools, com.sec.android.app.magnifier, com.samsung.tmowfc.wfccontroller, agk.wissamhbooss.colorpicker, salt.soup.smob, com.hancom.office.editor.hidden, com.dominospizza, com.sec.android.app.clockpackage, com.samsung.networkui, com.qualcomm.uimremoteclient, com.samsung.android.widgetapp.yahooedge.finance, com.google.android.gsf, pl.revanmj.toastsource, com.google.android.apps.maps, com.StefMorojna.SpaceflightSimulator, com.samsung.android.app.camera.sticker.stamp.preload, com.sec.android.app.wlantest, com.qualcomm.qti.auth.fidocryptoservice, com.aurora.wallpapers, mega.privacy.android.app, com.google.android.googlequicksearchbox, com.android.statementservice, org.fdroid.fdroid, com.google.android.play.games, com.htetznaing.zfont2, com.msiejak.msiejak.phoenix, com.android.bips, com.samsung.android.app.galaxyfinder, com.samsung.android.personalpage.service, com.koo.lightmanagerpro, io.github.muntashirakon.setedit, com.gsamlabs.bbm.pro, com.samsung.android.smartmirroring, com.sec.android.providers.security, com.monotype.android.font.chococooky, com.sec.android.emergencylauncher, com.simplemobiletools.thankyou, com.silicondroid.hexen, com.mixplorer.addon.autotag, com.osp.app.signin, fr.monoqle.looq, com.rowlhouse.picasimdonate, com.google.android.onetimeinitializer, com.overwolf.statsroyale, com.samsung.android.timezone.autoupdate_O, com.qualcomm.timeservice, com.imgur.mobile, com.samsung.android.app.cocktailbarservice, com.android.settings, com.samsung.android.allshare.service.fileshare, com.samsung.storyservice, com.sec.android.splitsound, com.flickr.android, com.google.android.setupwizard, com.samsung.android.messaging, org.simalliance.openmobileapi.service, com.android.apps.tag, io.github.muntashirakon.AppManager, com.paget96.netspeedindicator, com.samsung.android.app.motionpanoramaviewer, com.android.egg, file.observer, apps.r.barometer, com.sec.android.provider.badge, com.github.axet.torrentclient, com.samsung.android.authfw, com.cyberlink.powerdirector.DRA140225_01, com.sec.android.app.safetyassurance, com.sec.enterprise.knox.attestation, com.google.android.syncadapters.calendar, com.android.providers.calendar, com.samsung.android.fingerprint.service, com.forrestguice.suntimescalendars, com.samsung.android.app.soundpicker, com.sec.svoice.lang.en_US, com.sec.android.app.camera.shootingmode.animatedgif, com.sec.android.widgetapp.samsungapps, io.github.muntashirakon.unapkm, ru.maximoff.apktool.unapkm, com.android.server.telecom, com.samsung.android.game.gametools, com.github.android, com.android.chrome, com.sec.factory.camera, com.samsung.android.smartface, com.facebook.services, com.samsung.knox.securefolder.setuppage, com.gputreats.orbitalexplorer, com.rubenmayayo.reddit, com.mixplorer.addon.tagger, com.samsung.android.da.daagent, com.android.wallpapercropper, com.kiwibrowser.browser, com.sec.location.nsflp2, com.samsung.android.mdm, com.sec.factory, ch.publisheria.bring, net.sourceforge.opencamera, lockcamera.blockcamera.disablecamera, com.dv.adm, website.leifs.delta, com.samsung.android.securitylogagent, com.draco.nom, com.silentlexx.ffmpeggui, com.sec.android.app.DataCreate, com.samsung.android.app.sbrowseredge, com.sec.android.app.camera.shootingmode.panorama3d, com.draco.netthrottle, com.kylecorry.trail_sense, com.android.providers.downloads, com.adguard.android, com.monotype.android.font.foundation, com.jarsilio.android.scrambledeggsif, com.sec.android.app.parser, com.sec.android.app.soundalive, com.android.providers.downloads.ui, eu.thedarken.sdm, com.appsisle.developerassistant, com.brit.swiftinstaller, com.android.providers.blockednumber, com.samsung.android.shortcutbackupservice, com.samsung.android.sdk.handwriting, com.samsung.android.clipboarduiservice, com.microsoft.xboxone.smartglass.beta, com.samsung.android.app.watchmanagerstub, com.sec.android.app.myfiles, com.android.storagemanager, com.samsung.android.scloud, com.sec.android.service.health, com.gd.mobicore.pa, com.ninetwozero.bf4intel, com.samsung.android.app.simplesharing, org.videolan.vlc, com.policydm, com.android.pacprocessor, com.samsung.safetyinformation, com.samsung.faceservice, com.flamefrontstudios.forzatune7, com.sec.android.app.servicemodeapp, com.samsung.android.ststub, com.room408design.XboxDVRHub, com.enhance.gameservice, org.hamware.sdo.wallpaper, com.oF2pks.classyshark3xodus, com.sec.android.app.ringtoneBR, tw.firemaples.onscreenocr, com.sec.android.easyMover.Agent, com.bryanwalsh.redditwallpaper2, com.mixplorer.addon.archive, com.samsung.android.SettingsReceiver, air.kukulive.mailnow, com.samsung.ucs.agent.boot, org.zwanoo.android.speedtest, com.sec.enterprise.mdm.services.simpin, com.google.android.apps.photos, com.tmobile.pr.mytmobile, com.android.documentsui, com.samsung.android.widgetapp.yahooedge.sport, com.samsung.android.oneconnect, com.android.nfc, com.tmobile.vvm.application, io.github.muntashirakon.AppManager.debug, com.android.bookmarkprovider, com.draco.ease, com.discord, com.vanced.manager, com.sec.spp.push, com.android.emergency, com.sec.app.RilErrorNotifier, com.github.cvzi.screenshottile, com.samsung.helphub, kr.co.nowcom.mobile.afreeca, com.samsung.android.app.interactivepanoramaviewer, com.samsung.android.bbc.bbcagent, com.android.location.fused, ru.maximoff.sheller, com.difftool, com.andrewkhandr.aspect, com.android.dreams.basic, com.facebook.system, com.sec.android.inputmethod, com.facebook.katana, com.sec.android.emergencymode.service, me.piebridge.brevent, com.samsung.app.newtrim, com.sec.android.mimage.photoretouching, com.samsung.ipservice, com.samsung.android.app.smartcapture, com.samsung.android.provider.filterprovider, net.countrymania.morse, com.maxmpz.audioplayer.unlock, com.sem.factoryapp, com.samsung.upsmtheme, com.samsung.android.app.assistantmenu, com.sec.android.fido.uaf.client, com.sec.android.app.shealth, com.aurora.adroid, com.google.android.apps.translate, com.samsung.android.samsungpass, apps.r.compass, com.dirgtrats.endlessatc, com.android.bluetoothmidiservice, com.mixplorer.addon.image, com.samsung.android.universalswitch, com.android.carrierconfig, it.mirko.beta, com.mgoogle.android.gms, phone.science.AsteroidAlert, com.android.captiveportallogin, com.sec.android.app.camera, com.samsung.mlp, org.ligi.survivalmanual, com.samsung.android.app.selfmotionpanoramaviewer, com.adguard.vpn, com.sec.vsimservice, com.samsung.android.themecenter, com.samsung.android.provider.stickerprovider, com.mixplorer.addon.smb, com.android.vending.licensing.ILicensingService, com.samsung.android.video, com.mixplorer.addon.signer, com.dsi.ant.sample.acquirechannels, com.sec.epdg, bitpit.launcher, com.samsung.android.providers.context, com.google.android.apps.paidtasks, com.samsung.app.slowmotion, com.samsung.android.app.filterinstaller, com.zacharee1.systemuituner, com.samsung.android.service.peoplestripe, com.draco.tagsh, com.samsung.android.app.notes, com.sec.android.app.popupcalculator, ru.maximoff.apktool, id.begal.channelthebegal, com.mediafire.android, partl.unsplashed, android, com.android.vending.billing.InAppBillingService.BINN, com.samsung.android.voicewakeup, com.whitepages.nameid.tmobile, com.draco.nolauncher, com.google.android.gms, com.vanced.android.youtube, com.walmart.android, com.walmart.beta, com.samsung.android.allshare.service.mediashare, com.mixplorer.addon.pdf, org.hlwd.bible, com.google.android.ext.services, com.acmeaom.android.myradar, com.sec.android.fido.uaf.asm, com.sec.sve, com.android.bluetooth, com.samsung.knox.securefolder, com.samsung.android.spayfw, com.sec.android.app.camera.shootingmode.dual, com.traversient.pictrove2.free, com.draco.immersive, com.google.android.apps.authenticator2, com.andrewkhandr.aspectpro, com.google.android.music, com.skms.android.agent, com.sec.android.ofviewer, com.gmail.heagoo.filemon, eu.thedarken.sdm.unlocker, com.android.defcontainer, com.sec.android.app.SecSetupWizard, com.jundroo.SimpleRockets2, com.merkuryinnovations.geeni, com.sec.android.app.applinker, com.samsung.tmovvm, com.samsung.android.beaconmanager, com.samsung.android.app.clipboardedge, com.samsung.android.hmt.vrsvc, com.google.android.packageinstaller, com.paget96.batteryguru, com.draco.tempo, com.termux, com.envy.guilt.icons, com.samsung.cmh, com.draco.purr, com.samsung.SMT, com.samsung.voiceserviceplatform, com.google.android.apps.walletnfcrel, com.sec.android.app.chromecustomizations, com.android.dreams.phototable, com.samsung.android.drivelink.stub, com.sec.android.app.apex, com.dsi.ant.plugins.antplus, eu.flatworld.android.sdoviewer, com.sec.knox.bluetooth, com.samsung.android.smartcallprovider, com.sec.android.app.factorykeystring, net.redwarp.gifwallpaper, com.android.providers.contacts, com.sec.android.app.camera.shootingmode.sports, com.samsung.android.samsungpassautofill, com.android.sharedstoragebackup, com.maxmpz.audioplayer, com.lonict.android.subwooferbass, com.android.vpndialogs, com.sec.android.app.billing, com.samsung.android.app.mhswrappertmo, com.kimcy929.screenrecorder, com.sec.android.daemonapp, com.sec.hearingadjust, com.cnn.mobile.android.phone.edgepanel, com.samsung.android.stickercenter, com.sec.svoice.lang.es_US, com.chrome.canary, com.sec.android.gallery3d.panorama360view, com.mixplorer.addon.metadata, com.zhiliaoapp.musically, ch.rmy.android.http_shortcuts, com.android.providers.settings, com.amazon.mShop.android, com.android.systemui, com.tmobile.simlock, com.physphil.android.unitconverterultimate, org.xphnx.ameixa, com.qualcomm.location, com.samsung.advp.imssettings, com.samsung.android.knox.containeragent, com.samsung.android.communicationservice, org.thunderdog.challegram, org.mediainfo.android.app, com.samsung.android.weather, com.samsung.app.jansky, newfree.poweramp.vis, com.sec.android.app.camera.shootingmode.rearcamselfie, com.samsung.android.mateagent, jp.danball.powdergameviewer, com.samsung.android.rubin.app, com.android.backupconfirm, com.sec.android.gallery3d, com.sec.android.app.dictionary, com.samsung.android.app.multiwindow, com.draco.powerbuttonsettings, com.samsung.android.widgetapp.briefing, com.monotype.android.font.rosemary, com.dafftin.android.moon_phase, com.samsung.android.keyguardwallpaperupdator, com.android.phone, com.minma.icon.free, com.facebook.appmanager, com.android.mms.service, com.draco.mfstrim, com.sec.usbsettings, com.qualcomm.uimremoteserver, com.samsung.android.bluelightfilter, com.mixplorer.addon.codecs, com.android.inputdevices, com.sec.enterprise.knox.shareddevice.keyguard, com.android.calllogbackup, com.android.providers.partnerbookmarks, com.envy.agony.icons, com.qti.confuridialer, com.emanuelef.remote_capture, com.sec.android.uibcvirtualsoftkey, com.android.vending, com.samsung.android.game.gamehome, com.georgie.pi, com.android.wallpaperbackup, com.android.providers.media, com.android.stk, com.forrestguice.suntimeswidget, com.bandcamp.android, org.wikipedia.beta, com.google.android.youtube, com.samsung.android.provider.shootingmodeprovider, com.supercell.clashroyale, com.sec.android.preloadinstaller, com.google.android.backuptransport, com.sec.hiddenmenu, com.samsung.android.widgetapp.yahooedge.news, com.sec.android.app.quicktool, com.simplemobiletools.gallery.pro, com.android.certinstaller, com.sec.modem.settings, theredspy15.ltecleanerfoss, com.sec.imslogger, com.samsung.android.goodlock, com.sec.android.cover.ledcover, com.samsung.android.app.camera.sticker.facear.preload, top.niunaijun.blackdexa64, com.samsung.android.easysetup, com.samsung.android.app.watchmanager, sansunsen3.imagesearcher, com.android.cts.priv.ctsshim, com.draco.respring, com.google.android.syncadapters.contacts, jp.ddo.hotmist.unicodepad, com.sec.android.easyonehand, mark.via, com.google.android.gm, com.draco.echo, com.samsung.android.app.advsounddetector, com.sec.android.app.sysscope, com.one.ui.s10.iconpack, com.monotype.android.font.cooljazz, com.sec.android.wallpapercropper2] 2021-07-01 09:04:10.637 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:10.664 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:10.689 E/ADA - App Info: isPackageChanged called 2021-07-01 09:04:10.699 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764) 2021-07-01 09:04:11.778 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:11.820 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:11.954 D/updateInfoForUid: Uid: 1000 2021-07-01 09:04:11.984 D/updateInfoForPackages: packages: [com.skms.android.agent, com.samsung.android.bbc.bbcagent, com.android.server.telecom, com.android.wallpaperbackup, org.codeaurora.btmultisim, com.qualcomm.atfwd, com.sec.imsservice, com.sec.android.emergencymode.service, com.samsung.android.lool, com.sec.mldapchecker, com.samsung.android.sm, com.samsung.tmowfc.wfcpref, com.samsung.android.app.accesscontrol, com.sec.android.wallpapercropper2, com.samsung.android.da.daagent, com.android.location.fused, com.android.providers.settings, com.samsung.android.securitylogagent, com.samsung.android.dlp.service, com.sec.android.app.sysscope, com.sec.android.app.quicktool, com.samsung.android.app.assistantmenu, com.sec.sve, com.trustonic.tuiservice, com.android.inputdevices, com.qualcomm.location, com.samsung.android.clipboarduiservice, com.sec.modem.settings, com.sec.android.app.parser, com.dsi.ant.server, com.samsung.android.SettingsReceiver, com.sec.android.app.factorykeystring, com.samsung.android.app.filterinstaller, com.sec.android.app.wlantest, com.samsung.android.app.advsounddetector, com.sec.factory, com.qualcomm.qti.services.secureui, com.samsung.android.hmt.vrsvc, com.samsung.android.stickercenter, com.sec.android.app.servicemodeapp, com.samsung.android.fingerprint.service, com.samsung.android.svcagent, com.samsung.aasaservice, com.sec.android.app.SecSetupWizard, com.samsung.android.universalswitch, com.sec.android.uibcvirtualsoftkey, com.samsung.android.smartface, com.samsung.app.jansky, com.sec.bcservice, com.wssyncmldm, com.sec.vsimservice, com.samsung.clipboardsaveservice, com.sec.android.preloadinstaller, com.samsung.android.app.color, com.policydm, com.sec.android.app.bluetoothtest, com.samsung.knox.securefolder.setuppage, com.samsung.android.MtpApplication, android, com.samsung.android.app.mirrorlink, com.sec.android.soagent, com.sec.android.app.apex, com.sec.android.emergencylauncher, com.samsung.advp.imssettings, com.sec.android.providers.security, com.sec.android.app.personalization, com.qualcomm.svi, com.sec.hiddenmenu, com.wssnps, com.samsung.android.ststub, com.sec.app.RilErrorNotifier, com.qualcomm.cabl, com.samsung.tmowfc.wfccontroller, com.qualcomm.wfd.service, com.samsung.android.themecenter, com.sec.factory.camera, com.samsung.helphub, com.sec.android.diagmonagent, com.samsung.SMT, com.android.keychain, com.sec.imslogger, com.mobeam.barcodeService, com.samsung.android.personalpage.service, com.sem.factoryapp, com.sec.android.app.hwmoduletest, com.samsung.ucs.agent.boot, com.samsung.android.fmm, com.sec.automation, com.sec.usbsettings, com.android.settings, com.samsung.android.shortcutbackupservice, com.sec.epdg, com.sec.enterprise.mdm.services.simpin, com.sec.android.app.applinker, com.qualcomm.qti.auth.fidocryptoservice] 2021-07-01 09:04:11.962 D/ADVM: Locale changed. 2021-07-01 09:04:12.654 E/ADA - App Info: isPackageChanged called 2021-07-01 09:04:12.685 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764) 2021-07-01 09:04:13.319 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:13.355 E/OsEnvironment: [StorageVolume: Device memory, StorageVolume: SD card (BCF4-1CFD)] 2021-07-01 09:04:20.984 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764) 2021-07-01 09:04:33.768 E/ADA - Uses permissions: isPackageChanged called 2021-07-01 09:04:33.794 E/AppOpsService: Could not get app ops for UID 10490 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.size()' on a null object reference 	at android.os.Parcel.readException(Parcel.java:1973) 	at android.os.Parcel.readException(Parcel.java:1913) 	at com.android.internal.app.IAppOpsService$Stub$Proxy.getUidOps(IAppOpsService.java:579) 	at io.github.muntashirakon.AppManager.appops.AppOpsService.getOpsForPackage(AppOpsService.java:65) 	at io.github.muntashirakon.AppManager.appops.AppOpsUtils.getChangedAppOps(AppOpsUtils.java:15) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1131) 	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:701) 	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 	at java.lang.Thread.run(Thread.java:764)

Galaxy S7 edge
8.0.0
Debug #1370
ADB

**Comment by MuntashirAkon** [comment]
Thanks for reporting. This is a work in progress. I didn't push all the changes yet (#456, #388).

**Comment by MuntashirAkon** [comment]
Fixed in 9b11ca9c
