### ISSUE TITLE
Unable to Install Apk with AM

### ISSUE THREAD

**Issue by Canvas02** [MuntashirAkon/AppManager#508]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Error when trying to install apk via App Manager 
I tried installing apks from f-droid and during the installation of an update for [Neko](https://github.com/CarlosEsco/Neko)  

**To Reproduce**
Steps to reproduce the behaviour:
1. Download an apk
2. try to install it with App Manager
3. App gives notification to report Error

**Expected behavior**
App installs normally

**Crash logs**
```
java.lang.SecurityException: Caller has no access to session 1153646290
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
    at android.os.Parcel.createException(Parcel.java:2369)
    at android.os.Parcel.readException(Parcel.java:2352)
    at android.os.Parcel.readException(Parcel.java:2294)
    at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:541)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.cleanOldSessions(PackageInstallerCompat.java:753)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:655)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:527)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:69)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:31)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.6.2
App version code: 389
Android build version: A217FXXU5CUD4
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.012.A217FXXU5CUD4
Device brand: samsung
Device manufacturer: samsung
Device name: a21s
Device model: SM-A217F
Device product name: a21snnxx
Device hardware name: exynos850
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: auto
```

**Device info**
 - Device: Samsung A21s (SM-A217F)
 - OS Version: Android 11
 - App Manager Version: 2.6.2 (389)
 - Mode: auto (no root)

**Comment by MuntashirAkon** [comment]
Fixed in e8367198
