### ISSUE TITLE
Crash on Log export

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#525]
Hey there,
exporting logs a zip crashes the app:
``` android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=*/* (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
    at android.app.Activity.startActivityForResult(Activity.java:5314)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
    at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
    at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:208)
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:166)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at io.github.muntashirakon.AppManager.utils.BetterActivityResult.launch(BetterActivityResult.java:80)
    at io.github.muntashirakon.AppManager.logcat.LogViewerActivity.lambda$saveLogToTargetApp$38$LogViewerActivity(LogViewerActivity.java:867)
    at io.github.muntashirakon.AppManager.logcat.-$$Lambda$LogViewerActivity$Ppiuashrm-6QTtnstDCUk-_bJy8.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 2.6.2
App version code: 389
Android build version: 0d2dbb77b5
Android release version: 11
Android SDK version: 30
Android build ID: lineage_cheryl-userdebug 11 RQ3A.210705.001 0d2dbb77b5
Device brand: razer
Device manufacturer: Razer
Device name: cheryl
Device model: Phone
Device product name: lineage_cheryl
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: auto
```

Is there something, that I am doing wrong?
Thanks!

**Comment by MuntashirAkon** [comment]
This isn't reproducible on my device (LOS 18.1). We ask users to use the issue template so that they can describe the steps to reproduce the issue (which greatly reduce our time).

Anyway, can you install a [debug release](https://github.com/MuntashirAkon/AppManager/actions/runs/1058321554) and see if it's still reproducible? It's easier to figure out the error using a debug build because it describes the error (unlike a release version).

**Comment by UltraBlackLinux** [comment]
1. Sorry for the mess with the issue template - my GH app doesn't want to show the template picker :/
The steps to reproduce are literally just opening the log viewer and clicking save zip

2. Yes the crash is also happening with the debug build

The log now: https://0bin.net/paste/ic2R0m3n#+uPajCmIdTmii48puYmXMN-Tjot5gyvsRnRjVMD/bos
(Wait a minute, I am having the same activity not found problem, as I have discovered with adaway... Something seems borked about the lineageos build...)

**Comment by MuntashirAkon** [comment]
> (Wait a minute, I am having the same activity not found problem, as I have discovered with adaway... Something seems borked about the lineageos build...)

Check if the **Files** app (`com.android.documentsui`) is present.

**Comment by UltraBlackLinux** [comment]
> > (Wait a minute, I am having the same activity not found problem, as I have discovered with adaway... Something seems borked about the lineageos build...)
> 
> Check if the **Files** app (`com.android.documentsui`) is present.

Hmm I disabled since it's ugly and the MaterialFiles app is just better - Why would anything depend on one app specifically - But Ok

**Comment by MuntashirAkon** [comment]
> Hmm I disabled since it's ugly and the MaterialFiles app is just better - Why would anything depend on one app specifically - But Ok

This app is very important if you're device do not have any other document provider (see [pitfalls of SAF](https://commonsware.com/blog/2019/12/01/scoped-storage-stories-problems-saf.html)). Probably ask Material Files to implement a document provider so that you can safely disable it.
