### ISSUE TITLE
Crash when click on Instruction (WebView uninstalled)

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#566]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App crashes when go to instructions page (Android System WebView disabled)

**To Reproduce**
Steps to reproduce the behaviour:
1. Uninstall Android System WebView app
2. Click on upper-right-cornor 3 dot icon
3. Click on Instructions
App crashes

**Expected behavior**
I know its sounds silly why would you disable WebView & try to open Instructions page. But in my opinion it should say instruction page requires "Android System WebView app plz enable/update it" or something instead of crashing

**Crash logs**
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.misc.HelpActivity}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
   at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
   at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
   at android.webkit.WebView.getFactory(WebView.java:2530)
   at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
   at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
   at android.view.View.<init>(View.java:4574)
   at android.view.View.<init>(View.java:4706)
   at android.view.ViewGroup.<init>(ViewGroup.java:597)
   at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
   at android.webkit.WebView.<init>(WebView.java:643)
   at android.webkit.WebView.<init>(WebView.java:588)
   at android.webkit.WebView.<init>(WebView.java:571)
   at android.webkit.WebView.<init>(WebView.java:558)
   at android.webkit.WebView.<init>(WebView.java:548)
   at io.github.muntashirakon.AppManager.misc.HelpActivity.onAuthenticated(HelpActivity.java:50)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:46)
   at android.app.Activity.performCreate(Activity.java:7023)
   at android.app.Activity.performCreate(Activity.java:7014)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
   at android.app.ActivityThread.-wrap11(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Device info**
App version: 2.6.3
App version code: 392
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto (adb/no-root)

**Additional context**
Got this idea to disable WebView while testing https://github.com/mirfatif/PermissionManagerX/issues/19

**Comment by MuntashirAkon** [comment]
Thanks for reporting.

> in my opinion it should say instruction page requires "Android System WebView app plz enable/update it" or something instead of crashing

It should open the link to the docs instead.

**Comment by MuntashirAkon** [comment]
Fixed in 40694954
