### ISSUE TITLE
Crashed while force stopping Gardine app, while on split view

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#577]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Crashed while force stopping [Gardine](https://github.com/yauhen-l/gardine) app from AM. Gardine is an Accessibility app (plus Display over other apps), probably something related to that? IDK
It crashes every time (if I reproduce the same behaviour), not just one-time crash.

**To Reproduce**
1. while on Gardine app home screen click on the device split view
2. open AM on another split part, go to Gardine app & try to force stop it
AM crashed

**Expected behavior**
It should stop Gardine app as usual & it does stopped Gardine but AM crashed at the same time...

**Crash logs**

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@e507dd1 rejected from java.util.concurrent.ThreadPoolExecutor@f417036[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.refreshDetails(AppInfoFragment.java:575)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$gqktss2mpyH8q1NFsSnxCt8CtB4(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$gqktss2mpyH8q1NFsSnxCt8CtB4.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Device info**
App version: 2.6.3
App version code: 392
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Fixed in d7553da3.
