### ISSUE TITLE
Root Mode does not work for a rom with Sandboxed Play services patches

### ISSUE THREAD

**Issue by BurhanDanger** [MuntashirAkon/AppManager#620]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I applied 'Sandboxed Play services' patches from grapheneos. https://github.com/sn-00-x/lineage-gmscompat/tree/master/src/gmscompat_patches

Magisk grants superuser requests from AM. But AM works as if it is in 'no root' mode ( falls back to it).

**Crash logs**
 Previous crashlog
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3597)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7671)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:51)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:46)
   at android.app.Activity.performCreate(Activity.java:7994)
   at android.app.Activity.performCreate(Activity.java:7978)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3597)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:223)
   at android.app.ActivityThread.main(ActivityThread.java:7671)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 2.7.0-1586-DEBUG
App version code: 395
Android build version: eng.noob.20211109.101718
Android release version: 11
Android SDK version: 30
Android build ID: lineage_miatoll-userdebug 11 RD2A.211001.002 eng.noob.20211109.101718 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: curtana
Device model: Redmi Note 9 Pro
Device product name: lineage_miatoll
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: root
```

**log**

[AM-2021-11-10-00-28-02.txt](https://github.com/MuntashirAkon/AppManager/files/7510186/AM-2021-11-10-00-28-02.txt)

**Comment by MuntashirAkon** [comment]
The remote service is crashing:

```
11-10 00:28:35.826 D/AndroidRuntime( 5567): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-10 00:28:35.828 I/AndroidRuntime( 5567): Using default boot image
11-10 00:28:35.828 I/AndroidRuntime( 5567): Leaving lock profiling enabled
11-10 00:28:35.829 I/app_process( 5567): Core platform API reporting enabled, enforcing=false
11-10 00:28:35.898 D/app_process( 5567): Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
11-10 00:28:35.898 D/app_process( 5567): I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
11-10 00:28:35.919 W/app_process( 5567): JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-10 00:28:35.923 D/AndroidRuntime( 5567): Calling main entry io.github.muntashirakon.AppManager.server.IPCMain
11-10 00:28:36.057 W/System  ( 5567): No Compatibility callbacks set! Querying change 1531297613045645771
11-10 00:28:36.057 W/System  ( 5567): No Compatibility callbacks set! Querying change 7528921493777479941
11-10 00:28:36.059 E/IPC     ( 5567): Error in IPCMain
11-10 00:28:36.059 E/IPC     ( 5567): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
11-10 00:28:36.059 E/IPC     ( 5567): 	at io.github.muntashirakon.AppManager.server.common.ServerUtils.getSystemContext(ServerUtils.java:28)
11-10 00:28:36.059 E/IPC     ( 5567): 	at io.github.muntashirakon.AppManager.server.IPCMain.main(IPCMain.java:71)
11-10 00:28:36.059 E/IPC     ( 5567): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-10 00:28:36.059 E/IPC     ( 5567): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)
11-10 00:28:36.059 E/IPC     ( 5567): Caused by: java.lang.reflect.InvocationTargetException
11-10 00:28:36.059 E/IPC     ( 5567): 	at java.lang.reflect.Method.invoke(Native Method)
11-10 00:28:36.059 E/IPC     ( 5567): 	at io.github.muntashirakon.AppManager.server.common.ServerUtils.getSystemContext(ServerUtils.java:24)
11-10 00:28:36.059 E/IPC     ( 5567): 	... 3 more
11-10 00:28:36.059 E/IPC     ( 5567): Caused by: java.lang.RuntimeException: Unable to instantiate Application():java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.ActivityThread.attach(ActivityThread.java:7390)
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.ActivityThread.systemMain(ActivityThread.java:7434)
11-10 00:28:36.059 E/IPC     ( 5567): 	... 5 more
11-10 00:28:36.059 E/IPC     ( 5567): Caused by: java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1269)
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.ActivityThread.attach(ActivityThread.java:7386)
11-10 00:28:36.059 E/IPC     ( 5567): 	... 6 more
11-10 00:28:36.059 E/IPC     ( 5567): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-10 00:28:36.059 E/IPC     ( 5567): 	at com.android.internal.gmscompat.dynamite.GmsDynamiteHooks.initGmsServerApp(GmsDynamiteHooks.java:81)
11-10 00:28:36.059 E/IPC     ( 5567): 	at com.android.internal.gmscompat.GmsHooks.initApplicationBeforeOnCreate(GmsHooks.java:209)
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1162)
11-10 00:28:36.059 E/IPC     ( 5567): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1261)
11-10 00:28:36.059 E/IPC     ( 5567): 	... 7 more
11-10 00:28:36.060 I/app_process( 5567): System.exit called, status: 1
11-10 00:28:36.060 I/AndroidRuntime( 5567): VM exiting with result code 1.
```

**Comment by MuntashirAkon** [comment]
Can you send me the frameworks.jar file?

**Comment by MuntashirAkon** [comment]
Anyway, found the issue. The issue is with the following file:

https://github.com/sn-00-x/lineage-gmscompat/blob/10d0d6918d392c914a8907a36791b116d06ac613/src/gmscompat_patches/frameworks/base/0019-gmscompat-Add-support-for-loading-Dynamite-modules.patch#L260

If you look into the @kdrag0n's ProtonAOSP, the issue isn't present there:

https://github.com/ProtonAOSP/android_frameworks_base/blob/8dfafcba8bf8a01fe5750f64087021535e6b7cfa/core/java/com/android/internal/gmscompat/dynamite/GmsDynamiteHooks.java#L81

**Comment by BurhanDanger** [comment]
Thanks for such quick reply. After rebuilding rom with mentioned changes, AM working fine.

**Comment by kdrag0n** [comment]
Thanks for tracking down the issue @MuntashirAkon and sorry for the trouble. Yes, I noticed this bug while porting GmsCompat patches to Android 12 and fixed it by changing that line.
