### ISSUE TITLE
Unable to install .apks file on custom Android 12

### ISSUE THREAD

**Issue by Kris6na** [MuntashirAkon/AppManager#630]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Unable to install .apks files using App Manager on a freshly installed custom android 12. I tried installing the same file using APKMirror Installer and SAI APKs Installer and it was successfully installed by both of them.

**Crash logs**
java.lang.NoSuchMethodError: No interface method createSession(Landroid/content/pm/PackageInstaller$SessionParams;Ljava/lang/String;I)I in class Landroid/content/pm/IPackageInstaller; or its super classes (declaration of 'android.content.pm.IPackageInstaller' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:665)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:527)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:122)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:40)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

**Device Info**
App version: 2.6.4
App version code: 394
Android build version: 10839
Android release version: 12
Android SDK version: 31
Android build ID: SD1A.210817.036.A8
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: lavender
Device model: Redmi Note 7
Device product name: arrow_lavender
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Duplicate of #600
