### ISSUE TITLE
App crashes when loading large app icon

### ISSUE THREAD

**Issue by ZenerDeveloper** [MuntashirAkon/AppManager#649]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
It seems when loading a certain app icon, app manager crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install an app with a very large icon like [this](https://www.apkmirror.com/apk/linuxct/oxygenos-11-lwp-by-linuxct/oxygenos-11-lwp-by-linuxct-1-0-1-200903204425-cf07bb7-release/oxygenos-11-lwp-by-linuxct-1-0-1-200903204425-cf07bb7-android-apk-download/)
2. Make it show in the list (search or scroll)
3. App briefly shows no icon or the wrong icon then crashes
4. If you open the details page quickly before the app crashes, it will show without an icon and still Crash

**Expected behavior**
The app showing the icon and not crashing.

**Screenshots**

**Crash logs**
<details>
  <summary>Click to view</summary>

```
java.lang.RuntimeException: Canvas: trying to draw too large(391029408bytes) bitmap.
    at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:281)
    at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
    at android.widget.ImageView.onDraw(ImageView.java:1453)
    at android.view.View.draw(View.java:23901)
    at android.view.View.updateDisplayListIfDirty(View.java:22776)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.draw(View.java:23904)
    at android.view.View.updateDisplayListIfDirty(View.java:22776)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.draw(View.java:23904)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:22776)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.draw(View.java:23904)
    at android.view.View.updateDisplayListIfDirty(View.java:22776)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.updateDisplayListIfDirty(View.java:22762)
    at android.view.View.draw(View.java:23631)
    at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
    at android.view.View.draw(View.java:23904)
    at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
    at android.view.View.updateDisplayListIfDirty(View.java:22776)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
    at android.view.Choreographer.doCallbacks(Choreographer.java:809)
    at android.view.Choreographer.doFrame(Choreographer.java:744)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Device Info:
App version: 2.6.5.1
App version code: 397
Android build version: G975U1UES6GUI1
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.012.G975U1UES6GUI1
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2q
Device model: SM-G975U1
Device product name: beyond2qlteue
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
```

</details>

**Device info**
 - Device: Samsung Galaxy S10+
 - OS Version: Android 11 OneUI 3.1
 - App Manager Version: v2.6.5.1
 - Mode: No root

**Additional context**
The icon to the attached app is 2159x3656 (8.0mp 3.5MiB .png) for some reason

**Comment by MuntashirAkon** [comment]
Fixed in 6b4845a1
