### ISSUE TITLE
Crash while changing Mode of operation (2.7.0-1650-DEBUG)

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#652]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App crashed while changing Mode of operation to ADB over TCP

**To Reproduce**
Steps to reproduce the behaviour:
- Open App Manager, change Mode of operation to ADB over TCP
- Go back to AppManager's home (Onboard_Packages)
- See a dialog that "Working on ADB mode" then app crashed

**Crash logs**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:64)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:60)
   at android.app.Activity.performCreate(Activity.java:7023)
   at android.app.Activity.performCreate(Activity.java:7014)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
   at android.app.ActivityThread.-wrap11(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Device Info**
App version: **2.7.0-1650-DEBUG**
App version code: 395
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: adb_tcp

**Comment by MuntashirAkon** [comment]
While this crash is a rare one, I've yet to figure out what went wrong here.

**Comment by shuvashish76** [comment]
I usually don't use debug builds, it crashed multiple times.
I installed both Release build + Debug build. Probably that triggered something IDK.
Works perfectly with Release versions.

**Comment by MuntashirAkon** [comment]
Closed until next time someone encounter the issue.

**Comment by shuvashish76** [comment]
👍🏿 please add "waiting for response" "info-needed" or some similar tag.

**Comment by MuntashirAkon** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3774)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8184)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:95)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8129)
   at android.app.Activity.performCreate(Activity.java:8109)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:233)
   at android.os.Looper.loop(Looper.java:344)
   at android.app.ActivityThread.main(ActivityThread.java:8184)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:95)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8129)
   at android.app.Activity.performCreate(Activity.java:8109)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:233)
   at android.os.Looper.loop(Looper.java:344)
   at android.app.ActivityThread.main(ActivityThread.java:8184)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 Caused by: java.lang.RuntimeException: Couldn't connect to appOpsService locally
   at io.github.muntashirakon.AppManager.appops.AppOpsService.<init>(AppOpsService.java:41)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:660)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:95)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8129)
   at android.app.Activity.performCreate(Activity.java:8109)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:233)
   at android.os.Looper.loop(Looper.java:344)
   at android.app.ActivityThread.main(ActivityThread.java:8184)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 Caused by: android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
   at io.github.muntashirakon.AppManager.ipc.ProxyBinder.transact(ProxyBinder.java:59)
   at android.permission.IPermissionManager$Stub$Proxy.grantRuntimePermission(IPermissionManager.java:1047)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:314)
   at io.github.muntashirakon.AppManager.appops.AppOpsService.<init>(AppOpsService.java:36)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:660)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:95)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8129)
   at android.app.Activity.performCreate(Activity.java:8109)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:233)
   at android.os.Looper.loop(Looper.java:344)
   at android.app.ActivityThread.main(ActivityThread.java:8184)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

Device Info:
App version: 3.1.0-alpha01-DEBUG
App version code: 411
Android build version: R.202207080037
Android release version: 12
Android SDK version: 31
Android build ID: RMX3461_11_C.02
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: adb_wifi
```

**Comment by Guru-25** [comment]
Seems like AM does get `android.permission.GET_APP_OPS_STATS` permission, which caused AppDetailsViewModel crash.

Found a workaround to solve this.
1. Turning on special [debugging permission](https://muntashirakon.github.io/AppManager/en/#subsec:enable-usb-debugging), Xiomi users should enable _USB debugging (Security settings)_, realme users should enable _Disable Permission Monitoring_ and so on.. which allows AM to get `android.permission.GET_APP_OPS_STATS` permission
2. Or users should manually grant GET_APP_OPS_STATS permission to AM by running this command in adb
```adb shell pm grant io.github.muntashirakon.AppManager android.permission.GET_APP_OPS_STATS``` with special [debugging permissions](https://muntashirakon.github.io/AppManager/en/#subsec:enable-usb-debugging) enabled

**Comment by MuntashirAkon** [comment]
> * Turning on special [debugging permission](https://muntashirakon.github.io/AppManager/en/#subsec:enable-usb-debugging), Xiomi users should enable _USB debugging (Security settings)_, realme users should enable _Disable Permission Monitoring_ and so on.. which allows AM to get `android.permission.GET_APP_OPS_STATS` permission

So, this appears not to be an issue with App Manager but a misconfiguration on the user's end. But I will insert this info in the community guides.
