### ISSUE TITLE
MIUI 12.5.3.0 rules import failed

### ISSUE THREAD

**Issue by Zafrkant** [MuntashirAkon/AppManager#655]
Hi,

I have issue with importing rules on MIUI 12.5.3.0 haydn. MIUI optimization is disabled.

You can find log here:
java.lang.SecurityException: Cannot disable a protected package: com.google.android.apps.work.oobconfig
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
    at android.os.Parcel.createException(Parcel.java:2360)
    at android.os.Parcel.readException(Parcel.java:2343)
    at android.os.Parcel.readException(Parcel.java:2285)
    at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:6859)
    at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.setComponentEnabledSetting(PackageManagerCompat.java:177)
    at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.applyRules(ComponentsBlocker.java:398)
    at io.github.muntashirakon.AppManager.rules.RulesImporter.applyRules(RulesImporter.java:104)
    at io.github.muntashirakon.AppManager.rules.RulesTypeSelectionDialogFragment.lambda$handleImport$9$RulesTypeSelectionDialogFragment(RulesTypeSelectionDialogFragment.java:114)
    at io.github.muntashirakon.AppManager.rules.-$$Lambda$RulesTypeSelectionDialogFragment$ehquDM_CEt6rNvtr7sLeUTg7fwA.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21600)
	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:21525)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3237)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4425)
	at android.os.Binder.execTransactInternal(Binder.java:1157)

Device Info:
App version: 2.6.5.1
App version code: 397
Android build version: V12.5.3.0.RKKMIXM
Android release version: 11
Android SDK version: 30
Android build ID: RKQ1.201112.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: haydn
Device model: M2012K11G
Device product name: haydn_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Fixed in b4f749cb
