### ISSUE TITLE
Scanner:crash when tap collum while scan is progress

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#665]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**To Reproduce**

https://user-images.githubusercontent.com/41156994/152307829-48170aed-4d70-4aba-b375-27782dc9fb8f.mp4

**Crash logs**
```
java.lang.AbstractMethodError: abstract method "int android.text.ParcelableSpan.getSpanTypeIdInternal()"
    at android.text.TextUtils.writeToParcel(TextUtils.java:771)
    at android.os.Parcel.writeCharSequence(Parcel.java:891)
    at android.os.Parcel.writeValue(Parcel.java:1877)
    at android.os.Parcel.writeList(Parcel.java:1140)
    at android.view.accessibility.AccessibilityEvent.writeAccessibilityRecordToParcel(AccessibilityEvent.java:1364)
    at android.view.accessibility.AccessibilityEvent.writeToParcel(AccessibilityEvent.java:1317)
    at android.view.accessibility.IAccessibilityManager$Stub$Proxy.sendAccessibilityEvent(IAccessibilityManager.java:625)
    at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:660)
    at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:9161)
    at android.view.View.requestParentSendAccessibilityEvent(View.java:8335)
    at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:8328)
    at android.view.View.sendAccessibilityEventUnchecked(View.java:8290)
    at android.view.View.sendAccessibilityEventInternal(View.java:8267)
    at android.view.View.sendAccessibilityEvent(View.java:8231)
    at com.android.internal.policy.DecorView.sendAccessibilityEvent(DecorView.java:638)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3299)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2143)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8678)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by MuntashirAkon** [comment]
Fixed in 53494592
