### ISSUE TITLE
Crash When Installing a App through Aurora Store

### ISSUE THREAD

**Issue by ASTechnical** [MuntashirAkon/AppManager#675]
- I know what my device, OS and App Manager versions are
- I know how to take logs
- I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App Manager Crashes When installing a app through Aurora Store.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Aurora Store
2. Install App
3. See error

**Expected behavior**
App Manager Should not Crash.

**Crash logs**
`java.lang.IllegalArgumentException: ApkFile not found for key -2005669272
    at io.github.muntashirakon.AppManager.apk.ApkFile.getInstance(ApkFile.java:89)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:125)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:40)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.os.HandlerThread.run(HandlerThread.java:65)`

**Device info**
 - Device: [Samsung Galaxy J2 Core]
 - OS Version: [ Android 8.1]
 - App Manager Version: [2.6.5.1]
 - Mode: no-root

**Additional context**
App Manager can be Selected as the Installation Method in Aurora Store Nightly. But when i try to install an app with App Manager Selected as the Installation Method App Manager Crashes.

**Comment by MuntashirAkon** [comment]
Consider opening an issue in the Aurora Store's issue tracker instead.
