### ISSUE TITLE
cleare cache crash 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [MuntashirAkon/AppManager#679]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=*/* (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1981)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)
    at android.app.Activity.startActivityForResult(Activity.java:4762)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
    at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
    at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at io.github.muntashirakon.AppManager.utils.BetterActivityResult.launch(BetterActivityResult.java:80)
    at io.github.muntashirakon.AppManager.logcat.LogViewerActivity.lambda$saveLogToTargetApp$38$LogViewerActivity(LogViewerActivity.java:869)
    at io.github.muntashirakon.AppManager.logcat.-$$Lambda$LogViewerActivity$Ppiuashrm-6QTtnstDCUk-_bJy8.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: 354(C432)
Android release version: 8.0.0
Android SDK version: 26
Android build ID: RNE-L21 8.0.0.354(C432)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWRNE
Device model: RNE-L21
Device product name: RNE-L21
Device hardware name: hi6250
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: fr
In-App Language: fr
Mode: auto

**Comment by MuntashirAkon** [comment]
The crashlogs suggest that you have no document provider and it's crashing on the Log Viewer page when you're trying to save logs. I do not find anything regarding clearing app cache.

**Comment by Disqu3-mirOir-qt** [comment]
> The crashlogs suggest that you have no document provider and it's crashing on the Log Viewer page when you're trying to save logs. I do not find anything regarding clearing app cache.

yes my bad shared wrong log

android.content.res.Resources$NotFoundException: String resource ID storage_settings_for_app
    at io.github.muntashirakon.AppManager.utils.ResourceUtil.getString(ResourceUtil.java:54)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.getString(NoRootAccessibilityService.java:146)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.navigateToStorageAndCache(NoRootAccessibilityService.java:107)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.onAccessibilityEvent(NoRootAccessibilityService.java:65)
    at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1527)
    at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1712)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: 354(C432)
Android release version: 8.0.0
Android SDK version: 26
Android build ID: RNE-L21 8.0.0.354(C432)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWRNE
Device model: RNE-L21
Device product name: RNE-L21
Device hardware name: hi6250
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: auto

**Comment by Disqu3-mirOir-qt** [comment]
yes my bad shared wrong log


android.content.res.Resources$NotFoundException: String resource ID storage_settings_for_app
    at io.github.muntashirakon.AppManager.utils.ResourceUtil.getString(ResourceUtil.java:54)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.getString(NoRootAccessibilityService.java:146)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.navigateToStorageAndCache(NoRootAccessibilityService.java:107)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.onAccessibilityEvent(NoRootAccessibilityService.java:65)
    at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1527)
    at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1712)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: 354(C432)
Android release version: 8.0.0
Android SDK version: 26
Android build ID: RNE-L21 8.0.0.354(C432)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWRNE
Device model: RNE-L21
Device product name: RNE-L21
Device hardware name: hi6250
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: auto

**Comment by Disqu3-mirOir-qt** [comment]
yes my bad shared wrong log

...
android.content.res.Resources$NotFoundException: String resource ID storage_settings_for_app
    at io.github.muntashirakon.AppManager.utils.ResourceUtil.getString(ResourceUtil.java:54)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.getString(NoRootAccessibilityService.java:146)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.navigateToStorageAndCache(NoRootAccessibilityService.java:107)
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.onAccessibilityEvent(NoRootAccessibilityService.java:65)
    at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1527)
    at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1712)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
...

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: 354(C432)
Android release version: 8.0.0
Android SDK version: 26
Android build ID: RNE-L21 8.0.0.354(C432)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWRNE
Device model: RNE-L21
Device product name: RNE-L21
Device hardware name: hi6250
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: auto
