### ISSUE TITLE
suggested F-Droid version (3.0.0-alpha01) never displays app list

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#685]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Somehow (and this seems like a bad idea), version 3.0.0-alpha01 became the "suggested" version on F-Droid, and got installed. Basically, it doesn't work at all (four different devices from Android 6 through 10). In all of the devices, when starting the app, I get a search bar at the top, and a horizontal purple line moving from left to right immediately beneath that. Nothing else ever appears. Yes, I have restarted the devices.

**To Reproduce**

Start AppManager. Wait forever for the app listing to appear.

**Expected behavior**

Obviously, I expect to see the app list. :)

**Device info**

I will just include the Android 10 device here.

 - Device: [Xiaomi Mi A3]
 - OS Version: [crDroid 6.13]
 - App Manager Version: [3.0.0-alpha01]
 - Mode: root

**Comment by citizenserious** [comment]
Also it's crashing from time to time, maybe this is related? 

java.lang.RuntimeException: Parcel android.os.Parcel@5129892: Unmarshalling unknown type code 6881399 at offset 1612
    at android.os.Parcel.readValue(Parcel.java:3253)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
    at android.os.Parcel.readSparseArray(Parcel.java:2792)
    at android.os.Parcel.readValue(Parcel.java:3231)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2181)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3473)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: eng.user.20220216.111744
Android release version: 11
Android SDK version: 30
Android build ID: lineage_starlte-userdebug 11 RQ3A.211001.001 eng.user.20220216.111744 test-keys
Device brand: samsung
Device manufacturer: samsung
Device name: starlte
Device model: SM-G960F
Device product name: starltexx
Device hardware name: samsungexynos9810
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en
In-App Language: en
Mode: root

**Comment by marcdw1289** [comment]
Confirmed for me also.
After clearing cache and data v3 works as expected.
Folks will need to export/backup their rules before updating. Luckily I had a recent backup but will still have to go through and verify things.

**Comment by MuntashirAkon** [comment]
Possibly an issue with the Room database.

**Comment by 2011** [comment]
It works for me also after clearing data and cache.

**Comment by MuntashirAkon** [comment]
See #656 for related crashes.

**Comment by mubashir-rehman** [comment]
similar issue
logs emailed, 
can confirm, works after clearing data and logs

**Comment by carallo** [comment]
Does clearing data and cache also removes rules and settings?

**Comment by MuntashirAkon** [comment]
> Does clearing data and cache also removes rules and settings?

It removes rules from AM but not from the system. You can export the rules using the export options.

**Comment by shifoc** [comment]
I have the same issue even after clearing the data. It was working and it stopped working alone

**Comment by MuntashirAkon** [comment]
It's definitely an issue with the Room database. Somehow version upgrade wasn't working as expected. In alpha03, App Manager will display a prompt to clear database and restart app if such thing happens.

**Comment by Raif1** [comment]
I have been using this version for a while now. I was having the same problems. After a while it seems to be fixed automatically.

**Comment by Sami32** [comment]
Same with non rooted Android 7.0 on Xiaomi with the latest 3.0.0 alpha01(400).
Applications was listed before this App Manager version.
[App-manager_logs-2022-05-08-00-49-59.zip](https://github.com/MuntashirAkon/AppManager/files/8646069/App-manager_logs-2022-05-08-00-49-59.zip)

**Comment by MuntashirAkon** [comment]
@licaon-kter: I apologise for pinging you here. It seems publishing alphas are disabled in F-Droid, but only after alpha01 was released. Could you, perhaps, remove the alpha version from F-Droid so that no new users complain about it?

**Comment by licaon-kter** [comment]
Will do asap

**Comment by licaon-kter** [comment]
Done: https://gitlab.com/fdroid/fdroiddata/-/commit/e12f357352b1900a2bb94447696cfb2175f40c3e

**Comment by MuntashirAkon** [comment]
From ba50d0a6e6f01278feca89898cdd1bb58fd7e571, it's possible to fix the issue by only clearing the caches of App Manager.
