### ISSUE TITLE
TarUtils.validateFiles() consumes 100% CPU for array filtering on backups with a large number of files

### ISSUE THREAD

**Issue by chenxiaolong** [MuntashirAkon/AppManager#693]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

When restoring a backup of an app with a very large number of files, 50000+ in my case, the majority of the time is spent in `TarUtils.validateFiles()` while consuming 100% CPU. Looking at a thread dump (pasted below), this seems to be caused by excessive `.equals()` comparisons due to `ArrayUtils.contains()` in:

https://github.com/MuntashirAkon/AppManager/blob/a01f9c86ae322e9cfbc3bd7620c2e3ee9a292626/app/src/main/java/io/github/muntashirakon/AppManager/utils/TarUtils.java#L249

I haven't had a chance to try it myself yet, but since `io.github.muntashirakon.io.Path` objects are hashable, I suspect making `children` a `HashMap` would speed this up quite a bit. I'll test that out this weekend.

**To Reproduce**
Steps to reproduce the behaviour (assuming a fresh install of App Manager):
1. Take a backup of an app with a huge number of files in its `/data/user/0/<package>` directory. In my specific case, all 50000 files are in the same folder.
2. Restore the backup.
3. App Manager consumes 100% CPU for an extended period of time.
4. Run `kill -3 <pid>` against App Manager's root process.
5. The trace in `/data/anr/` shows `TarUtils.validateFiles` in the stack trace of the thread consuming 100% CPU.

**Expected behavior**
App Manager ideally wouldn't spend too much CPU time filtering lists.

**Screenshots**
n/a

**Crash logs**
n/a

**Device info**
 - Device: Samsung Galaxy Tab S7+ (SM-T970)
 - OS Version: Android 12 (build T970XXU2CULC)
 - App Manager Version: 3.0.0-alpha01
 - Mode: root

**Additional context**

Thread dump of the thread consuming 100% CPU:

```
"pool-14-thread-1" prio=5 tid=57 Runnable
  | group="main" sCount=0 ucsCount=0 flags=0 obj=0x15700000 self=0xb400006f1d4d9400
  | sysTid=21181 nice=0 cgrp=default sched=0/0 handle=0x6ecd5b2cb0
  | state=R schedstat=( 88003619174 2290747222 1275426 ) utm=3976 stm=4823 core=7 HZ=100
  | stack=0x6ecd4af000-0x6ecd4b1000 stackSize=1039KB
  | held mutexes= "mutator lock"(shared held)
  at android.net.Uri.encode(Uri.java:1899)
  at android.net.Uri$PathPart.getEncoded(Uri.java:2176)
  at android.net.Uri$HierarchicalUri.appendSspTo(Uri.java:1273)
  at android.net.Uri$HierarchicalUri.makeUriString(Uri.java:1336)
  at android.net.Uri$HierarchicalUri.toString(Uri.java:1326)
  at android.net.Uri.equals(Uri.java:364)
  at io.github.muntashirakon.io.Path.equals(Path.java:832)
  at java.util.Objects.equals(Objects.java:76)
  at io.github.muntashirakon.AppManager.utils.ArrayUtils.indexOf(ArrayUtils.java:196)
  at io.github.muntashirakon.AppManager.utils.ArrayUtils.contains(ArrayUtils.java:186)
  at io.github.muntashirakon.AppManager.utils.TarUtils.lambda$validateFiles$2(TarUtils.java:249)
  at io.github.muntashirakon.AppManager.utils.-$$Lambda$TarUtils$XGJCnm6AI70wLOX80lJ_fQc3eHo.accept(lambda:-1)
  at io.github.muntashirakon.io.Path.listFiles(Path.java:732)
  at io.github.muntashirakon.AppManager.utils.TarUtils.validateFiles(TarUtils.java:249)
  at io.github.muntashirakon.AppManager.utils.TarUtils.validateFiles(TarUtils.java:256)
  at io.github.muntashirakon.AppManager.utils.TarUtils.validateFiles(TarUtils.java:256)
  at io.github.muntashirakon.AppManager.utils.TarUtils.validateFiles(TarUtils.java:256)
  ... repeated 1 times
  at io.github.muntashirakon.AppManager.utils.TarUtils.extract(TarUtils.java:187)
  at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreData(RestoreOp.java:487)
  at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:200)
  at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:163)
  at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:294)
  at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(lambda:-1)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:920)
```

**Comment by MuntashirAkon** [comment]
You're right. We can use a `HashMap` here since the URIs in `Path` are unique.

**Comment by chenxiaolong** [comment]
I did a quick test with a HashMap using the following patch:
```diff
diff --git a/app/src/main/java/io/github/muntashirakon/AppManager/utils/TarUtils.java b/app/src/main/java/io/github/muntashirakon/AppManager/utils/TarUtils.java
index b6b52e77..6e5f45bf 100644
--- a/app/src/main/java/io/github/muntashirakon/AppManager/utils/TarUtils.java
+++ b/app/src/main/java/io/github/muntashirakon/AppManager/utils/TarUtils.java
@@ -29,6 +29,8 @@ import java.io.OutputStream;
 import java.lang.annotation.Retention;
 import java.lang.annotation.RetentionPolicy;
 import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.HashSet;
 import java.util.List;
 
 import io.github.muntashirakon.AppManager.AppManager;
@@ -231,9 +233,9 @@ public final class TarUtils {
                                       @Nullable String[] exclude) {
         if (source.isDirectory()) {
             // Check if the contents of the directory matches the filters
-            Path[] children = source.listFiles(pathname -> pathname.isDirectory()
-                    || (isUnderFilter(pathname, basePath, filters) && !willExclude(pathname, basePath, exclude)));
-            if (children.length == 0) {
+            HashSet<Path> children = new HashSet<Path>(Arrays.asList(source.listFiles(pathname -> pathname.isDirectory()
+                    || (isUnderFilter(pathname, basePath, filters) && !willExclude(pathname, basePath, exclude)))));
+            if (children.isEmpty()) {
                 // No child has matched, delete this directory
                 if (!basePath.equals(source)) {
                     // Only delete if the source is not the base path
@@ -246,7 +248,7 @@ public final class TarUtils {
                 return;
             }
             // Check for unmatched children
-            Path[] unmatchedChildren = source.listFiles(pathname -> !ArrayUtils.contains(children, pathname));
+            Path[] unmatchedChildren = source.listFiles(pathname -> !children.contains(pathname));
             // Delete unmatched children
             for (Path child : unmatchedChildren) {
                 child.delete();
```
It seems to be working fine. I created an additional file in `/data/data/<package>/` and it was successfully deleted by the restore process.

Unrelated to this original bug report, but I also found that reducing `AMService`'s debug logging cuts down the restore time by about 40% in my (extreme) app data size scenario.
```diff
diff --git a/app/src/main/java/io/github/muntashirakon/AppManager/ipc/AMService.java b/app/src/main/java/io/github/muntashirakon/AppManager/ipc/AMService.java
index a214c109..84c4889f 100644
--- a/app/src/main/java/io/github/muntashirakon/AppManager/ipc/AMService.java
+++ b/app/src/main/java/io/github/muntashirakon/AppManager/ipc/AMService.java
@@ -123,7 +123,7 @@ public class AMService extends RootService {
                 transactRemote(data, reply, flags);
                 return true;
             }
-            Log.d(TAG, String.format("transact: uid=%d, code=%d", Binder.getCallingUid(), code));
+//            Log.d(TAG, String.format("transact: uid=%d, code=%d", Binder.getCallingUid(), code));
             return super.onTransact(code, data, reply, flags);
         }
 
@@ -136,7 +136,7 @@ public class AMService extends RootService {
             IBinder targetBinder = data.readStrongBinder();
             int targetCode = data.readInt();
 
-            Log.d(TAG, String.format("transact: uid=%d, descriptor=%s, code=%d", Binder.getCallingUid(), targetBinder.getInterfaceDescriptor(), targetCode));
+//            Log.d(TAG, String.format("transact: uid=%d, descriptor=%s, code=%d", Binder.getCallingUid(), targetBinder.getInterfaceDescriptor(), targetCode));
             Parcel newData = Parcel.obtain();
             try {
                 newData.appendFrom(data, data.dataPosition(), data.dataAvail());
```

**Comment by MuntashirAkon** [comment]
> It seems to be working fine. I created an additional file in `/data/data/<package>/` and it was successfully deleted by the restore process.

Thanks for testing. I have to review the URI-generation logic to find out how stable the URIs are (and whether there is any room for improvements). But they should be stable in this case since we're only working with Linux file system.

**Comment by MuntashirAkon** [comment]
Fixed in b16c74dd414bf1194ea84b6da5c377da9cfa7fd5

**Comment by chenxiaolong** [comment]
Thank you!

**Comment by MuntashirAkon** [comment]
I think a non-recursive implementation would cut the time by half.
