### ISSUE TITLE
App is crashing with adb over tcp 

### ISSUE THREAD

**Issue by shifoc** [MuntashirAkon/AppManager#701]
App is crashing when I open it after enabling adb over tcp 

**Device info**
 - Device: Samsung S22 Ultra
 - OS Version: Android 12
 - App Manager Version: version 3.0.0-alpha01

**Comment by MuntashirAkon** [comment]
No crash logs.

**Comment by shifoc** [comment]
I tried to reproduce it and it crashed but not the same way as before and now the app list is empty.

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@6b45a06 is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:1587)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:509)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
    at android.app.Dialog.show(Dialog.java:512)
    at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
    at io.github.muntashirakon.AppManager.adb.AdbUtils.configureWirelessDebugging(AdbUtils.java:153)
    at io.github.muntashirakon.AppManager.settings.Ops.lambda$connectWirelessDebugging$3(Ops.java:328)
    at io.github.muntashirakon.AppManager.settings.-$$Lambda$Ops$LvpuYTrGeCJL9nGlkhTc458Mk9A.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8646)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: S908EXXU1AVBF
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.016.S908EXXU1AVBF
Device brand: samsung
Device manufacturer: samsung
Device name: b0q
Device model: SM-S908E
Device product name: b0qxxx
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: adb_wifi

**Comment by MuntashirAkon** [comment]
Crash logs say wireless debugging, not ADB over TCP

**Comment by MuntashirAkon** [comment]
> I can't get it to work with ADB over TCP anymore to produce a crash log

Normal logs also work. Take logs using logcat when you enable ADB over TCP inside App Manager.

**Comment by MuntashirAkon** [comment]
Any updates?

**Comment by shifoc** [comment]
Hi,
I am not able go reproduce it right now other than the way mentioned in #722. I would also like you to note that even though wireless debugging is connected, in the settings it's written as wireless (inferred: no root).

Can you also please explain which features it enables?
Thanks

**Comment by shuvashish76** [comment]
This crash happened once in v3.1.2 but I'm not able to reproduce it yet.

<details><summary>Details</summary>
<p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@75fe294 is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:1216)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:431)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
    at android.app.Dialog.show(Dialog.java:345)
    at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$setStorageAndCache$117$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:1585)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda6.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:978)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8090)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

Device Info:
App version: 3.1.2
App version code: 425
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: root
```

</p>
</details>

**Comment by shuvashish76** [comment]
Ok I'm able to reproduce it with steps as mentioned [here](https://github.com/MuntashirAkon/AppManager/issues/658#issuecomment-1609828256).
Only difference is fresh install AM & don't give "Usage Access" permission. You can't click back from device navigation when it shows the dialog, you've to click one of the option from dialog. But you do it very fast that it crashes.

Steps:
1. Fresh Install AM > Open app info of any app
2. Click back from device navigation very fast, even before it asking Usage Access permission
3. Follow step2 multiple times
4. App crashes.

Also reproducible in v4.0.0-alpha02

**Comment by MuntashirAkon** [comment]
> Only difference is fresh install AM & don't give "Usage Access" permission. You can't click back from device navigation when it shows the dialog, you've to click one of the option from dialog. But you do it very fast that it crashes.

These issues will be fixed gradually since they're not very prominent.
