### ISSUE TITLE
App Manager: Crash report

### ISSUE THREAD

**Issue by m-koushan** [MuntashirAkon/AppManager#723]
java.lang.ClassCastException: io.github.muntashirakon.widget.MultiSelectionView cannot be cast to java.lang.Object[]
    at androidx.collection.SimpleArrayMap.allocArrays(SimpleArrayMap.java:184)
    at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:458)
    at androidx.transition.Transition.addViewValues(Transition.java:1529)
    at androidx.transition.Transition.captureHierarchy(Transition.java:1626)
    at androidx.transition.Transition.captureValues(Transition.java:1508)
    at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:294)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3325)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
    at android.view.Choreographer.doCallbacks(Choreographer.java:799)
    at android.view.Choreographer.doFrame(Choreographer.java:734)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8057)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Device Info:
App version: 3.0.0-alpha02
App version code: 401
Android build version: V12.5.7.0.RGGMIXM
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia
Device model: Redmi Note 8 Pro
Device product name: begonia
Device hardware name: mt6785
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
A similar issue has been reported via E-Mail:

```
java.lang.ClassCastException: io.github.muntashirakon.widget.MaterialAlertView cannot be cast to java.lang.Object[]
at androidx.collection.SimpleArrayMap.allocArrays(SimpleArrayMap.java:184)
at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:458)
at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:281)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1111)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3418)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2197)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8673)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
at android.view.Choreographer.doCallbacks(Choreographer.java:849)
at android.view.Choreographer.doFrame(Choreographer.java:779)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:257)
at android.app.ActivityThread.main(ActivityThread.java:8192)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

Device Info:
App version: 3.1.0-alpha01
App version code: 411
Android build version: eng.compil.20220607.200319
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.012 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1904
Device model: vivo 1904
Device product name: 1904
Device hardware name: mt6762
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
```

**Comment by MuntashirAkon** [comment]
This appears to be a bug in the AndroidX library.
