### ISSUE TITLE
App Manager(Crash report)

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#731]
java.lang.RuntimeException: Parcel android.os.Parcel@b258b25: Unmarshalling unknown type code 6881398 at offset 644
    at android.os.Parcel.readValue(Parcel.java:3269)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3666)
    at android.os.Parcel.readSparseArray(Parcel.java:2808)
    at android.os.Parcel.readValue(Parcel.java:3247)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3583)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2197)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1736)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1689)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1357)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3759)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:232)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:212)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:184)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:254)
    at android.app.ActivityThread.main(ActivityThread.java:8243)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

Device Info:
App version: 3.0.0-alpha02-DEBUG
App version code: 401
Android build version: 1639416523335
Android release version: 11
Android SDK version: 30
Android build ID: RMX2063_11_C.21
Device brand: realme
Device manufacturer: realme
Device name: RMX2063L1
Device model: RMX2063
Device product name: RMX2063
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by kryptobolt200528** [comment]
Edit:The issue is same as #685

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
