### ISSUE TITLE
App Manager: Crash report

### ISSUE THREAD

**Issue by m-koushan** [MuntashirAkon/AppManager#732]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.progressindicator.LinearProgressIndicator.hide()' on a null object reference
    at io.github.muntashirakon.AppManager.scanner.ScannerActivity.showProgress(ScannerActivity.java:144)
    at io.github.muntashirakon.AppManager.scanner.ScannerFragment.lambda$onViewCreated$5$ScannerFragment(ScannerFragment.java:154)
    at io.github.muntashirakon.AppManager.scanner.-$$Lambda$ScannerFragment$HL9HoATQQfc-u903guznqi6YkT8.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8057)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Device Info:
App version: 3.0.0-alpha02
App version code: 401
Android build version: V12.5.7.0.RGGMIXM
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia
Device model: Redmi Note 8 Pro
Device product name: begonia
Device hardware name: mt6785
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by m-koushan** [comment]
Just opened the app and it crashed

**Comment by MuntashirAkon** [comment]
Fixed in c1a8c819879ea68b7dd97e3681a92ed2aa048bfe
