### ISSUE TITLE
android 12: AM installer crash

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#740]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
AM crashes whwn pressing install on the installer popup

**To Reproduce**
Steps to reproduce the behaviour:
1. Install an app through AM
2. Crash

**Crash logs**
```
java.lang.NoSuchMethodError: No interface method createSession(Landroid/content/pm/PackageInstaller$SessionParams;Ljava/lang/String;I)I in class Landroid/content/pm/IPackageInstaller; or its super classes (declaration of 'android.content.pm.IPackageInstaller' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:676)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:527)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:69)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:31)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.6.2
App version code: 389
Android build version: e0ded777d3
Android release version: 12
Android SDK version: 32
Android build ID: lineage_cheryl-userdebug 12 SP2A.220405.004 e0ded777d3
Device brand: razer
Device manufacturer: Razer
Device name: cheryl
Device model: Phone
Device product name: lineage_cheryl
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: en
Mode: auto
```

**Device info**
In crash log apparently

**Comment by MuntashirAkon** [comment]
Limited A12 support is present since v2.6.5.
