### ISSUE TITLE
App data backup failed

### ISSUE THREAD

**Issue by overlord8** [MuntashirAkon/AppManager#758]
- [✓ ] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [✓ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
failed to backup nekox massanger. app backup works, data backup not working.

**Screenshots**

**Crash logs**

====> op=BACKUP_RESTORE, mode=1 pkg=(nekox.messenger, 0)
io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:160)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:89)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
====> op=BACKUP_RESTORE, mode=1 pkg=(nekox.messenger, 0)
io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.
	at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:160)
	at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:89)
	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:310)
	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
**Device info**
 - Device: POCO M2 (SHIVA)
 - OS Version: Android 11
 - App Manager Version:  v3.0.0-rc01 (403)
 - Mode: root

**Additional context**

**Comment by MuntashirAkon** [comment]
> io.github.muntashirakon.AppManager.backup.BackupException: The app has keystore items and KeyStore backup isn't enabled.

Logs clearly explained what is wrong here. You have to enable backing up KeyStore items. See docs: https://muntashirakon.github.io/AppManager/en/#backup-apps-with-android-keystore
