### ISSUE TITLE
App Manager: Crash report

### ISSUE THREAD

**Issue by tonytkachenko** [MuntashirAkon/AppManager#761]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
    at io.github.muntashirakon.AppManager.accessibility.NoRootAccessibilityService.onAccessibilityEvent(NoRootAccessibilityService.java:36)
    at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2181)
    at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2389)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7866)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Device Info:
App version: 3.0.0-rc01
App version code: 403
Android build version: 1651405415
Android release version: 12
Android SDK version: 32
Android build ID: SP2A.220405.004
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: jasmine_sprout
Device model: Mi A2
Device product name: derp_jasmine_sprout
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Already fixed in b84ad40489f1362de95a47c554d575176b0266f4
