### ISSUE TITLE
Backup restore failure

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#772]
Device Lenovo P1
OS MM 
AppManager_v3.0.0rc-DEBUG (404) Root mode

Scenario - creating a backup - deleting the app - restoring the backup.

[000.txt](https://github.com/MuntashirAkon/AppManager/files/8837563/000.txt)
[logs-2022-06-04-13-59-06.zip](https://github.com/MuntashirAkon/AppManager/files/8837565/logs-2022-06-04-13-59-06.zip)

**Comment by MuntashirAkon** [comment]
It produced the following error:
```
io.github.muntashirakon.AppManager.backup.BackupException: Failed to extract the apk file(s).
 at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:326)
 at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:197)
 at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:165)
 at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:316)
 at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(lambda)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: Zip slip vulnerability detected!
Expected dest: /data/local/tmp/base.apk
Actual path: /data/sdext2/com.androits.gps.test.pro-1/base.apk
 at io.github.muntashirakon.AppManager.utils.TarUtils.extract(TarUtils.java:200)
 at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:324)
 ... 9 more
```

It's reporting that `/data/local/tmp/base.apk` points to the file at `/data/sdext2/com.androits.gps.test.pro-1/base.apk` which is a potential [Zip slip vulnerability](https://github.com/snyk/zip-slip-vulnerability) (This is a defence mechanism that I have implemented in App Manager to prevent potential attacks by replacing the unencrypted tar files with malicious tar files). You can investigate yourself to see if this file `/data/local/tmp/base.apk` exists and if so, where it points to. If it exists, you have to delete it manually. If it does not exist, you can try restoring again.

**Comment by tommynok** [comment]
> It's reporting that `/data/local/tmp/base.apk` points to the file at `/data/sdext2/com.androits.gps.test.pro-1/base.apk` which is a potential [Zip slip vulnerability](https://github.com/snyk/zip-slip-vulnerability) (This is a defence mechanism that I have implemented in App Manager to prevent potential attacks by replacing the unencrypted tar files with malicious tar files). You can investigate yourself to see if this file `/data/local/tmp/base.apk` exists and if so, where it points to. If it exists, you have to delete it manually. If it does not exist, you can try restoring again.

Ah, so it is, the whole problem was in this file.
Which was linked to the gps.test app.
After deleting, I was able to restore the backup successfully.
It remains unclear why this file was in the tmp/ folder at all.
Since I don't even have this app installed at this time

**Comment by MuntashirAkon** [comment]
You might want to check the installed apps having root/ADB permission.
