### ISSUE TITLE
Log viewer | Export crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#777]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Log viewer'
2. Click on 'Export' > OK
3. See error

**Crash logs**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.github.muntashirakon.io.Path.getName()' on a null object reference
    at io.github.muntashirakon.AppManager.logcat.LogViewerActivity.lambda$onAuthenticated$7$LogViewerActivity(LogViewerActivity.java:222)
    at io.github.muntashirakon.AppManager.logcat.-$$Lambda$LogViewerActivity$9N25bE6h6wPLAcEqvDVNjOiNvIQ.onChanged(Unknown Source:4)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
Device Info:
App version: 3.0.0-rc02-DEBUG
App version code: 404
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Should be fixed in f564818a4768d7dfc7aea1ae99f9e2de5a9206c6
