### ISSUE TITLE
AppManager Crash When Blocking App Trackers.

### ISSUE THREAD

**Issue by Rajjco** [MuntashirAkon/AppManager#823]
java.lang.RuntimeException: Parcel android.os.Parcel@5d07d2: Unmarshalling unknown type code 6881399 at offset 1612
    at android.os.Parcel.readValue(Parcel.java:3306)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3707)
    at android.os.Parcel.readSparseArray(Parcel.java:2845)
    at android.os.Parcel.readValue(Parcel.java:3284)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3624)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2198)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1725)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1678)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1388)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3748)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Device Info:
App version: 3.0.0-rc02
App version code: 404
Android build version: 2435e0e9ee
Android release version: 12
Android SDK version: 32
Android build ID: lineage_lemonadep-userdebug 12 SQ3A.220705.003.A1 2435e0e9ee
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus9Pro
Device model: LE2120
Device product name: OnePlus9Pro
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment]
The reported version (v3.0.0-rc02) is no longer supported. Update to a more recent version and try to reproduce the issue.
