### ISSUE TITLE
App Manager doesn't launch with Internet permission revoked

### ISSUE THREAD

**Issue by mariobrostech** [MuntashirAkon/AppManager#833]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When the Internet permission is revoked for the App Manager app, it fails to launch. If it has been set up previously, you will see a blank screen. If this is a new installation, the app will hang on the Initializing screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install App Manager
2. Revoke App Manager's Internet permission
3. Launch App Manager
4. Observe that App Manager hangs on the Initializing screen
OR
1. Install App Manager
2. Launch App Manager
3. Observe that App Manager functions normally
4. Revoke App Manager's Internet permission
5. Observe App Manager launching to a blank screen

**Expected behavior**
I expect that App Manager's basic functionality will work whether or not the app has Internet permission granted to it. I understand that there is some functionality that will require App Manager to be granted the Internet permission, but the features not requiring this should continue to function without it.

**Screenshots**
![Screenshot_20220809-105508](https://user-images.githubusercontent.com/17557442/183683600-7df079f5-f63c-459b-9a30-ba916920db89.png)
![Screenshot_20220809-105603](https://user-images.githubusercontent.com/17557442/183683647-c7ac6e95-1a82-47f9-b658-eb07ac661b90.png)

**Crash logs**
If somebody could provide instructions on how to collect crash logs, I'd be more than happy to gather and share them here.

**Device info**
 - Device: Google Pixel 5a
 - OS Version: Android 12
 - App Manager Version: 3.0.0
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
How are you blocking the INTERNET permission? In any case, if the mode of operation is set to `no-root` like you've reported, it will not check for ADB over TCP/wireless debugging. So, it shouldn't hang no matter how you're blocking the permission.

**Comment by mariobrostech** [comment]
@MuntashirAkon Sorry for the delay in getting back to you; I was never notified of your reply for some reason.

I use [GrapheneOS](https://grapheneos.org) on my device, which allows users to deprive any installed app the Internet permission. When used with other apps, this functionality works fine, but with App Manager, it causes the app to hang during initialization.

I also haven’t explicitly set the mode of operation to `no-root` since the app doesn’t load far enough for me to do so. However, my device isn’t rooted, nor is my bootloader unlocked. When the Internet permission, the app loads up just fine, so I’m pretty sure it isn’t an issue with GrapheneOS itself (issues caused due to GrapheneOS’s hardening tend to show up regardless of the permissions that are granted to an app). I hope this gives you some additional context to help troubleshoot what’s going on here.

Thanks again for your help!

**Comment by MuntashirAkon** [comment]
> I also haven’t explicitly set the mode of operation to `no-root` since the app doesn’t load far enough for me to do so.

I see. If `android.permission.INTERNET` permission itself is revoked, the probably just checking whether this permission is granted will be enough (8e5f20c91a8011251016f05a5d8490ad1fdd58cd). If you're able to test this, please download a [debug build](https://github.com/MuntashirAkon/AppManager/actions/runs/2861640494) from the GitHub Actions page and install it without the permission. Debug builds have a different package name and you can install it side by side with the other build.

**Comment by mariobrostech** [comment]
I just tried installing the debug build that you linked to, and I'm still experiencing the same problem. Is there somewhere else that the app is checking for Internet permission that might make it hang? I can collect and submit logs as well if you can explain how I would do that.

**Comment by MuntashirAkon** [comment]
> Is there somewhere else that the app is checking for Internet permission that might make it hang?

I don't think so.

> I can collect and submit logs as well if you can explain how I would do that.

You can find logs at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`.

**Comment by mariobrostech** [comment]
I'm not sure what the issue is, then. Hopefully, the logs will help reveal what's going on.
[am.log](https://github.com/MuntashirAkon/AppManager/files/9338611/am.log)

**Comment by MuntashirAkon** [comment]
The file is empty. If it is from the debug build, it shouldn't be empty.

**Comment by mariobrostech** [comment]
It is from the debug build. Should I try running it with Internet permission first and then deny them as opposed to denying them out of the gate?

**Comment by MuntashirAkon** [comment]
> It is from the debug build. Should I try running it with Internet permission first and then deny them as opposed to denying them out of the gate?

No. If it's really empty (assuming you're **Files** app isn't causing any trouble), the App Manager isn't even proceeding to the point where Internet is being checked. Did it display any dialog at the start where it asked you to save the KeyStore password for future use?

**Comment by mariobrostech** [comment]
Yes, I saw the message asking me to save the KeyStore password for further use. Then, I see an Initialization screen, and that’s where it hangs.

**Comment by MuntashirAkon** [comment]
I see. Then I could be wrong. Let me check.

**Comment by MuntashirAkon** [comment]
Try 35f15c51c1166453d7a444b2ad8db55ef9f7f78f (https://github.com/MuntashirAkon/AppManager/actions/runs/2862459665)

**Comment by mariobrostech** [comment]
Still not working, but at least I got a log out of it this time!
[am.log](https://github.com/MuntashirAkon/AppManager/files/9338955/am.log)

**Comment by mariobrostech** [comment]
I’ve waited for at least a minute, since that’s what my screen timeout duration is set to. I’ll try again, this time letting it sit for 5 minutes before collecting logs.

**Comment by mariobrostech** [comment]
Here's a log after letting it sit for 5 minutes:
[am.log](https://github.com/MuntashirAkon/AppManager/files/9339040/am.log)

**Comment by MuntashirAkon** [comment]
Thank you. The logs look exactly the same, and I think I've figured out what might be causing this issue. Try 8d2cca5dc0474e0f03717765d67ff5d451989828 (https://github.com/MuntashirAkon/AppManager/actions/runs/2862615335) as usual, and please send me the logs even if it works.

**Comment by mariobrostech** [comment]
That did it, thank you so much! Here's the log, as requested:
[am.log](https://github.com/MuntashirAkon/AppManager/files/9339145/am.log)

**Comment by MuntashirAkon** [comment]
Here's the error:

```
java.lang.SecurityException: NsdService: Neither user 10186 nor current process has android.permission.INTERNET.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
	at android.os.Parcel.createException(Parcel.java:2411)
	at android.os.Parcel.readException(Parcel.java:2394)
	at android.os.Parcel.readException(Parcel.java:2336)
	at android.net.nsd.INsdManager$Stub$Proxy.getMessenger(INsdManager.java:148)
	at android.net.nsd.NsdManager.getMessenger(NsdManager.java:672)
	at android.net.nsd.NsdManager.init(NsdManager.java:510)
	at android.net.nsd.NsdManager.<init>(NsdManager.java:300)
	at android.app.SystemServiceRegistry$37.createService(SystemServiceRegistry.java:583)
	at android.app.SystemServiceRegistry$37.createService(SystemServiceRegistry.java:578)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1861)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1538)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:2115)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:859)
	at io.github.muntashirakon.adb.android.AdbMdns.<init>(AdbMdns.java:67)
	at io.github.muntashirakon.AppManager.adb.AdbUtils.getLatestAdbDaemon(AdbUtils.java:29)
	at io.github.muntashirakon.AppManager.settings.Ops.findAdbPort(Ops.java:461)
	at io.github.muntashirakon.AppManager.settings.Ops.findAdbPortNoThrow(Ops.java:470)
	at io.github.muntashirakon.AppManager.settings.Ops.autoDetectRootOrAdb(Ops.java:234)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:153)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:75)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2242)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2270)
	at com.android.server.NsdService.getMessenger(NsdService.java:605)
	at android.net.nsd.INsdManager$Stub.onTransact(INsdManager.java:94)
	at android.os.Binder.execTransactInternal(Binder.java:1201)
```

I don't get it. I've already placed checks for the `INTERNET` permission above the code that throws this error. It seemed to have skipped that check, which means that the permission was available to App Manager. It might, of course, be a bug (or could be intentional too). Let's see what the GrapheneOS developers have to say about this.
