### ISSUE TITLE
"Failed to access properties of the KeyStore folder" during restore

### ISSUE THREAD

**Issue by genpfault** [MuntashirAkon/AppManager#859]
- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Apps with KeyStore data fail to completely restore due to `io.github.muntashirakon.AppManager.backup.BackupException` exceptions.

Apps tried:
* `com.duosecurity.duomobile`
* `com.azure.authenticator`
* `org.mozilla.firefox`

**To Reproduce**
Attempt to restore an app with KeyStore data.

**Expected behavior**
I expected the app to be restored, KeyStore data included.

**Screenshots**
Restore log (composited) screenshot (is this logged anywhere?  I wasn't seeing it in `adb logcat`):

![backtrace screenshot](https://user-images.githubusercontent.com/721338/188506999-5c05b2f9-c4c3-4224-8321-6738a1082708.png)

**Crash logs**
Restore backtrace transcription (apologies for any typos, I OCR'd the screenshot above & manually corrected):
```none
====> op=BACKUP_RESTORE, mode=2 pkg=(com.duosecurity.duomobile, O)
io.github.muntashirakon.AppManager.backup.BackupException: Failed to access properties of the KeyStore folder.
  at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreKeyStore(RestoreOp.java:388)
  at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:203)
  at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManagerjava: 171)
  at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$io-github-muntashirakon-AppManager-batchops-BatchOpsManager(BatchOpsManager.java:322)
  at io.github.muntashirakon.AppManager.batchops.BatchOpsManager$$ExternalSyntheticLambda2.run(Unknown Source:12)
  at java.util.concurrent.Executors$RunnableAdaptercall(Executors.java:462)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor@Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java.920)
Caused by: android.system.ErrnoException: lstat failed: ENOENT (No such file or directory)
  at libcore.io.Linux.lstat(Native Method)
  at libcore.io.ForwardingOs.lstat(ForwardingOs.java:478)
  at libcore.io.BlockGuardOs.lstat(BlockGuardOs.java:249)
  at android.system.Os.lstat(Os.java:451)
  at io.github.muntashirakon.io.FileSystemService.getUidGid(Fi1eSystemService.java:200)
  at io.github.muntashirakon.io.IFileSystemService$Stub.onTransact(IFi1eSystemService.java:454)
  at android.os.Binder.execTransactInternal(Binder.java:1179)
  at android.os.Binder.execTransact(Binderjava:1143)
```

**Device info**
 - Device: [OnePlus Nord N100](https://en.wikipedia.org/wiki/OnePlus_Nord_N100)
 - OS Version: Android 12 via [AndyYan's LinageOS 19.x GSI](https://forum.xda-developers.com/t/gsi-12-lineageos-19-x-gsi-a64b-64b.4358041/)
 - App Manager Version: [v3.0.1 Stable](https://github.com/MuntashirAkon/AppManager/releases/tag/v3.0.1)
 - Mode: root, via [Magisk 25.2](https://github.com/topjohnwu/Magisk/releases/tag/v25.2)

**Additional context**
Backups were taken on a [Moto G7 Play](https://en.wikipedia.org/wiki/Moto_G7#G7_Play) running Android 11 (LinageOS 18.1) with [F-Droid's version](https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/) of [App Manager v3.0.0](https://f-droid.org/repo/io.github.muntashirakon.AppManager_410.apk).

**Comment by genpfault** [comment]
Per the comment in [`KeyStoreUtils.java:getKeyStoreFiles()`](https://github.com/MuntashirAkon/AppManager/blob/v3.0.1/app/src/main/java/io/github/muntashirakon/AppManager/utils/KeyStoreUtils.java#L40-L54):

```
// For any app, the key path is as follows:
// /data/misc/keystore/user_{user_handle}/{uid}_{KEY_NAME}_{alias}
```

...here is what's in `/data/misc/keystore`: 

```
phhgsi_arm64_ab:/ # ls -alh /data/misc/keystore/
total 98K
drwx------  2 keystore keystore 3.4K 2022-08-29 11:53 .
drwxrwx--t 60 system   misc     3.4K 1969-12-31 18:06 ..
-rw-------  1 keystore keystore  76K 2022-09-05 14:04 persistent.sqlite
-rw-------  1 keystore keystore    0 2022-08-29 11:53 timestamp
-rw-------  1 keystore keystore  16K 2022-08-14 02:09 vpnprofilestore.sqlite
```

The `user_*` files/directories are noticeably absent...

**Comment by genpfault** [comment]
Hmm, [this StackOverflow answer](https://stackoverflow.com/a/72160533) suggests this might be an Android 12 issue.

**Comment by MuntashirAkon** [comment]
Thanks for investigating, I shall take a look at the AOSP source code to see what to do (and how to migrate). It appears to be an undocumented change as I didn't find any official documentation regarding this change. However, I'm currently unable to test anything beyond Android 11, so I am fully dependent on Android docs, sources and user feedbacks.

**Comment by MuntashirAkon** [comment]
**[This is a developing story]**

Keystore2 has two databases:
1. `persistent.sqlite`: The main database where all the keys and their metadata are stored.
2. `vpnprofilestore.sqlite`: The legacy database where the pre-S style (legacy) keys are stored (the name looks something else, but it was due to its different usage).

When the latter database is empty or nonexistent, keystore2 activates the optimisation mode, imports the legacy keys and delete the previous file structure. This makes restoring a pre-S backup with keystore a bit easier since we can either empty the legacy database or add the files to this database and expect the optimisation to import it for us. (I haven't yet looked at the import process itself, but a detailed description is available [here](https://cs.android.com/android/platform/superproject/main/+/main:system/security/keystore2/tests/legacy_blobs/keystore2_legacy_blob_tests.rs;drc=7909224b9f6c20bf6601edf2c1a8323f508b2808).) However, we've made a mistake. We didn't back up the `.masterkey` in the pre-S backups; we only checked if the checksum matches with the current `.masterkey` in the system (if exists). So, if `.masterkey` existed in the past, the keystore will not restore at all. (We can back up the `.masterkey` from now on to avoid this issue in the future.)

Exporting a keystore from the former database (as part of the backup process in A12+) is complicated since it involves a lot of things now. What we can do, however, is that figure out if we can still convert keys to pre-S legacy keys. This would simplify things a lot.

I'm not sure when we can actually implement the whole thing.

**Comment by MuntashirAkon** [comment]
Decided to drop support for KeyStore backup since it's not feasible anymore: 06d009ad3104ca90bfd10e4cc83d0ce2ea2ffc08
