### ISSUE TITLE
Unable to block some trackers on Android 10

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#864]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Comparing two different devices here. AppManager does this for a handful of apps, but I will describe PCAPdroid (com.emanuelef.remote_capture) here.

**To Reproduce**

PCAPdroid has two trackers: cat.ereza.customactivityoncrash.provider.CaocInitProvider and cat.ereza.customactivityoncrash.activity.DefaultErrorActivity. The Android 7 devices blocks both trackers. The Android 10 device will only block the second. The first remains displayed is white (with the trackers label on the information page brown) no mattar how many times I attempt to block it.

**Expected behavior**

Both trackers blocked.

**Log**

The filtered log (from the Android 10 device) entries as captured by as external app (I had some difficulty clearing logs in the AppManager log viewer, but couldn't reproduce that):

```
[09-11 03:26:08.612 843:843 E/Layer]
[Surface(name=AppWindowToken{de71078 token=Token{b774ddb ActivityRecord{44466ea u0 io.github.muntashirakon.AppManager/.main.MainActivity t5300}}})/@0x72d4988 - animation-leash#0] No local sync point found

[09-11 03:26:08.613 1285:1323 V/AppLockService]
setForegroundApp(io.github.muntashirakon.AppManager)

[09-11 03:26:08.612 843:843 E/Layer]
[Surface(name=AppWindowToken{de71078 token=Token{b774ddb ActivityRecord{44466ea u0 io.github.muntashirakon.AppManager/.main.MainActivity t5300}}})/@0x72d4988 - animation-leash#0] No local sync point found

[09-11 03:26:09.360 1285:25488 I/ActivityTaskManager]
START u0 {cmp=io.github.muntashirakon.AppManager/.details.AppDetailsActivity (has extras)} from uid 10234

[09-11 03:26:09.423 1285:3605 V/AppLockService]
setForegroundApp(io.github.muntashirakon.AppManager)

[09-11 03:26:13.779 1285:3605 E/InputDispatcher]
Window handle Window{99e2794 u0 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity} has no registered input channel

[09-11 03:26:13.785 13670:15096 W/DF]
Failed to create /data/user/0/io.github.muntashirakon.AppManager/files/conf/com.emanuelef.remote_capture.tsv
java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at androidx.documentfile.provider.ExtendedRawDocumentFile.createFile(ExtendedRawDocumentFile.java:45)
        at io.github.muntashirakon.io.Path.findOrCreateFile(Path.java:532)
        at io.github.muntashirakon.AppManager.rules.RulesStorageManager.getDesiredFile(RulesStorageManager.java:270)
        at io.github.muntashirakon.AppManager.rules.RulesStorageManager.commit(RulesStorageManager.java:227)
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.addRules(AppDetailsViewModel.java:556)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$setupTagCloud$23$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:586)
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

[09-11 03:26:13.785 13670:15096 W/System.err]
java.io.IOException: Could not create file:///data/user/0/io.github.muntashirakon.AppManager/files/conf/com.emanuelef.remote_capture.tsv with type application/x-invalid-mime-type

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.io.Path.findOrCreateFile(Path.java:534)

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.AppManager.rules.RulesStorageManager.getDesiredFile(RulesStorageManager.java:270)

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.AppManager.rules.RulesStorageManager.commit(RulesStorageManager.java:227)

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.addRules(AppDetailsViewModel.java:556)

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$setupTagCloud$23$io-github-muntashirakon-AppManager-details-info-AppInfoFragment(AppInfoFragment.java:586)

[09-11 03:26:13.786 13670:15096 W/System.err]
        at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda2.run(Unknown Source:4)

[09-11 03:26:15.379 843:843 E/Layer]
[Surface(name=AppWindowToken{f143c40 token=Token{d022bc3 ActivityRecord{669eb72 u0 io.github.muntashirakon.AppManager/.details.AppDetailsActivity t5300}}})/@0xd301522 - animation-leash#0] No local sync point found

[09-11 03:26:15.379 843:843 E/Layer]
[Surface(name=AppWindowToken{f143c40 token=Token{d022bc3 ActivityRecord{669eb72 u0 io.github.muntashirakon.AppManager/.details.AppDetailsActivity t5300}}})/@0xd301522 - animation-leash#0] No local sync point found

[09-11 03:26:15.837 1285:25854 W/NotificationService]
Toast already killed. pkg=io.github.muntashirakon.AppManager callback=android.app.ITransientNotification$Stub$Proxy@b5f809a
```

**Device info**
 - Device: [Mi A3 / Teclast T10]
 - OS Version: [Android 10 / Andraid 7]
 - App Manager Version: [3.0.1]
 - Mode: root

**Comment by MuntashirAkon** [comment]
> Failed to create /data/user/0/io.github.muntashirakon.AppManager/files/conf/com.emanuelef.remote_capture.tsv
> java.io.IOException: Permission denied

These lines suggest that the trackers were successfully blocked but App Manager is unable to write to its own directory which is why it's using data from the last saved file that happens to contain only the latter component. Please check the permission of `/data/user/0/io.github.muntashirakon.AppManager/files/conf/` using a terminal emulator or a file manager such as Material Files or MiXplorer.

**Comment by 2011** [comment]
```
laurel_sprout:/data/user/0/io.github.muntashirakon.AppManager/files # ls -Ral
.:
total 9
drwxrwx--x 3 u0_a234 u0_a234 3488 2022-02-23 11:31 .
drwx------ 9 u0_a234 u0_a234 3488 2022-07-27 09:48 ..
drwxr-xr-x 2 root    root    3488 2022-02-23 11:31 conf

./conf:
total 6
drwxr-xr-x 2 root    root    3488 2022-02-23 11:31 .
drwxrwx--x 3 u0_a234 u0_a234 3488 2022-02-23 11:31 ..
```

**Comment by MuntashirAkon** [comment]
Change the ownership of the conf folder:

```
chown -R u0_a234:u0_a234 /data/user/0/io.github.muntashirakon.AppManager/files/conf
```

**Comment by 2011** [comment]
That worked (thanks), but I wonder how the directory got created with the "wrong" owner in the first place (I never touched it). Did AppManager create it incorrectly, or did something else possibly alter it?

**Comment by MuntashirAkon** [comment]
> Did AppManager create it incorrectly?

Yes, this could be the case if you're coming from the alpha/RC builds (I cannot remember exactly which one, probably alpha-01). If see more of these issues coming up, I will write a migration routine for it.
