### ISSUE TITLE
Crash on clearing cache

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#930]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

During clearing cache of a specific app, I experienced this crash.

### To Reproduce

- 1. Go to that app's page properties on AM Debug
- 2. Clear the cache
- 3. You'll get that crash

### Expected behavior

I expected no crash at all.

### Logs

```
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object io.github.muntashirakon.AppManager.details.struct.AppDetailsItem.vanillaItem' on a null object reference
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getActivityView(AppDetailsFragment.java:960)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:896)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:635)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2253)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:731)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Device info

App version: 3.1.0-alpha01-DEBUG
App version code: 411
Android build version: eng.joel16.20220120.132941
Android release version: 11
Android SDK version: 30
Android build ID: lineage_satsuki-userdebug 11 RQ3A.211001.001 eng.joel16.20220120.132941 test-keys
Device brand: Sony
Device manufacturer: Sony
Device name: satsuki
Device model: E6853
Device product name: E6853
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: tr-TR
In-App Language: auto
Mode: auto
Inferred Mode: root

**Comment by MuntashirAkon** [comment]
<details>

<summary>Similar issues reported via E-Mail</summary>

```
java.lang.NullPointerException: Attempt to read from field
'java.lang.Object
io.github.muntashirakon.AppManager.details.struct.AppDetailsItem.vanillaItem'
on a null object reference in method 'void
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getActivityView(android.content.Context,
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter$ViewHolder,
int)'
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getActivityView(AppDetailsFragment.java:953)
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:895)
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:635)
    at
androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at
androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at
androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
    at
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at
androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at
androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at
com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
    at
com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2253)
    at
androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
    at android.view.View.layout(View.java:23700)
    at android.view.ViewGroup.layout(ViewGroup.java:6413)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3999)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
    at
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9080)
    at
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
    at
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:832)
    at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Device Info:
App version: 3.1.0-alpha02
App version code: 415
Android build version: 9244662
Android release version: 13
Android SDK version: 33
Android build ID: TQ1A.221205.011
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
Device hardware name: oriole
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-AU
In-App Language: auto
Mode: auto
Inferred Mode: root
```

```
java.lang.NullPointerException: Attempt to read from field
'java.lang.Object
io.github.muntashirakon.AppManager.details.struct.AppDetailsItem.vanillaItem'
on a null object reference
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getActivityView(AppDetailsFragment.java:953)
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:889)
    at
io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:633)
    at
androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at
androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at
androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
    at
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at
androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at
androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at
com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at
com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2227)
    at
androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3755)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
    at
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8797)
    at
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Device Info:
App version: 3.0.0-rc04
App version code: 406
Android build version: 1661162888
Android release version: 12
Android SDK version: 32
Android build ID: SQ3A.220705.004
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: cheeseburger
Device model: ONEPLUS A5000
Device product name: aosp_cheeseburger
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
```

</details>

**Comment by MuntashirAkon** [comment]
This issue doesn't appear to be reproducible anymore.
