### ISSUE TITLE
Shortcut issues 

### ISSUE THREAD

**Issue by soheilkhanalipur** [MuntashirAkon/AppManager#963]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1. Search for 'com.google.android.documentsui' 
2. Click on 'Activities' 
3. Create 'com.android.documentsui.files.FilesActivity' shortcut
4. Edit shortcut icon section
5. See error

### To Reproduce

1. Search for 'com.google.android.documentsui' 
2. Click on 'Activities' 
3. Create 'com.android.documentsui.files.FilesActivity' shortcut
4. Edit shortcut icon section
5. See error

### Logs

android.content.res.Resources$NotFoundException: Resource ic_app_ico of type mipmap is not found in package com.google.android.documentsui
    at io.github.muntashirakon.AppManager.utils.ResourceUtil.getResourceFromName(ResourceUtil.java:61)
    at io.github.muntashirakon.AppManager.details.EditShortcutDialogFragment.getDrawable(EditShortcutDialogFragment.java:130)
    at io.github.muntashirakon.AppManager.details.EditShortcutDialogFragment$1.afterTextChanged(EditShortcutDialogFragment.java:81)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:11911)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15283)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1291)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:591)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
    at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:232)
    at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:337)
    at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:49)
    at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:285)
    at android.view.inputmethod.InputConnectionWrapper.deleteSurroundingText(InputConnectionWrapper.java:145)
    at androidx.emoji2.viewsintegration.EmojiInputConnection.deleteSurroundingText(EmojiInputConnection.java:68)
    at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingText$31$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:851)
    at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda23.run(Unknown Source:8)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8741)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Device Info:
App version: 3.0.3
App version code: 414
Android build version: M526BRXXU1CVJ7
Android release version: 13
Android SDK version: 33

Device brand: samsung
Device manufacturer: samsung
Device name: m52xq
Device model: SM-M526BR
Device product name: m52xqxx
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: no_root

### Device info

- Device: Galaxy M52
- OS Version: Android 13
- App Manager Version: 3.0.3 (F-Droid)
- Mode: NonRoot

### Additional context

Shortcuts created by the app are watermarked. It seems that the only solution is to create a separate widget for shortcuts, which selects the app so that there is no watermark.

**Comment by MuntashirAkon** [comment]
> Shortcuts created by the app are watermarked. It seems that the only solution is to create a separate widget for shortcuts, which selects the app so that there is no watermark.

Watermarking is a great feature because it helps you keep track of shortcuts and prevent you from accidentally losing all the shortcuts by uninstalling an app.

**Comment by soheilkhanalipur** [comment]
I mean, you can use the solution of this app to remove the watermark of a shortcut…

https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker

**Comment by MuntashirAkon** [comment]
> I mean, you can use the solution of this app to remove the watermark of a shortcut…

No, it is an intended feature.

**Comment by MuntashirAkon** [comment]
This issue should be fixed in v3.0.4. Can you confirm?

**Comment by MuntashirAkon** [comment]
Fixed in 41fc0a0f178a8b62e181c6a500a13628ab201e9e
