### ISSUE TITLE
Bug report for Alpha buid

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#975]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

How to report bug for Alpha builds..
I am getting force close app while clicking on App lable under sorting options.

### Logs

java.lang.IllegalStateException: Only a single item should be checked
    at io.github.muntashirakon.AppManager.misc.ListOptions.lambda$init$0$io-github-muntashirakon-AppManager-misc-ListOptions(ListOptions.java:143)
    at io.github.muntashirakon.AppManager.misc.ListOptions$$ExternalSyntheticLambda2.onCheckedChanged(Unknown Source:2)
    at com.google.android.material.chip.ChipGroup$1.onCheckedStateChanged(ChipGroup.java:161)
    at com.google.android.material.internal.CheckableGroup.onCheckedStateChanged(CheckableGroup.java:184)
    at com.google.android.material.internal.CheckableGroup.access$300(CheckableGroup.java:43)
    at com.google.android.material.internal.CheckableGroup$1.onCheckedChanged(CheckableGroup.java:83)
    at com.google.android.material.internal.CheckableGroup$1.onCheckedChanged(CheckableGroup.java:79)
    at com.google.android.material.chip.Chip.lambda$new$0$com-google-android-material-chip-Chip(Chip.java:259)
    at com.google.android.material.chip.Chip$$ExternalSyntheticLambda0.onCheckedChanged(Unknown Source:2)
    at android.widget.CompoundButton.setChecked(CompoundButton.java:222)
    at com.google.android.material.chip.Chip.setChecked(Chip.java:722)
    at android.widget.CompoundButton.toggle(CompoundButton.java:139)
    at android.widget.CompoundButton.performClick(CompoundButton.java:144)
    at android.view.View.performClickInternal(View.java:7458)
    at android.view.View.access$3700(View.java:837)
    at android.view.View$PerformClick.run(View.java:28872)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8184)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

Device Info:
App version: 3.1.0-alpha02-DEBUG
App version code: 415
Android build version: R.202212101223
Android release version: 12
Android SDK version: 31
Android build ID: RMX3461_11_C.06
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
Inferred Mode: root

### Device info

- Device: Realme 9 se
- OS Version: A12
- App Manager Version: Alpha 2172
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 99575cb904fd9a6fef466ecb063ae0a73cfd8a58
